### ISSUE TITLE
Feature request: Port to 1.0 and submit textex to Inkscape's stock extensions

### ISSUE THREAD

**Issue by Esokrates** [textext/textext#107]
It would be great if you could follow
http://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0
and propose the extension to be part of the stock extensions.

Another thing I would wish for is the dummy window to disappear that shows up before the textext dialog appears. If you want a different issue to track this, no problem.

**Comment by sizmailov** [comment]
TexText has extra dependencies that prohibits its inclusion in stock extensions, IMO.

I agree dummy window is annoying, but I think there is no way to avoid it without modifying inkscape source code.

**Comment by sizmailov** [comment]
I [asked](https://gitlab.com/inkscape/inkscape/issues/156#note_174623053) a number of questions about inkscape 1.0 to clarify what needs to be done to support it. 

While GTK3 is required by inkscape the *python bindings* are NOT guaranteed to be installed in the interpreter. So we need to supply GTK3 installers/instructions. 

The extension is required to be python2/3-complaint. Which is a bit sad.

Here is short check-list: 
 - [X] Update GUI to GTK3
 - [ ] Adjust code for new `inkex.py` API
 - [ ] Remove `pdf->svg` dependency
 - [ ] Make extension python3-complaint

**Comment by sizmailov** [comment]
I filed an issue about dummy window https://gitlab.com/inkscape/inkscape/issues/267 . Maybe we will be able to get rid of it in near future)

**Comment by sizmailov** [comment]
It turns out that the required change to suppress dummy window was rather small. Hopefully it's going to be [merged](https://gitlab.com/inkscape/inkscape/merge_requests/698) in  inkscape 1.0 release.

**Comment by sizmailov** [comment]
:tada: :tada: :tada:
Inkscape 1.0 will hide "extension is working" window for extensions with custom GUI!

**Comment by leberwurstsaft** [comment]
That's so sweet!

**Comment by sizmailov** [comment]
Good news everyone! We can get rid of "extension is working" window in inkscape<1.0! See #138

**Comment by jcwinkler** [comment]
> Good news everyone! We can get rid of "extension is working" window in inkscape<1.0!

Thanks for figuring this out! This will be in release 0.11!

**Comment by jcwinkler** [comment]
See https://github.com/textext/textext/projects/1
