### ISSUE TITLE
More a question than a bug: How to re-edit latex formula?

### ISSUE THREAD

**Issue by corvus-albus** [textext/textext#108]
The website of the old textext version of Pauli Virtanen mentiones, that you can re-edit the latex input. 
Is it still a feature of textext? It isn't mentioned in the feature list and I wasn't sucessful triing it. 
I selected the object and started the extension but instead of reediting there was just a blank interface for inserting a new formula.
If editing is still possible than please give some hints in your docs at https://textext.github.io/textext/ .

cheers corvus-albus

P.S. Sorry for opening a bug-report for this but I didn't know which category to choose.

**Comment by sizmailov** [comment]
It's still the **main** feature of the plugin. 
Please make sure 
1) you didn't break TexText object group into pieces 
2) you select whole TexText object before invoking the plugin

If you still have troubles fill out required information for bug report, attach troubling .svg, screenshots, etc.

**Comment by corvus-albus** [comment]
Thank you for the quick reply. I was unsure because my first attempt didn't work. the following did. 
As I had a closer look at the files I saw
     inkscape:current-layer="surface1"
did prevent textext from recognizing the formula. After changing to the standard layer everything worked well. I don't know where this layer came from, it isn't list in the layer list and vanishes after switching to default "layer 1". 
Thank you for your time spending on answering. My problem is solved, you can close this issue.
