### ISSUE TITLE
Typo at https://textext.github.io/textext/install/linux.html

### ISSUE THREAD

**Issue by LouisZulli** [textext/textext#109]
To install xelatex on Ubuntu/Debian:
sudo apt-get install texlive-xelatex

That should be 

sudo apt-get install texlive-xetex

**Comment by sizmailov** [comment]
Thanks for report! Indeed.

**Comment by jcwinkler** [comment]
Thanks for reporting this, @LouisZulli , thanks for fixing, @sizmailov.
