### ISSUE TITLE
crash while: Run TexText GUI

### ISSUE THREAD

**Issue by RaulDurand** [textext/textext#114]
**Description of the problem/ steps to reproduce**
I downloaded the extension from github. Installation was sucessful.
[TexText][SUCCESS ]: --> TexText has been SUCCESSFULLY installed on your system <--

The problem seems to be in the line: 
  gui_config = asker.ask(save_callback, preview_callback)

**Steps to reproduce the behavior (if not obvious from description)**:
1. Start TexText
2. Two grey windows appear with no text inside. Inkscape freezes and becomes unusable.
3. Nothing else.

**Message(s) in error dialog (if this comes up)**

No error messages

**Logfile**
[textext.log](https://github.com/textext/textext/files/2841384/textext.log)

**Install log**
[install.log](https://github.com/textext/textext/files/2841373/install.log)

**Screenshots**
--

**System information**

- TexText version: downloaded on 07/02/2019 from github
- Inkscape version: 0.92
- Operating system: Debian 64 bits
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): pdf2svg
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): all of them
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Comment by sizmailov** [comment]
Thanks for the report!

Inkscape freeze is intended. It prevents you from changing document simultaneously with an extension and manually. 

The line you cited just starts TexText GUI window. 

Seems like PyGTK2 freezes for some reason. Are you able to run simple PytGTK2 application? 

```python

import pygtk

pygtk.require('2.0')
import gtk

window = gtk.Window()
label = gtk.Label("Hello, world!")
window.add(label)

window.show_all()
gtk.main()
```

Make sure to run it with `python2`

**Comment by RaulDurand** [comment]
Thanks for the reply.
I tested PyGTK2 with the code provided. It shows the Hello world! window nicely. 
Also python version is 2.7.13.

I use i3 window manager. 

I just tested with gnome wm and TexText works although there were some warnings:

```
Unable to locate theme engine in module_path: “adwaita”

Failed to load module “canberra-gtk-module”

** (__init__.py:26548): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

The first two warnings were removed by installing: `gnome-themes-standard` and `libcanberra-gtk-module`

Coming back to i3, still no luck. 
Thus, it seems that the problem is somehow related with i3.

**Comment by sizmailov** [comment]
TexText works under KDE without problems as well. 

> Thus, it seems that the problem is somehow related with i3.

Might be. But simple PyGTK app *is* working under i3, so TexText should too. 

So far the best we can do is to find the line which was executed last in `asktext.py`.
```python
# put those two lines at top of asktext.py
import logging
logger = logging.getLogger('TexText')
... 
# put next everywhere in `asktext.py`, the line numbers should be reported automatically
logger.debug("hello")
```

Attach the resulting `textext.log` file with all "hello"s from `asktext.py`

**Comment by RaulDurand** [comment]
I did as suggested. For some reason the file and line numbers are not correctly displayed in the log so I put some messages next to the word "hello". See the files:

[textext.log](https://github.com/textext/textext/files/2845384/textext.log)
[asktext.txt](https://github.com/textext/textext/files/2845385/asktext.txt)  (rename to .py)

The problem is in the line with `gtk.main()`. May be some particular setting is avoiding gtk to work properly.

**Comment by sizmailov** [comment]
Thanks for investigation! 

You may also want to try comment-out warning suppression in asktext.py:

https://github.com/textext/textext/blob/0a4b388f25df0613f3df8c66b934b6517bb0653b/extension/textext/asktext.py#L1116-L1117

Looks like PyGTK can't initialize/render some content of TexText window. Which version of PyGTK do you use? 

I think we need to construct analog of TexText GUI window and see which element leads to observed behavior.

**Comment by RaulDurand** [comment]
These are my gtk versions:
```
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
>>> gtk.pygtk_version
(2, 24, 0)
>>> gtk.gtk_version
(2, 24, 31)
```

One feature of i3wm is that it tends to tile new windows. Thus, it also might be with resizing.

I commented out that line but did not notice any extra information.

I managed to make TexText to work by forcing the use of Tk.

**Comment by sizmailov** [comment]
@RaulDurand Your Gtk version is recent, so all features should be available.. (sigh, it runs with Gnome, dumb me). Well, yes, Tk is viable workaround, but it's less powerful than Gtk version. 
 
Here is one more test since it might be connected with i3 composition:

Let's run TexText without inkscape. To do so you need an empty.svg file.

```bash
# set PYTHONPATH to find modules provided by inkscape
export PYTHONPATH=`inkscape --extension-directory`
# run TexText without inkscape 
python2 ~/.config/inkscape/extensions/textext/__init__.py empty.svg
```

TexText window should appear.

**Comment by RaulDurand** [comment]
I run the test as you said.
I saw flash in the screen and no TexText window. The terminal gets stuck in this command.
Maybe an option to use Tk could be included in the installer.

Thanks for the help in trying to solve the problem. Also thanks so much for the great work on TexText.

**Comment by sizmailov** [comment]
@cheshirekow Thanks for the input!

@RaulDurand Can you confirm fix is working for you? 

We wanted to have two rows of interface be of same height. Height of element is unknown before it's render, so we need to call `show()` first. At the same time height requirement does not have effect on already rendered elements, so we need to have `show()` call after setting heights equal. 
That the reason for having `show/hide/show` call sequence:

```python
                window.show()
                self.normalize_ui_row_heights() # requires knowledge of rendered heights 
                window.hide()
                window.show()
```

I admit, the `show/hide/show` hack is bad solution and needs to be replaced. But now I don't know how to do it properly. 

On my system height change is only 1px.  @jcwinkler Can we sacrifice equal heights of interface rows?

**Comment by jcwinkler** [comment]
> On my system height change is only 1px. @jcwinkler Can we sacrifice equal heights of interface rows?

I tested it on Windows with removed normalize/hide/show section and the change is - if it exists at all - only marginal.
