### ISSUE TITLE
TexText for Windows - missing packages

### ISSUE THREAD

**Issue by Toxicdafi** [textext/textext#118]
I just installed TexText for Windows, using https://textext.github.io/textext/install/windows.html and Inkscape 0.92.3 (64bit) Windows 10, 1803, pstoedit+ghostscript, PyGTK, MiKTeX 2.9 and TexText via batch and installer file (tried both)

When I tried to use TexText (everything was fine before) in Inkscape, I couldn't so I checked the log in MikTeX\pdflatex and :

- GUI Framework cannot be initialized

So, I tried to uninstall everything and re-install everything, the same error was happening.

And I discovered that I had to change the option in MikTeX for "Install missing packages on-the-fly" to "Yes". And now it's totally working.

Could you add that, in the installation process ? I struggled for 2 hours, and I think this can happen for everyone using Windows :) 

Bye :)

**Comment by jcwinkler** [comment]
Thank you very much for your report and your patience in fixing this on your own.

I know this problem (MiKTeX tries to install missing packages and waits for your confirmation to do so, but you are not notified...). I will add this to the documentation.

(Thought this is already catched, but obiously not...)

**Comment by sizmailov** [comment]
Does this error appear in TexText dialog with stdout/stderr fields? 

If so we might add custom latex output parser rules to form nice and clear error messages with link to corresponding section in FAQ/troubleshooting. 

Probably we need to implement a generic procedure to handle specific errors such as reported one.

**Comment by Toxicdafi** [comment]
I don't have a screenshot of this error, but when i was trying to do a compilation,  I had an error telling to check pdflatex logs, and nothing else (that's why i checked those logs) ! I think this was on the second scrolling menu.

**Comment by sizmailov** [comment]
@Toxicdafi I meant "TexText Error" dialog, see 
https://textext.github.io/textext/usage/troubleshooting.html#latex-and-toolchain-errors

**Comment by Toxicdafi** [comment]
It was exactly this error : https://textext.github.io/textext/_images/textext-error-dialog-stderr.png

**Comment by jcwinkler** [comment]
@Toxicdafi It is exactly the "install on the fly" error that produces this window, I made the screenshot you referenced with that MiKTeX feature enabled and a missing packages.
