### ISSUE TITLE
inkscape binary on macOS

### ISSUE THREAD

**Issue by ro0mquy** [textext/textext#120]
**Issue**
When installing on macOS, `./setup.py` can't find the inkscape binary:
```
`inkscape-bin` is NOT found in PATH
```

**Possible Solution**
My inkscape (installed with homebrew cask) places a binary just called `inkscape` in $PATH.
With `--inkscape-executable=/usr/local/bin/inkscape` the installation proceeds sucessfully.
The script should therefore look for `inkscape` instead of `inkscape-bin`.

**System information**
- TexText version: 0.10
- Inkscape version: Inkscape 0.92.2 5c3e80d, 2017-08-06
- Operating system: macOS 10.13.6

**Comment by jcwinkler** [comment]
Thank you for your report. I will update the setup.py so it tests for both, inkscape and inkscape-bin (the last one works on a friend's test system, inkscape not).

As a MAC user: If you have any suggestion w.r.t to the installation instructions do not hesitate to tell or to provide a pull request with improvements.

**Comment by ro0mquy** [comment]
Thanks for the work :) Besides this little issue the installation was a breeze. I think the only thing that would make it even easier is a homebrew formula.

**Comment by jcwinkler** [comment]
@ro0mquy Could you please download the most recent [MacOS installer development version](https://github.com/textext/textext/releases/tag/0.10.1-dev1) and re-run it on your system without the ``--inkscape-executable`` parameter? Inkscape should now be detected correctly.

**Comment by ro0mquy** [comment]
Works like a charm, thanks!
