### ISSUE TITLE
Font size selection

### ISSUE THREAD

**Issue by ro0mquy** [textext/textext#121]
I am writing my master's thesis in latex and want to use inkscape for making figures. I would like to match the font size of the document with the one of the figures.

**Is it possible to add an option for changing the font size used by textext?**

Further especially for very large and small sizes scaling the output is different from actually changing the font size.

**Comment by sizmailov** [comment]
Did you read https://textext.github.io/textext/usage/faq.html#faq-font-size
?

пт, 12 апр. 2019 г., 16:25 ro0mquy <notifications@github.com>:

**Comment by ro0mquy** [comment]
I'm sorry, apparently not. Thanks
