### ISSUE TITLE
Mac OS: Where is tmp.svg created? 

### ISSUE THREAD

**Issue by osbama** [textext/textext#125]
My tex->pdf->svg toolchain works perfectly both with the recommended text and in my daily use, however, textext does not work, since 

Command "/Applications/Inkscape.app/Contents/Resources/bin/inkscape -f tmp.svg --export-png tmp.png --export-area-drawing --export-dpi=200" 

fails with:  "Can't open file: tmp.svg (doesn't exist)" 

yes, neither can I find tmp.svg. Where does this file get created?

**Comment by sizmailov** [comment]
All data is created in temp directory, usually it's `/tmp/<temp dir>`, but it's deleted once it's no longer needed even in case of error. 

Did you try to manually reproduce textext toolchain https://textext.github.io/textext/usage/troubleshooting.html#trouble-manual-compile ? 

Please copy-paste manual testing results from terminal as markdown code block (enclose in triple back quotes  ```)
