### ISSUE TITLE
Incompatibility between Ghostsript 9.27 and pstoedit (all versions)

### ISSUE THREAD

**Issue by sindzicat** [textext/textext#126]
Hello!

I'm on Windows 8.1x64.

I created `test.tex`:

```latex
\documentclass{article}
\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}
\pagestyle{empty}
\begin{document}
$\sin(x^2) + \cos(x^2) = R^2$
\end{document}
```

Then compiled it. I tried `xelatex test.tex` and `pdflatex test.tex -interaction=nonstopmode -halt-on-error`. I got a pdf file. This file was fine and had the correct formula.

Then I tried:
```
"C:\Program Files\pstoedit\pstoedit.exe" -f plot-svg test.pdf test.svg -dt -ssp -psarg -r9600x9600 -pta
```

I got the following error:
```
pstoedit: version 3.73 / DLL interface 108 (built: Jun  3 2018 - release build - MS VC++ 1912 - 64-bit) : Copyright (C) 1993 - 2018 Wolfgang Glunz
Error: /undefined in .makeoperator
Operand stack:
   false   rectfill   rectfill   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1
%stopped_push   1991   1   3   %oparray_pop   1990   1   3   %oparray_pop   1978   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop
 .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--
Dictionary stack:
   --dict:1033/1123(G)--   --dict:0/20(G)--   --dict:216/300(L)--   --dict:1033/1123(G)--
Current allocation mode is global
Current file position is 15548
GPL Ghostscript 9.27: Unrecoverable error, exit code 1
PostScript/PDF Interpreter finished. Return status 1 executed command : C:\Program Files\gs\gs9.27\bin\gsdll64.dll -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS -r9600x9600 C:/Users/SINDZI~1/AppData/Local/Temp/psin2
The interpreter seems to have failed, cannot proceed !
```

How can I fix this?

Best regards,
Andrey.

**Comment by sindzicat** [comment]
Sorry, my mistake. I used gs927, but gs926 is needed.

**Comment by jcwinkler** [comment]
Hmm, looks like that the old DELAYBIND error re-appeared in gs 9.27 (see issue #2)... :angry:

**Comment by jcwinkler** [comment]
@sindzicat Thank you for reporting this. I released a new version of TexText the setup script of which detects the incompatible versions of pstoedit and ghostscript and informs the user.

I also contacted the developer of pstoedit for further assistance.

**Comment by sindzicat** [comment]
I'm glad my comment was useful :)
Many thanks for your nice extension! Now I have a nice tool to convert from tikz to svg too! :+1:

**Comment by musm** [comment]
Any updates on this?
I'd love to use ghostscript 9.27. Is the only solution to downgrade?

**Comment by sizmailov** [comment]
@musm As a workaround you can use alternative `pdf->svg` converter `pdf2svg`
https://textext.github.io/textext/install/linux.html#linux-install-pdf-to-svg-converter
https://textext.github.io/textext/install/windows.html#windows-install-pdf-to-svg-converter

**Comment by jcwinkler** [comment]
I contacted the developer of pstoedit and he provides a new version 3.74 now.:

https://sourceforge.net/p/pstoedit/bugs/25/

I will update the documentation soon.

**Comment by jcwinkler** [comment]
So, finally it turns out that this fix produces an ugly svg rendering and, hence, does not help:

![grafik](https://user-images.githubusercontent.com/11866252/58798229-625f9a80-8602-11e9-9338-342b93b44b1b.png)

**Comment by jcwinkler** [comment]
As already mentioned above by @sizmailov everybody who needs to use ghostscript 9.27 on his system is encouraged to use pdf2svg as converter. Refer to the installation instructions:
- [Windows](https://textext.github.io/textext/install/windows.html#windows-install-pdf-to-svg-converter)
- [Linux](https://textext.github.io/textext/install/linux.html#linux-install-pdf-to-svg-converter)
- [MacOs](https://textext.github.io/textext/install/macos.html#macos-install-pdf-to-svg-converter)
