### ISSUE TITLE
Avoid losing work upon pressing escape

### ISSUE THREAD

**Issue by tmoemke** [textext/textext#127]
When using TexText, I frequently lose my text by pressing Esc.

Solutions: (i) disable the shortcut (ii) or add a dialog in case that text was changed.

**Comment by jcwinkler** [comment]
I think this is a good suggestion which I will implement.

**Comment by sizmailov** [comment]
I think new "Settings" entry `Close TexText shortcut` with `Escape|Ctrl+Q|None` options should be enough.
