### ISSUE TITLE
Textext does not install on Ubuntu 19.04

### ISSUE THREAD

**Issue by cgoise** [textext/textext#129]
Hi,

textext does not install on Ubuntu 19.04.

Upon running 'setup.py' the following output is given:

```
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape
[TexText][SUCCESS ]: |      `inkscape` is found at `/usr/bin`
[TexText][CRITICAL]: /-and-* [Fail] Detect `python2.7`
[TexText][CRITICAL]: |      Expected python 2.7 but found `3.7.1 (default, Dec 14 2018, 19:28:38) `
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             https://textext.github.io/textext/install/linux.html#linux-install-python27
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex` is found at `/usr/bin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex` is found at `/usr/bin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex` is found at `/usr/bin`
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             https://textext.github.io/textext/install/linux.html#linux-install-gui-library
[TexText][CRITICAL]: |     /--or-* [Fail] PyGTK2 is not found
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             https://textext.github.io/textext/install/linux.html#linux-install-pygtk2
[TexText][CRITICAL]: |     /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   https://textext.github.io/textext/install/linux.html#linux-install-tkinter
[TexText][SUCCESS ]: /-and-+ [Succ] Detect pdf->svg conversion utility
[TexText][SUCCESS ]:       /--or-+ [Succ] Detect compatible pstoedit+ghostscript versions
[TexText][SUCCESS ]:       |     /-and-+ [Succ] 
[TexText][INFO    ]:       |     |     /-not-+ [Fail] Detect incompatible versions of pstoedit+ghostscript
[TexText][INFO    ]:       |     |           /--or-+ [Fail] 
[TexText][INFO    ]:       |     |           |     /-and-* [Fail] pstoedit=3.70 is not found (but pstoedit=3.73 is found)
[TexText][INFO    ]:       |     |           |     /-and-* [Fail] ghostscript=9.22 is not found (but ghostscript=9.26 is found)
[TexText][INFO    ]:       |     |           /--or-+ [Fail] 
[TexText][SUCCESS ]:       |     |                 /-and-* [Succ] pstoedit=3.73 is found
[TexText][INFO    ]:       |     |                 /-and-* [Fail] ghostscript=9.27 is not found (but ghostscript=9.26 is found)
[TexText][SUCCESS ]:       |     /-and-* [Succ] pstoedit is found
[TexText][SUCCESS ]:       |     /-and-* [Succ] ghostscript is found
[TexText][SUCCESS ]:       /--or-* [Succ] Detect pdf2svg:
[TexText][SUCCESS ]:              `pdf2svg` is found at `/usr/bin`
[TexText][ERROR   ]: Automatic requirements check found issue
[TexText][ERROR   ]: Follow instruction above and run install script again
[TexText][ERROR   ]: To bypass requirement check pass `--skip-requirements-check` to setup.py
```

Reason: the setup expects python 2.7 to be the default interpreter. Ubuntu apparently moved on to 3.7.1.

If setting `alias python='python-2.7'` before setup the install works well and textext appears in inkscapes menu. But still the extension does not work, as it checks the python version also during runtime. 

Error-message during runtime: `TexText][ERROR   ]: Python 2.7 is required, but found 3.7.1 (default, Dec 14 2018, 19:28:38) `, similar to the installer-message.

**System information**

- TexText version: 0.10.2
- Inkscape version: 0.92.4
- Operating system: Ubuntu 19.04, 64 bit
- SVG-converter installed: pdf2svg 0.2.3-1
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): PyGTK+PyGTK-Sourceview
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Comment by sizmailov** [comment]
@cgoise Thanks for the report!

Currently on linux one need to run install script with the same python interpreter which is used by inkscape (not sure it's explicitly mentioned in docs): 
```bash
python2 setup.py
```

By default inkscape uses `python` interpreter to run all python extensions including "TexText". 

Change inkscape python interpreter to `python2` as described here: http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters#Selecting_a_specific_interpreter_version_.28via_preferences_file.29

We do plan to switch to python3 along with inkscape (I think it will be inkscape 1.0)

@jcwinkler For now I think we should add "`python` is `python3` in recent systems" warning [here](https://textext.github.io/textext/install/linux.html#linux-install-python27) with instructions to change default inkscape interpreter to `python2`

**Comment by jcwinkler** [comment]
Please refer to the updated [Linux installation instructions](https://textext.github.io/textext/install/linux.html#linux-install-python27) to get this problem solved on your system.
