### ISSUE TITLE
PDF -> SVG converter necessary?

### ISSUE THREAD

**Issue by Gibtnix** [textext/textext#131]
First of all: great work, works just fine!

However, I don't really understand why we need an external PDF to SVG conversion tool?
Inkscape by itself can convert PDFs to SVG... I prefer to avoid unnecessary dependencies, thus I just wanted to quickly ask this question. Thanks for your time!

**Comment by sizmailov** [comment]
@Gibtnix Good point! Indeed, looks like 

```bash
inkscape -f input.pdf -z --export-area-drawing --export-dpi=300 --export-png=output.png
```

does the trick. We overlooked this opportunity when we removed imagemagick dependency :disappointed: 

If we eliminate `pdf->svg` the requirements will be as simple as Tex + GUI ! 

I'll make a patch to test `pdf->svg` conversion via inkscape.

**Comment by Gibtnix** [comment]
Thanks for the fast reply! Would be great if this dependency indeed could be removed. :-) 👍

**Comment by sizmailov** [comment]
It looks like there is no way to properly import pdf TeX graphics from command line into inkscape. Default importer replaces all text, so all typesetting is lost. 

I've opened an inkscape issue https://gitlab.com/inkscape/inkscape/issues/263.

**Comment by Gibtnix** [comment]
Thanks for updating, just did my own test and run exactly into the same issue; Poppler/Cairo works fine but Inkscape's internal conversion always replaces the fonts which messes up the. But assuming we can make Inkscape use Poppler/Cairo from command line, eliminating the external conversion is straightforward?

**Comment by sizmailov** [comment]
@Gibtnix Yes, it's the only obstacle. We also to need to handle backward compatibility issues, but they should not give us any troubles. 

Good news! inkscape 1.0 (not released yet) has `--pdf-poppler` option [(link)](https://gitlab.com/inkscape/inkscape/issues/263#note_174511580) We will be able to drop dependencies on next major update. 

(off topic) @jcwinkler What is the status GTK3 in terms of inkscape packaging? Is it guaranteed to be available along with inkscape 1.0 installation? If so we might want to include TexText into a builtin pack of inkscape extensions.

**Comment by Gibtnix** [comment]
Perfect, looking forward for TexText's release based on Inkscape 1.0 👍

**Comment by jcwinkler** [comment]
Another possibility is to use `dvisvgm` which is included in the standard TeX distros as far as I do see. It would require to compile via `latex` instead of `pdflatex` (or `xelatex -no-pdf` instead of `xetex` and `dvilualatex` instead of `lualatex`).

**Comment by pacuserra** [comment]
Don't know if it can be of any help, but I have been using pdf2svg in order to avoid the font substitution issue when importing PDF figures into Inkscape:

https://github.com/dawbarton/pdf2svg

It looks like it replaces text objects by symbols...

BTW, pdf2svg is based on Poppler and Cairo libraries.

**Comment by jcwinkler** [comment]
Yes, pdf2svg is already provided as an alternative in the installation instructions and the backend is implemented. 

Any dependency we drop helps us to avoid trouble during installation and daily usage, so the best way is to use any built-in methods, as @sizmailov suggested.

**Comment by jcwinkler** [comment]
Will be realized in release for Inkscape 1.0, see https://github.com/textext/textext/projects/1
