### ISSUE TITLE
Adding TexText to Inkscape extension manager

### ISSUE THREAD

**Issue by Foadsf** [textext/textext#132]
The addons' installation is difficult. Following the [other feature request](https://github.com/textext/textext/issues/117) and [this post](https://tex.stackexchange.com/a/377898/102825), I asked [this question](https://twitter.com/fsfarimani/status/1134035796590321664) and [I was told](https://twitter.com/realdoctormo/status/1134107821249847298):

> Martin Owens @realdoctormo :
> It's basically done, just needs more testing and maybe a couple of other developers to ponder the best ways of using it.

&nbsp;
It would be great if the TexText addon could be added to the experimental extension manager already. 

&nbsp;
**Additional context**
more information below [this Twitter thread](https://twitter.com/realdoctormo/status/1134107821249847298).

**Comment by sizmailov** [comment]
Extension manager is not going to be part of inkscape 1.0 release, probably 1.1.

If I understand correctly an extension is required to be a regular PYPI package to be installable via extension manager, so the integration of working extension will be trivial. 

Note: Extension manager will handle only python dependencies (TexText currently doesn't have any). System wide applications, such as latex, still need to be installed manually.

**Comment by doctormo** [comment]
Shipped in Inkscape and being available to Inkscape users isn't quite the same thing. We expect to release the extension manager as a stand alone app first during the 1.0 cycle. (depending on stability and testing)

External dependencies are going to be handled by using the `extras_require` check, this is a feature that's not there yet, but could be added easily enough. `extras_require={'system':['uniconv>=1.1']}` this code would look to see if the program uniconv existed on the system and only allow installing packages that satisfied the requirement. Further features would allow us to use Ubuntu's revere lookup to check for packages and offer to install the required packages for systems where that's possible.

**Comment by sizmailov** [comment]
I think we will add support for extension-manager right after port to 1.0.
