### ISSUE TITLE
live preview

### ISSUE THREAD

**Issue by Foadsf** [textext/textext#134]
I know it might be too much to ask, but having live preview could be really helpful. I have listed several examples [here in this post](https://tex.stackexchange.com/a/420307/102825). For example, an interface similar to [KLatexFormula ](https://klatexformula.sourceforge.io/) would be great.

**Comment by jcwinkler** [comment]
Thanks for the suggestion. I think this is a feature which is nice to have but which should not be considered as the most important now. We have to focus our limited resources on the transition to Inkscape 1.0 compatibility. Later we should evaluate how to further improve the extension.

**Comment by sizmailov** [comment]
I think a shortcut for preview will be a reasonable compromise.
