### ISSUE TITLE
TexText closing itself after pressing "safe"

### ISSUE THREAD

**Issue by sniperrat** [textext/textext#140]
TexText closes itself for me when pressing "safe". This is pretty annoying when I want to add many separate texts. Is it possible to add an option where the TexText window stays open after pressing "safe"?

**Comment by sizmailov** [comment]
No, it's not possible in current inkscape extension subsystem. 

Effectively inkscape dumps whole document to external program to stdin stream and reads it's output stream. There is no way to communicate to inkscape. 

The was a discussion of possible "extension communication protocol" on gitlab, but it's not going to be available any time soon

**Comment by sizmailov** [comment]
@sniperrat Are you aware of <kbd>Alt + Q</kbd> shortcut for previously used extension?

**Comment by sniperrat** [comment]
Thank you for the quick reply! Didn't know about the shortcut. That will ease my problems a little :)

**Comment by sizmailov** [comment]
Here is link to extensions with IO discussion: https://gitlab.com/inkscape/extensions/issues/8
