### ISSUE TITLE
Textext window does not open (Windows 10) if user extensions path does contain unicode characters (?)

### ISSUE THREAD

**Issue by jmcarm** [textext/textext#144]
Hello, I have installed Textext for Windows 10 64 bit following the instructions:
- Inkscape 0.92.4 64 bit
- PyGTK2 for Inkscape 0.92.4 64 bit
- pdf2svg 64 bit
- Textext with the setup script (that says that installation was successful).

I already had MikTeX installed in my system. When I open Inkscape, the name of the extension 'textext' appears. However, when I click on it, nothing happens.

I have checked that pdflatex and pdf2svg work fine in my system. Any idea of what may be happening?

Thanks very much.

**Comment by sizmailov** [comment]
Which version of TexText do you use? 


**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

**Comment by jmcarm** [comment]
Hi, sorry for the delay in answering. My version the TexText is 0.11. I
could not find the log file in the path you told me, but I suspected that
perhaps it was not able to write this log file because in the path, [Your
user name] contains both an accent and a space: C:\Users\José
Manuel\AppData\Roaming\inkscape\extensions\textext

So I have created a new user called "usuario2" and installed TexText for
him. In fact, in this account it works! So I think that was the problem. Is
it a bug? Do you know a way I could use TexText from my original account?

Thanks.

**Comment by sizmailov** [comment]
@jmcarm Please run the following command in console and paste output here. (login as troubling user). 

```bash
python -c 'import os; print(os.path.join(os.getenv("APPDATA"), "inkscape\extensions"))'
```

**Comment by jmcarm** [comment]
Hi, the previous command does not give any output on screen. The directory
exists, as you can see here:

[image: image.png]
Thanks.

**Comment by Shiroikoi** [comment]
I got the same problem, cutting the the textext folder and the textext.inx file from `C:\Users\凝紫秋萌\AppData\Roaming\inkscape\extensions` to `C:\Program Files\Inkscape\share\extensions` works for me

**Comment by jmcarm** [comment]
Great, moving the extension to the Inkscape\share\extensions folder worked
for me too! Thank you very much!

**Comment by jcwinkler** [comment]
I tested TexText with spaces and non ascii characters in the user name under Windows. No issues occured. Hence, I close this issue.
