### ISSUE TITLE
TexText dependencies

### ISSUE THREAD

**Issue by mundim** [textext/textext#145]
Hello

I'm trying to install textext in the new (beta) version of inkscape (1.0), but the dependencies check fails even having all the key packages installed, specially python27. I followed the instruction to skip the dependency check, but when using the extension, this check is run again and fail. It also can not find pdflatex but I do have it in the path. Any suggestions, please?
Thanks.

**Comment by sizmailov** [comment]
Please provide information required in issues template, including OS, textext version, etc

**Comment by mundim** [comment]
Sorry, I used a direct link from another page. So...

**Description of the problem/ steps to reproduce**
I tried to install textxt 0.11 in inkscape 1.0, but when installing textext0.11 by means of 

python setup.py

It failed because of CRITICAL issues, like missing python 2.7, the GUI library, PyGTK2.
Python 2.7 is indeed the default python version in my system and it is included in the path. Then I installed it with the option to skip the dependency check, since all key packages are installed (namelly pdflatex, pdf2svg).

The python 2.7 problem was solved editing Inkscape preferences.xml and under group "extensions", but then, other problems appeared.

When using the extension for the first time, apparently it run again the dependency check a popup window with exactly the same messages as when running "python setup.py" appeared.

**Steps to reproduce the behavior (if not obvious from description)**:
1. installed inkscape 1.0 for macOS (tried a beta version on a macos native version because in the older version of Inkscape textext was not working properly)
2. downloaded the new textext 0.11
3. activate python 2.7 as the default version in my system
4. run "python setup.py --skip-requirements-check"
5. in inkscape, go to Extensions -> Tex text

**Message(s) in error dialog (if this comes up)**

Please paste the error message(s) at the marked positions:

TexText][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '0.11.0' (md5sum = cdd7dc145364a80a56fdaa5c84096461)
[TexText][DEBUG   ]: platform.system() = 'Darwin'
[TexText][DEBUG   ]: platform.release() = '18.7.0'
[TexText][DEBUG   ]: platform.version() = 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64'
[TexText][DEBUG   ]: platform.machine() = 'x86_64'
[TexText][DEBUG   ]: platform.uname() = ('Darwin', 'MacBook-Pro.local', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64', 'x86_64', 'i386')
[TexText][DEBUG   ]: platform.mac_ver() = ('10.14.6', ('', '', ''), 'x86_64')
[TexText][DEBUG   ]: sys.executable = '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python'
[TexText][DEBUG   ]: sys.version = '2.7.16 (default, Sep  7 2019, 20:10:32) \n[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]'
[TexText][DEBUG   ]: os.environ = {'PYTHONIOENCODING': 'UTF-8', 'FONTCONFIG_PATH': '/Applications/Inkscape.app/Contents/Resources/etc/fonts', 'XDG_DATA_HOME': '/Users/mundim/Library/Application Support/Inkscape/data', 'GIO_MODULE_DIR': '/Applications/Inkscape.app/Contents/Resources/lib/gio/modules', 'GTK_EXE_PREFIX': '/Applications/Inkscape.app/Contents/Resources', 'LOGNAME': 'mundim', 'USER': 'mundim', 'HOME': '/Users/mundim', 'PATH': '/Applications/Inkscape.app/Contents/MacOS:/Applications/Inkscape.app/Contents/Frameworks/Python.framework/Versions/Current/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'DISPLAY': '/private/tmp/com.apple.launchd.WNPr7nV7eq/org.macports:0', 'LANG': 'en_BR', 'SHELL': '/bin/bash', 'SHLVL': '0', 'XPC_FLAGS': '0x0', 'PANGO_SYSCONFDIR': '/Applications/Inkscape.app/Contents/Resources/etc', 'GTK_DATA_PREFIX': '/Applications/Inkscape.app/Contents/Resources', 'GTK_PATH': '/Applications/Inkscape.app/Contents/Resources', 'XDG_CONFIG_HOME': '/Users/mundim/Library/Application Support/Inkscape/config', 'XPC_SERVICE_NAME': '0', 'PYTHONPATH': '/Users/mundim/Library/Application Support/Inkscape/config/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated-simple', 'INKSCAPE_DATADIR': '/Applications/Inkscape.app/Contents/Resources/share', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.FPvena9T5L/Listeners', 'XDG_CACHE_HOME': '/Users/mundim/Library/Application Support/Inkscape/cache', 'PANGO_RC_FILE': '/Applications/Inkscape.app/Contents/Resources/etc/pango/pangorc', 'PANGO_LIBDIR': '/Applications/Inkscape.app/Contents/Resources/lib', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.uLXzmHlObU/Render', 'LC_ALL': 'en_BR', 'INKSCAPE_LOCALEDIR': '/Applications/Inkscape.app/Contents/Resources/share/locale', 'TMPDIR': '/var/folders/qv/hykh_xrs31b1mdhr46bcbh540000gn/T/', 'XDG_CONFIG_DIRS': '/Applications/Inkscape.app/Contents/Resources/etc/xdg', 'LC_MESSAGES': 'en_BR', 'GDK_PIXBUF_MODULE_FILE': '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache', 'GTK_IM_MODULE_FILE': '/Applications/Inkscape.app/Contents/Resources/etc/gtk-3.0/gtk.immodules', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'XDG_DATA_DIRS': '/Applications/Inkscape.app/Contents/Resources/share', 'PWD': '/'}
[TexText][INFO    ]: Using `inkscape-executable` = `/Applications/Inkscape.app/Contents/MacOS/Inkscape`
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape
[TexText][SUCCESS ]: |      inkscape is found at `/Applications/Inkscape.app/Contents/MacOS/Inkscape`
[TexText][SUCCESS ]: /-and-* [Succ] Detect `python2.7`
[TexText][SUCCESS ]: |      python2.7 is found at `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python`
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gui-library[0m
[TexText][CRITICAL]: |     /--or-* [Fail] PyGTK2 is not found
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-pygtk2[0m
[TexText][CRITICAL]: |     /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-tkinter[0m
[TexText][CRITICAL]: /-and-+ [Fail] Detect pdf->svg conversion utility
[TexText][CRITICAL]:        Please follow installation instructions at 
[TexText][CRITICAL]:               [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-pdf-to-svg-converter[0m
[TexText][CRITICAL]:       /--or-+ [Fail] Detect compatible pstoedit+ghostscript versions
[TexText][CRITICAL]:       |      Please follow installation instructions at 
[TexText][CRITICAL]:       |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-pstoedit[0m
[TexText][SUCCESS ]:       |     /-and-+ [Succ] 
[TexText][INFO    ]:       |     |     /-not-+ [Fail] Detect incompatible versions of pstoedit+ghostscript
[TexText][INFO    ]:       |     |           /--or-+ [Fail] 
[TexText][INFO    ]:       |     |           |     /-and-* [Fail] pstoedit=3.70 is not found
[TexText][INFO    ]:       |     |           |     /-and-* [Fail] ghostscript=9.22 is not found
[TexText][INFO    ]:       |     |           /--or-+ [Fail] 
[TexText][INFO    ]:       |     |                 /-and-* [Fail] pstoedit=3.74 is not found
[TexText][INFO    ]:       |     |                 /-and-* [Fail] ghostscript=9.27 is not found
[TexText][CRITICAL]:       |     /-and-* [Fail] pstoedit is not found
[TexText][CRITICAL]:       |     |      Please follow installation instructions at 
[TexText][CRITICAL]:       |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-pstoedit[0m
[TexText][CRITICAL]:       |     |      If pstoedit is installed in custom location, specify it via 
[TexText][CRITICAL]:       |     |             --pstoedit-executable=<path-to-pstoedit>
[TexText][CRITICAL]:       |     |      and run setup.py again
[TexText][CRITICAL]:       |     /-and-* [Fail] ghostscript is not found
[TexText][CRITICAL]:       |            Please follow installation instructions at 
[TexText][CRITICAL]:       |                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-pstoedit[0m
[TexText][CRITICAL]:       |            If ghostscript is installed in custom location, specify it via 
[TexText][CRITICAL]:       |                   --ghostscript-executable=<path-to-ghostscript>
[TexText][CRITICAL]:       |            and run setup.py again
[TexText][CRITICAL]:       /--or-* [Fail] Detect pdf2svg:
[TexText][CRITICAL]:              `pdf2svg` is NOT found in PATH
[TexText][CRITICAL]:              Please follow installation instructions at 
[TexText][CRITICAL]:                     [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-pdf2svg[0m
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

<details>

<summary>dialog output (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stdout (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>


**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 0.11
- Inkscape version: 1.0 (the same happen for 0.92)
- Operating system: [e.g. Windows 10, 1803, 32-bit] MacOS 10.14.6 Mojave)
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): pdf2svg
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): PyGTK
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Comment by sizmailov** [comment]
Currently there is no release of TexText which supports inkscape >=1.0. But you may give a try to the [dev version](https://github.com/textext/textext/commits/develop) which is compatible with inkscape 1.0

**Comment by mundim** [comment]
Thanks. I'll try it.

**Comment by jcwinkler** [comment]
Running the dev version of TexText on an AppImage of Inkscape 1.0beta in parallel with an installed version of Inkscape 0.92.x will not succeed. I will release some instructions how to cope with this.

**Comment by jcwinkler** [comment]
See https://textext.github.io/textext/install/linux-beta.html
