### ISSUE TITLE
textext fails at runtime on Ubuntu Disco

### ISSUE THREAD

**Issue by paolocrosetto** [textext/textext#168]
I install TexText alright, but then when launching it, it complains that a module named 'elements' does not exist. 

[TexText][ERROR   ]: No module named elements
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 110, in <module>
    import inkex.elements
ImportError: No module named elements

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new

**Comment by sizmailov** [comment]
It looks like you are trying to use textext 1.0-dev with older version of inkscape. Either upgrade inkscape to 1.0+ or use TexText <1.0

@jcwinkler https://github.com/textext/textext/issues/new doesn't have bug template, link needs to be updated to https://github.com/textext/textext/issues/new?template=bug_report.md

**Comment by paolocrosetto** [comment]
thanks. I followed instructions for 0.92.4 (beware, in your website the instructions are for 0.94, which as far as I know does not exist). But i ma now upgrading inkscape to 1.0beta. Thanks again.

**Comment by jcwinkler** [comment]
> in your website the instructions are for 0.94

Ah, yeah. Thanks. I will fix this.
