### ISSUE TITLE
ImportError: No module named pygtk

### ISSUE THREAD

**Issue by cossio** [textext/textext#18]
I get this error. 

ImportError: No module named pygtk

However, I can import pygtk from the python interpreter.

**Comment by jcwinkler** [comment]
Please provide some information about the operating system and the Inkscape version. Thanks! 

Am 9. April 2018 17:35:51 MESZ schrieb Jorge Fernandez-de-Cossio-Diaz <notifications@github.com>:
>I get this error. 
>
>ImportError: No module named pygtk
>
>However, I can import pygtk from the python interpreter.

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cossio** [comment]
Inkscape 0.92.
Linux Mint 18

**Comment by jcwinkler** [comment]
Hm, the ImportError should be caught. I do not understand this error at all

Just to be sure: 

1. Please provide the full error back trace.

2. Did you use the TexText zip or tgz install package?

3. Did you check the pygtk import in a python2 or python3 interpreter?

**Comment by cossio** [comment]
@jcwinkler This is the actual error I get. I was tinkering with the .py source file and that was why the exception was not caught.

I checked import pygtk in python2.


Traceback (most recent call last):
  File "textext.py", line 90, in <module>
    from asktext import AskerFactory
  File "/home/cossio/.var/app/org.inkscape.Inkscape/config/inkscape/extensions/asktext.py", line 60, in <module>
    raise RuntimeError("Neither pygtk nor Tkinter is available! \n Hint: If you updated Inkscape "
RuntimeError: Neither pygtk nor Tkinter is available! 
 Hint: If you updated Inkscape from 0.48 to 0.91 under Windows you have to reinstall PyGTK!

**Comment by laods** [comment]
I have the same problem as @cossio (exact same output)

Inkscape 0.92.03 
Ubuntu 18.04
tgz install package

I was able to import pygtk in python2.

Remark that I had to add
sys.path.append('/snap/inkscape/4019/share/inkscape/extensions')
to textext.py in order for it to find inkex

**Comment by jcwinkler** [comment]
Hmm, the question is if Inkscape really calls the interpreter you used for testing the pygtk import. Currently, I am testing on kubuntu 17.10 and doe not observe any issues. I will check it on a fresh 18.04 install.

**Comment by jcwinkler** [comment]
@laods, @cossio: I cannot reproduce the problem on Kubuntu 18.04 + Inkscape 0.92.3.

What's the out put of `ll /usr/bin/python*` on your system?

**Comment by laods** [comment]
@jcwinkler: First of all I am really sorry for my late reply. My excuse is that I defended my PhD thesis this monday, so I have been too busy the last weeks.

`ll /usr/bin/python*` produce the following:
/usr/bin/python -> python2.7*
/usr/bin/python2 -> python2.7*
/usr/bin/python2.7*
/usr/bin/python2.7-config -> x86_64-linux-gnu-python2.7-config*
/usr/bin/python2-config -> python2.7-config*
/usr/bin/python3 -> python3.6*
/usr/bin/python3.6*
/usr/bin/python3.6-config -> x86_64-linux-gnu-python3.6-config*
/usr/bin/python3.6m*
/usr/bin/python3.6m-config -> x86_64-linux-gnu-python3.6m-config*
/usr/bin/python3-config -> python3.6-config*
/usr/bin/python3m -> python3.6m*
/usr/bin/python3m-config -> python3.6m-config*
/usr/bin/python-config -> python2.7-config*
/usr/bin/pythontex -> ../share/texlive/texmf-dist/scripts/pythontex/pythontex.py*
/usr/bin/pythontex3*

**Comment by jcwinkler** [comment]
> I defended my PhD thesis

You have my full understanding for any delays resulting from this! 

The output of the `ll /usr/bin/python*` is exactly the same on my system.

There is only one test we can do now. Since you have already worked in the textext source files please do the following:

Open the file `asktext.py` in the extension directory and navigate to the line `import os`. Just after the line insert:

``` python
import inkex
import sys
inkex.debug(sys.argv)
inkex.debug(sys.executable)
inkex.debug(sys.exec_prefix)
inkex.debug(sys.path)
```

Make sure there are no indents!

When the extension fails to load please copy the full output in the error message and post it here so we can see which python interpreter is called and where your gtk failes reside. On my system I have

```
['textext.py', '/tmp/ink_ext_XXXXXX.svgASO0JZ']
/usr/bin/python
/usr
['/home/winkler/.config/inkscape/extensions', '/usr/share/inkscape/extensions', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/winkler/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0', '']
... tranceback ...
```

Thank you very much!

**Comment by laods** [comment]
```
['textext.py', '/tmp/ink_ext_XXXXXX.svgUEJEKZ']
/snap/inkscape/4019/usr/bin/python
/snap/inkscape/4019/usr
['/home/larsod/snap/inkscape/4019/extensions', '/snap/inkscape/share/inkscape/extensions', '/snap/inkscape/4019/usr/lib/python2.7', '/snap/inkscape/4019/usr/lib/python2.7/plat-x86_64-linux-gnu', '/snap/inkscape/4019/usr/lib/python2.7/lib-tk', '/snap/inkscape/4019/usr/lib/python2.7/lib-old', '/snap/inkscape/4019/usr/lib/python2.7/lib-dynload', '/home/larsod/.local/lib/python2.7/site-packages', '/snap/inkscape/4019/usr/lib/python2.7/dist-packages', '/snap/inkscape/4019/usr/lib/python2.7/dist-packages/PILcompat', '/snap/inkscape/4019/lib/python2.7/site-packages', '', '/snap/inkscape/4019/share/inkscape/extensions', '/snap/inkscape/4019/share/inkscape/extensions']\
```

Then `ll /snap/inkscape/4019/usr/bin/python*` produce 
```
/snap/inkscape/4019/usr/bin/python -> python2.7*
/snap/inkscape/4019/usr/bin/python2 -> python2.7*
/snap/inkscape/4019/usr/bin/python2.7*
/snap/inkscape/4019/usr/bin/python3 -> python3.5*
/snap/inkscape/4019/usr/bin/python3.5*
/snap/inkscape/4019/usr/bin/python3.5m*
/snap/inkscape/4019/usr/bin/python3m -> python3.5m*
```

So it seems like inkscape is using its own python binary in this snap directory. I am not so familar with snap, but I was not allowed to ("Read-only file system") change the links.

**Comment by jcwinkler** [comment]
I think the easiest solution is to do

`snap remove inkscape`

followed by

`sudo apt-get install inkscape`

so you drive inkscape not in the snap environment and you have access to the pygtk package you have already installed into your python distribution under /usr/bin.

Does this "solve" your problem?

**Comment by laods** [comment]
Yes, it solved this problem. 
However, then another problem is encountered: I have Ghostscript 9.22, which is listed under 'Known issues' in the README file. I guess I will have to try getting an older verson of GS or wait for support for pstoedit.

**Comment by jcwinkler** [comment]
Great to hear! The snap packagement by Canonical seems to break the complete Inkscape extension system, see e.g. https://github.com/evil-mad/axidraw/issues/57 , there other packages of inkscape are not found (That's why you had to add the line to sys.path).

When you use TexText 0.8 you can install **pdf2svg** so you do not need ghostscript. See step 4 in https://github.com/jcwinkler/textext/wiki/Installation-specific-instructions-for-Linux-systems

**Comment by laods** [comment]
I installed pdf2svg, but still get the same error. Do I have to tell someone to use pdf2svg instead of ghostscript?

**Comment by laods** [comment]
```
Command pstoedit -f plot-svg /tmp/tmpdHZy2E/tmp.pdf /tmp/tmpdHZy2E/tmp.svg -dt -ssp -psarg -r9600x9600 -pta failed (code 1): pstoedit: version 3.70 / DLL interface 108 (built: Aug 29 2017 - release build - g++ 7.2.0 - 64-bit) : Copyright (C) 1993 - 2014 Wolfgang Glunz

 *** WARNING - the DELAYBIND command has been deprecated, and will be
               removed in the next version. For now you can restore
               the behaviour by using -dREALLYDEALYBIND but if you
               require continued use of this command you should contact
               the Ghostscript developers. Commercial customers of
               Artifex should email their support contact, free users
               are encouraged to talk to us on the #ghostscript IRC
               channel on irc.freenode.net.

Unrecoverable error: undefined in DELAYBIND
PostScript/PDF Interpreter finished. Return status 65280 executed command : /usr/bin/gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS -r9600x9600 "/tmp/psin2dnvIl"
The interpreter seems to have failed, cannot proceed !

Traceback (most recent call last):
  File "/home/larsod/.config/inkscape/extensions/asktext.py", line 491, in cb_ok
    self.callback(self.text, self.preamble_file, self.global_scale_factor)
  File "textext.py", line 224, in <lambda>
    old_node),
  File "textext.py", line 321, in do_convert
    new_node = converter.convert(text, preamble_file, scale_factor)
  File "textext.py", line 988, in convert
    self.pdf_to_svg()
  File "textext.py", line 1064, in pdf_to_svg
    raise RuntimeError(latest_message())
RuntimeError: Command pstoedit -f plot-svg /tmp/tmpdHZy2E/tmp.pdf /tmp/tmpdHZy2E/tmp.svg -dt -ssp -psarg -r9600x9600 -pta failed (code 1): pstoedit: version 3.70 / DLL interface 108 (built: Aug 29 2017 - release build - g++ 7.2.0 - 64-bit) : Copyright (C) 1993 - 2014 Wolfgang Glunz

 *** WARNING - the DELAYBIND command has been deprecated, and will be
               removed in the next version. For now you can restore
               the behaviour by using -dREALLYDEALYBIND but if you
               require continued use of this command you should contact
               the Ghostscript developers. Commercial customers of
               Artifex should email their support contact, free users
               are encouraged to talk to us on the #ghostscript IRC
               channel on irc.freenode.net.

Unrecoverable error: undefined in DELAYBIND
PostScript/PDF Interpreter finished. Return status 65280 executed command : /usr/bin/gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS -r9600x9600 "/tmp/psin2dnvIl"
The interpreter seems to have failed, cannot proceed !
```

**Comment by laods** [comment]
Yes. If I look briefly into textext.py, it seems like pdf2svg is a newer implementation than what is included in my tarball (TexText-Linux-0.7.2.tgz). I can't remember where i got mine from, but I will try the newest release.

**Comment by laods** [comment]
And now it works! 
(TexText-Linux-0.8-beta3.tgz)
Thanks for helping me out.

**Comment by jcwinkler** [comment]
Good to hear and thanks for your patience. 

To sum up we have to state that the snap package management of ubuntu caused the import error problems. In fact, if one installs Inkscape via snap the extension system seems to be broken (I tested this also with other extensions). I will file a bug report.
