### ISSUE TITLE
Wrong version of TexText for Inkscape 0.92 in documentation

### ISSUE THREAD

**Issue by CorentinChauvin** [textext/textext#180]
Hello!

The links to the .zip and .targz archives are wrong in the documentation of the version corresponding to Inkscape 0.92 (here: https://textext.github.io/textext/install/linux.html#linux-install-textext). It is indeed pointing to the 1.0 version, and it seems to be the same for the Windows archive.

Cheers,
Corentin

**Comment by jcwinkler** [comment]
Yes, I will fix this. Thanks for reporting!

**Comment by CorentinChauvin** [comment]
Welcome. Thanks for providing this tool!

**Comment by jcwinkler** [comment]
Fixed doc is online now.
