### ISSUE TITLE
Textext error with inkex.py

### ISSUE THREAD

**Issue by luis87krausser** [textext/textext#182]
Hello! I was trying to install textext1.0.0 on inskcape 1.0beta2 and when executing the extension I receive the following error message:
[TexText][ERROR   ]: No module named 'inkex'
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 109, in <module>
    import inkex
ModuleNotFoundError: No module named 'inkex'

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new

The setup.py file gave me a similar error, so I copied from the command line the files contained in the "extension" folder that I downloaded from:
https://github.com/textext/textext/releases/tag/1.0.0-dev.1#release

I currently use 64-bit Fedora 31, scientific spin, and I have python3 installed.
If you can help me, I would greatly appreciate it.
Greetings.

**Comment by sizmailov** [comment]
Thanks for report! 

Unfortunately link embed in textext does not have right bug report template. Can you please update your post by adding info required [here](https://github.com/textext/textext/issues/new?assignees=&labels=&template=bug_report.md&title=)? (Don't create new issue, update this one)

It would help us to figure out issue details. At the moment it looks like inkscape bug / or improper installation of inkscape. Can't tell more until you update the post.

**Comment by jcwinkler** [comment]
@luis87krausser Did you unpack your Inkscape 1.0beta2 package from an AppImage as described [here](https://textext.github.io/textext/install/linux-beta.html)? If so does the command

``` bash
ls ~/squashfs-root/share/inkscape/extensions/inkex
```
work? And what's its output?

**Comment by luis87krausser** [comment]
Guys I already solved the problem. The steps I took were the following:
1. Clear all trace of inkscape on pc.
1. Install inkscape with dnf (dnf-and install inkscape), and thus have Inkscape 1.0beta2.
2. Then, download textext-1.0.0-dev.1, extract the content and place myself in the created textext directory.
3. Execute the python3 setup.py --inkscape-executable / usr / bin / inkscape command.
4. Download the Inkscape-2b71d25-x86_64.AppImage image into a new folder with:
wget -c https://inkscape.org/gallery/item/16199/Inkscape-2b71d25-x86_64.AppImage
5. Enter the folder and execute the commands:
chmod u + x Inkscape-2b71d25-x86_64.AppImage
./Inkscape-2b71d25-x86_64.AppImage --appimage-extract
6. Then navigate to "... / squashfs-root / share / inkscape / extensions /", copy its contents and paste it into "/home/your-user/.config/inkscape/extensions/"

That solved my problem. I hope my answer is clear. I will try to make a video tutorial about it.
regards

**Comment by luis87krausser** [comment]
> @luis87krausser Did you unpack your Inkscape 1.0beta2 package from an AppImage as described [here](https://textext.github.io/textext/install/linux-beta.html)? If so does the command
> 
> ```shell
> ls ~/squashfs-root/share/inkscape/extensions/inkex
> ```
> 
> work? And what's its output?

Apparently dnf installs a very basic version of inkscape. Without the extensions. From AppImage I took the extensions folder and that solved the lost packages that prevented textext from working.
