### ISSUE TITLE
Mac OS issues - "No module name elements"

### ISSUE THREAD

**Issue by darredondo1** [textext/textext#183]
I followed the instructions listed, and I get the following error during setup.py (I know it said to ignore errors regarding Tkinter / gtk), so i subsequently ran setup with --skip-requirements-check

'''
[TexText][INFO    ]: Using `inkscape-executable` = `/Applications/Inkscape.app/Contents/MacOS/Inkscape`
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][UNKNOWN ]: /-and-* [Ukwn] Detect inkscape>=1.0
[TexText][UNKNOWN ]: |      Can't determinate inkscape version
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex` is found at `/usr/local/bin`
[TexText][SUCCESS ]: |     |      `pdflatex` is found at `/Library/TeX/texbin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex` is found at `/usr/local/bin`
[TexText][SUCCESS ]: |     |      `lualatex` is found at `/Library/TeX/texbin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex` is found at `/usr/local/bin`
[TexText][SUCCESS ]: |            `xelatex` is found at `/Library/TeX/texbin`
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]:        Please follow installation instructions at 
[TexText][CRITICAL]:               https://textext.github.io/textext/install/macos.html#macos-install-gui-library
[TexText][CRITICAL]:       /--or-* [Fail] GTK3 is not found
[TexText][CRITICAL]:       |      Please follow installation instructions at 
[TexText][CRITICAL]:       |             https://textext.github.io/textext/install/macos.html#macos-install-pygtk2
[TexText][CRITICAL]:       /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]:              Please follow installation instructions at 
[TexText][CRITICAL]:                     https://textext.github.io/textext/install/macos.html#macos-install-tkinter
'''

When I run the extension in inkscape a window pops up with the following error:
'''
[TexText][ERROR   ]: No module named elements
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 110, in <module>
    import inkex.elements
ImportError: No module named elements

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new
'''

**Comment by sizmailov** [comment]
Thanks for report!

Unfortunately link embed in textext does not have right bug report template. Can you please update your post by adding info required here? (Don't create new issue, update this one)

It would help us to figure out issue details. 

(probably you have 0.x inkscape installed, which is incompatible with textext 1.0)

**Comment by darredondo1** [comment]
That was the answer - I'm now using textext 0.11.0, thank you for your time.
