### ISSUE TITLE
Installation instructions for TexText 1.0 fail on Kubuntu 19.10

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#185]
**Description of the problem/ steps to reproduce**
1. Follow the installation instructions for TexText 1.0 for Inkscape 1.0 beta2 on Ubuntu 19.10 
2. After having downloaded and extracted the AppImage it is not possible to launch inkscape from the `~/squashfs/bin`dir. It results in the error message

   ```bash
   *** stack smashing detected ***: <unknown> terminated
   Terminated (dumping memory)
   ```

**Remarks**
- Under Ubuntu 18.04 this works flawlessly.
- Running the Appimage directly by calling ~./Inkscape-2b71d25-x86_64.AppImage successfully launches Inkscape on Ubuntu 19.10.
- The natural way of **not** unpacking the downloaded AppImage and installing TexText with the option 
   ```bash
   python setup.py --inkscape-executable ~/Inkscape-2b71d25-x86_64.AppImage
   ```
   does not work: While TexText passes the requirements checks during setup it fails during execution of the extension. It does not find the gtk/tk bindings although they are installed. Obviously, the python environment in the launched AppImage does not see the system environment and, hence, not the gtk bindings. This can also be reproduced on Ubuntu 18.04

Any idea of how providing an Inkscape 1.0 / TexText 1.0  test environment on Kubuntu 19.10 without overwriting the existing Inkscape 0.92.4 installation?

**Comment by jcwinkler** [comment]
Reason for crash of inkscape when launched from `squashfs-root\bin` directory: `inkscape`-binary has been compiled against lib versions which are not compatible with the ones installed on Ubuntu 19.10. When launched directly as `~./Inkscape-2b71d25-x86_64.AppImage` the `AppRun` script is called (which can be found in bin directory of extracted AppImage). This script sets the `LIBRARY_PATH` to the libs bundled in the AppImage so everything is fine.

In this script also the `PYTHONHOME` is set to the minimal Python bundled with the AppImage. That's why the gtk bindings are not found when TexText is invoked from within `~./Inkscape-2b71d25-x86_64.AppImage`.

Hmm :face_with_head_bandage:

**Comment by sizmailov** [comment]
IMO it's inkscape issue, and should be solved not here. Although we can warn people about existing problems and give some workaround hints. 

Extracting and interfering with self-contained application archives does not sound to me as a reliable way of obtaining software. It should be done with care and requires some expertize (i believe) above average inkcape users. I would not recommend it as primary way of obtaining inkscape 1.0. As long as inkscape is not released I would not provide any compatibilitiy guarantees between textext and inkscape, except maybe latest inkscape's master. It gets too complex and would require us to have tons of intermediate inkscape versions to test against... 

That said I think it's relatively safe to change PYTHON* env variables in script as inkscape is not compiled against any python version, it just issues `exec` calls. So all this recommendations falls into "try it on your own risk" category.

**Comment by jcwinkler** [comment]
Yeah it is too much. Lets limit "support" to TT 1.0 for Kubuntu 18.04 as long as Inkscape 1.0 final is not released.
