### ISSUE TITLE
TexText 1.0 (Windows): TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

### ISSUE THREAD

**Issue by mBarreau** [textext/textext#186]
Installation is impossible on Windows 10 Education (Version 1809, built 17763.973). It was working previously and it stopped working few days ago. I tried re-installing the software and I get the same error.

**Steps to reproduce the behavior (if not obvious from description)**:
Install TexText.

**Message(s) in error dialog (if this comes up)**
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from requirements_check import \
  File "extension\textext\requirements_check.py", line 699, in <module>
    defaults = WindowsDefaults()
  File "extension\textext\requirements_check.py", line 89, in __init__
    self._tweaked_syspath = wap.get_non_syspath_dirs() + os.environ["PATH"].split(os.path.pathsep)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

The error gets corrected (but the extension if then not recognized in Inkscape) if line 56 of win_app_path is changed to
return [dirname] if _os.path.isdir(dirname) else []

**System information**

- TexText version: last version
- Inkscape version: last version
- Operating system: [e.g. Windows 10, 1809, 64-bit]
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): pstoedit
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): ...
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MikTeX
- Windows only: TexText installed via batch script or installer file: batch file

**Comment by jcwinkler** [comment]
Thanks, @mBarreau. I will investigate this. You fix is correct but the reason for the extension not appearing in Inkscape not.

**Comment by jcwinkler** [comment]
@mBarreau Most likely the error results from the fact that no old Inkscape 0.92.x is installed in C:\Program Files\Inkscape. Then None has been returned by win_app_path. This is fixed now.

You state you do not see the extension in Inkscape. Did you look under the `Extension\Text` **sub**-menu entry? It has been moved there from `Extension` according to new extension subsystem guideline.

**Comment by mBarreau** [comment]
Oh I see, I will reinstall it and I will tell you. I didn't try in the text
menu. I come back to you soon

Le lun. 24 févr. 2020 à 14:23, Jan Winkler <notifications@github.com> a
écrit :

**Comment by mBarreau** [comment]
That's indeed working !
Thanks,
Matth

Le lun. 24 févr. 2020 à 15:39, Matthieu BARREAU <namorgin@gmail.com> a
écrit :
