### ISSUE TITLE
TexText 1.0: Unknown options --without-gui, --export-file

### ISSUE THREAD

**Issue by orengt** [textext/textext#188]
Just installed TexText-Windows-1.0.0-dev.2 for: inkscape-1.0beta2_2020-02-06_235953b-x64.

I'm trying to create a formula.
I entered a simple one as $V_0$ and when preview/save I get the following error:

Command D:\Software Download\Inkscape\inkscape-1.0beta2_2020-02-06_235953b-x64\inkscape\bin\inkscape.exe --without-gui --pdf-poppler --pdf-page=1 --export-type=png --export-area-drawing --export-dpi=300 --export-file tmp.png tmp.pdf failed (code 1)

(org.inkscape.Inkscape:5472): GLib-GIO-WARNING **: 16:17:01.192: win32 session dbus binary not found: D:\Software Download\Inkscape\inkscape-1.0beta2_2020-02-06_235953b-x64\inkscape\bin\\gdbus.exe
Unknown option --without-gui

**Comment by sizmailov** [comment]
Hi, thanks for report. inkscape recently removed `--without-gui` command line option. 

The fix would be to remove `--without-gui` option from `textext/__init__.py` (two occurrences)

Alternatively you can use inkscape beta snapshot before approximately mid-January (I believe).

**Comment by orengt** [comment]
Sergei,

Thanks a lot for your quick response, it helps a lot.
I removed the options and it works.
Oren

**Comment by Masacroso** [comment]
You must also change in __init__.py the string --export-file by --export-filename (it appear twice also). Then, with these two changes, the extension work for the actual beta2 version of inkscape.

**Comment by jcwinkler** [comment]
Confirmed in most recent beta2 version. I'll fix it.

**Comment by jcwinkler** [comment]
Unfortunately, these changes in the Inkscape extension API do only float into the Windows build of Inkscape beta2. This is built on a nightly basis whereas the Linux AppImage build reflects the state of December 3rd 2019 of Inkscape beta 2, hence does not have the change --export-file -> --export-filename.

(I will update the TexText 1.0 Windows package manually)
