### ISSUE TITLE
Wrong link for tar-file in documentation

### ISSUE THREAD

**Issue by alcrene** [textext/textext#191]
In the installation instructions for Inkscape 0.92 (https://textext.github.io/textext/install/linux.html), despite https://github.com/textext/textext/issues/180, the direct link at the bottom for the `.tar.gz` file still points to the dev version, which of course is incapable with v0.92.

The `.zip` link is correct.

**Comment by jcwinkler** [comment]
Thanks for reporting. I fix this.

**Comment by jcwinkler** [comment]
Updated doc is online.
