### ISSUE TITLE
Import inkex.svg fails

### ISSUE THREAD

**Issue by sabian2008** [textext/textext#194]
**Description of the problem/ steps to reproduce**
Extension crashes on startup because it cannot import `inkex.svg`

**Steps to reproduce the behavior (if not obvious from description)**:
1. Install `inkscape` from Fedora repositories using `dnf`.
2. Rebase the `/usr/share/inkscae/extensions` with the extensions from Inkscape's [Gitlab](https://gitlab.com/inkscape/extensions), because the Fedora package is trimmed down.
3. Install *TexText* as always, installation succeeds. 
4. Try to open *TexText* inside Inkscape and see it crash.

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

[TexText][ERROR   ]: No module named 'inkex.svg'
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 586, in <module>
    import inkex.svg
ModuleNotFoundError: No module named 'inkex.svg'

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md

</details>

<details>
<summary>output of stdout (if available):</summary>
</details>

<details>
<summary>output of stderr (if available):</summary>
</details>

**Logfile**
Same info as dialog error.

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 1.0 Latest
- Inkscape version: 1.0beta2
- Operating system: Fedora 31 amd64, fully updated.
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): Both
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): PyGTK

I think the crash makes sense because in `__init__.py` you import `inkex.svg` and that submodule doesn't exist now, [proof](https://gitlab.com/inkscape/extensions/-/tree/master/inkex). 

P.S: The problem persists if I don't rebase with the latest `extension` repo from Gitlab, with a plain `dnf` installation. I did the upgrade to see if it was solved by a newer version of extensions. It wasn't.

**Comment by sizmailov** [comment]
Thanks for the report! 

Indeed, recent changes in `inkscape/extensions` are breaking (https://gitlab.com/inkscape/extensions/-/merge_requests/178), and we didn't update dev branch of TexText to match: 

> This API change introduces one backwards imcompatible change:
`from inkex.svg import SvgDocumentElement` must be changed to from `inkex.elements import SvgDocumentElement`

I'll create a MR to fix that.

**Comment by sizmailov** [comment]
> P.S: The problem persists if I don't rebase with the latest extension repo from Gitlab, with a plain dnf installation. I did the upgrade to see if it was solved by a newer version of extensions. It wasn't. 

Is the error same to what you have with updated extensions?

**Comment by sabian2008** [comment]
Yes the error is the same IIRC, but will test it tomorrow to be sure.

Thanks for the quick answer and dedication. I'll try reverting `inkex` to a previous version that contains `svg` and report here, so to help other users that might find this same problem during Inkscape 1.0 transition.

**Comment by renatobellotti** [comment]
I'm also on Fedora 31. I followed the installation instructions for Ubuntu using the Inkscape release from the Fedora repo and the correct path to the inkscape binary. Running `setup.py` tells me that the installation was successful. When I try to create Latex text, I get the following error:

```
[TexText][ERROR   ]: No module named 'inkex'
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 109, in <module>
    import inkex
ModuleNotFoundError: No module named 'inkex'

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md
```

I'm using the following version of the extension: `TexText 1.0.0-dev.2 (2020-02-10)`

I'm currently writing my master's thesis and time is a critical factor, so I just ask: Do you think this can be fixed soon, or should I use workarounds like including screenshots of equations?

**Comment by sizmailov** [comment]
@renatobellotti your error is different from what @sabian2008 had. Probably you have broken installation of inkscape. It's better to see full log (full log is enabled after first fail and right after installation).

**Comment by sabian2008** [comment]
I checked and Fedora from repos gives the same error that @renatobellotti has. It seems like Fedora is shipping a VERY narrow extensions directory.

@renatobellotti I suggest you try installing inkscape beta from flatpak es described in the documentation of TeXText. Installing Inkscape v0.92 from Fedora 30 (http://rpmfind.net/linux/rpm2html/search.php?query=inkscape) could also be a short-term solution.

**Comment by renatobellotti** [comment]
> I checked and Fedora from repos gives the same error that @renatobellotti has. It seems like Fedora is shipping a VERY narrow extensions directory.
> 
> @renatobellotti I suggest you try installing inkscape beta from flatpak es described in the documentation of TeXText. Installing Inkscape v0.92 from Fedora 30 (http://rpmfind.net/linux/rpm2html/search.php?query=inkscape) could also be a short-term solution.

Thanks for your answer. For me, it is not a priority right now, and I don't want to mess up my Inkscape installation before I've handed in my thesis. But I'm willing to do some testing in case you want to support the Inkscape version in the Fedora 31 repo.

**Comment by jcwinkler** [comment]
The original error (also affecting most current Inkscape Windows beta builds) is fixed now in the develop branch.
