### ISSUE TITLE
fail to open topmodule-gtk ubuntu-mate while saving texText formula

### ISSUE THREAD

**Issue by OrnithOrtion** [textext/textext#195]
**I try to save a formula on an inkscape drawing with texText, but it fails.**
A window opens and this message is displayed 

<details>
<summary>`Gtk-Message: 07:39:34.459: Failed to load module "topmenu-gtk-module"
`
I tried to remove ":topmenu-gtk" from /etc/X11/Xsession.d/99mate-environment as 
https://ubuntu-mate.community/t/gtk-message-failed-to-load-module-topmenu-gtk-module/4964 
proposed but it didn't solve any thing. 
I try also to completely remove this old file, but it didn't resolve more.

[textext.log](https://github.com/textext/textext/files/4398356/textext.log)

</summary>

</details>

**Logfile**

**System information**

- TexText version: 0.11.0
- Inkscape version: 0.92
- Operating system: Ubuntu-Mate 32 Bits (laptop) 18.04
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): pstoedit and pdf2svg
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): Tkinter at least, pyGTK probably

**Comment by jcwinkler** [comment]
Please try

```bash
sudo apt-get install topmenu-gtk2:i386
```

**Comment by OrnithOrtion** [comment]
I can't install the package. Note, that I have Ubuntu Mate 18.04, may be it could help ?
> E: Unable to locate package topmenu-gtk2:i386

**Comment by OrnithOrtion** [comment]
Hello, I solved the issue by running 
`env GTK_MODULES="canberra-gtk-module" /usr/bin/inkscape`
According to the following forum,
[https://askubuntu.com/questions/1079133/how-to-install-libtopmenu-gtk-modules](url)

I still wonder if this little command needs to be entered for each time I want to use TexText.

**Comment by OrnithOrtion** [comment]
Indeed, when I launch Inkscape  again, without the previous command (i. e. with the desktop launcher), the same Error message displays.

**Comment by OrnithOrtion** [comment]
Ok, I am not sure, but it seems to print the formula, even if an error message is printed.
Thank you.
