### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by derMart** [textext/textext#198]
I installed the version 0.11.0 with PyGTK2 and  pdf2svg on a texlive Ubuntu 18.04 system with Inkscape 0.92.3 (official canonical package).
While saving a tex object I get: 

> Gtk-Message: 11:08:52.118: Failed to load module "canberra-gtk-module"

The svg object is created correctly though.

kind regards

**Comment by derMart** [comment]
after installing the libcanberra-gtk-module package the error is gone:
`sudo apt install libcanberra-gtk-module`
One might consider adding this package to the dependencies: https://textext.github.io/textext/install/linux.html

**Comment by jcwinkler** [comment]
Thanks for the report. It seems to be related to #195.

It is interesting that this problem occurs in the well tested ubuntu 18.04 / Inkscape 092.3 / TexText 0.11 environment. I will test it with a fresh system on a VM.

**Comment by OrnithOrtion** [comment]
Just for your information, installing  libcanberra-gtk-module didn't solve anything in my case, in fact, this package was already installed on my machine.
Nevertheless the issue conserns almost all the GUI program (such as Qt creator, Caja and so on for instance...), and seems not to disable proper work of these software, including inkscape...

**Comment by jcwinkler** [comment]
I cannot reproduce the problem on a fresh ubuntu 18.04. So, unfortunately, I have no idea at the moment.
