### ISSUE TITLE
Migration to pdf2svg

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#2]
TexText uses pstoedit for the conversion of the LaTeX generated pdf snippet to a svg node. Pstoedit itself depends on calls to ghostscript. Unfortunately, a certain option has been marked deprecated in ghostscript > 9.20 which is used by pstoedit. Hence, generation of the pdf snippet fails.

As an alternative we have decided to give the possibility to use another converter: pdf2svg. Work is currently in progress.

See [Issue 48](https://bitbucket.org/pitgarbe/textext/issues/48/ghostscript-still-bug-under-linux) and [Issue 57](https://bitbucket.org/pitgarbe/textext/issues/57/pdf2svg-migration).

**Comment by jcwinkler** [comment]
Current status of development can be found at branch [feature/pdf2svg_support](https://github.com/jcwinkler/textext/tree/feature/pdf2svg_support) at my fork until pull-request #20 goes into this repo. Requires that pdf2svg is in your path. Tk interface not working 100%.

**Comment by sizmailov** [comment]
Is `pstoedit` still supported as a backup converter or it completely deprecated?

**Comment by sizmailov** [comment]
Right now plugin requires `pdf2svg` and does not fallback to `pstoedit` if `pdf2svg` is not found.

**Comment by jcwinkler** [comment]
This is correct, as stated in pull request #20:

> Code works only if pdf2svg is found on the path. To use pstoedit comment/uncomment CONVERTERS in lines 1199/ 1200. (Will be in one list in final release).

**Comment by sizmailov** [comment]
Indeed, I'm sorry, overlook that.

**Comment by jcwinkler** [comment]
Provided in release 0.8.
