### ISSUE TITLE
TexText 1.0: Re-compilation of nodes created with TexText 0.x flips result vertically

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [textext/textext#205]
Hi,
Previously, I worked with stable Inkscape (0.92) along with textext. Everything worked like charm.
I upgraded Inkscape to the 1.x via [this AUR (Arch User Repository) package](https://aur.archlinux.org/packages/inkscape-git/).
It seems to come without any extensions, some of which are needed by Textext 1.0, so I extracted the Inkscape AppImage and copied the squashfs-root/usr/share/inkscape/extensions/ contents to my ~/.config/inkscape/extensions/ directory.
Then, I installed textex as recommended in the instructions, with python3 and gtk3 bindings.
It works as expected.

I just noticed a minor bug :
I worked on a file where there are some textext objects created before the upgrade (ie with textext 0.11). I can edit them with the new environment, but when saving changes, the edited box is mirrored. You can simply mirror them again to get the proper result so this is not a serious issue, but still I thought you should know.
Note that newly created textext objects are editable properly.
Regards,
Guillaume.

**Comment by jcwinkler** [comment]
@GuillaumeLeGoc  I confirm this error. Re-edited objects are mirrored alon the horizontal axis. Thank you for the report.

Additional bug: If the old nodes are colored in Inkscape this color information is lost (will open a separate issue).

**Comment by jcwinkler** [comment]
Here is the candidate:

https://github.com/textext/textext/blob/e12df682f4d5aed27dfda042d95d88d08a335699/textext/base.py#L704-L707

**Comment by jcwinkler** [comment]
So this is fixed now. I will publish this in the next dev releases when I have fixed #206 .
