### ISSUE TITLE
Python interpreter set in inkscape preferences is ignored in requirements check

### ISSUE THREAD

**Issue by veltsov** [textext/textext#212]
Inkscape provides a possibility to set up python interpreter for extensions in `preferences.xml` like this
```
 <group
     id="extensions"
     python-interpreter="inkscape1-python" />
``` 
The TexText extension calls python for tests in `requirements_check.py` like this
```
    def find_pygtk3(self):
        try:
            executable = sys.executable
            defaults.call_command([executable, "-c", "import gi;"+
                                                     "gi.require_version('Gtk', '3.0');"+
                                                     "from gi.repository import Gtk, Gdk, GdkPixbuf"])
```
As one can see, the inkscape preference is ignored and for a non-standard installation the test can fail, even if everything is set up correctly (that is, replacing `sys.executable` in the above code with `os.path.expanduser("~/bin/inkscape1-python")` makes everything working). The difference here is that  `sys.executable` is just an executable name, while inkscape preference refers to a script, which e.g. first set up necessary environments variables for the executable to work.
So either TexText should respect inkscape preference (when set), or run the test commands in the current python interpreter (why is starting a new python process needed at all?)

**Comment by sizmailov** [comment]
If the only side effect of the custom script are env variables everything should be fine and you should see no difference (as those changes are inherited by by child processes, see simplified example below). Don't think other side effects are desirable or common to care about (please correct me if I'm wrong).

```bash
export MY_ENV=Hello
python -c 'import subprocess, sys; subprocess.call([sys.executable, '-c', 'import os; print(os.environ)'])"
```

In principle we can parse `preferences.xml` and extract info from it, but this example doesn't convinced me that we should. 

Another thing that we can do is avoid GTK3 bindings check after inkscape 1.0 release. This would finally reduce requirements check to a trivial form which should to be refactored to something else. It used to be helpful back then when we were relying on bunch of various third party tools. Now when all is provided by inkscape we don't need this machinery.

**Comment by veltsov** [comment]
Unfortunately, practice shows that it does not work this simple way (see also issue #175 which is probably similar). It's obvious that nobody tampers with random environment names, but sensitive ones (like dynamic library path) can be modified in the call chain. In any case, if you insist on starting a separate python interpreter, the correct approach is to respect inkscape preference (I do not think one can argue about that). I am still not convinced, though, that the separate process is needed. Why not to try loading those packages in the running interpreter? It's wrapped in try: except: anyway.

**Comment by sizmailov** [comment]
The referred code does simple library importability check. Use of separate interpreter is an artifact from time when inkscape interpreter could have been different from current one. Now all those checks (and separate interpreter calls) are obsolete and can be removed.
