### ISSUE TITLE
Compilation issue with esvect package

### ISSUE THREAD

**Issue by Bobyl** [textext/textext#214]
Hi,
In order to produce nice looking vector arrows, I use the [esvect ](https://www.ctan.org/pkg/esvect) package in my latex documents.
In order to use this package in textext, I added the following line to default_packages.tex:
`\usepackage[b]{esvect}`

Textext fails with the following output:
>[TexText][DEBUG   ]: Enforcing DEBUG mode due to previous exit code `60`
>[TexText][DEBUG   ]: TexText initialized
>[TexText][DEBUG   ]: TexText version = '0.11.0' (md5sum = cdd7dc145364a80a56fdaa5c84096461)
>[TexText][DEBUG   ]: platform.system() = 'Windows'
>[TexText][DEBUG   ]: platform.release() = '10'
>[TexText][DEBUG   ]: platform.version() = '10.0.18362'
>[TexText][DEBUG   ]: platform.machine() = 'AMD64'
>[TexText][DEBUG   ]: platform.uname() = ('Windows', 'Pebbles', '10', '10.0.18362', 'AMD64', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
>[TexText][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')
>[TexText][DEBUG   ]: sys.executable = 'C:/Program Files/Inkscape/pythonw.exe'
>[TexText][DEBUG   ]: sys.version = '2.7.17 (default, Oct 23 2019, 05:20:31)  [GCC 9.2.0 64 bit (AMD64)]'
>[TexText][DEBUG   ]: os.environ = {'TMP': 'C:\\Users\\jcimb\\AppData\\Local\\Temp', 'ONEDRIVECONSUMER': 'C:\\Users\\jcimb\\OneDrive', 'COMPUTERNAME': 'PEBBLES', 'USERDOMAIN': 'PEBBLES', 'INTEL_DEV_REDIST': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3a09', 'SYSTEMROOT': 'C:\\WINDOWS', 'PATH': 'C:\\Program Files\\Inkscape;C:\\Program Files\\Inkscape;C:\\Program Files\\Inkscape\\python;C:\\Program Files\\Inkscape\\python\\Scripts;C:\\Program Files\\Inkscape\\python;C:\\Program Files\\Inkscape\\python;C:\\Program Files\\Inkscape\\perl;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\ImageMagick-7.0.8-Q16;C:\\tools\\Anaconda3;C:\\tools\\Anaconda3\\Library\\mingw-w64\\bin;C:\\tools\\Anaconda3\\Library\\usr\\bin;C:\\tools\\Anaconda3\\Library\\bin;C:\\tools\\Anaconda3\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\PDFtk\\bin\\;C:\\Program Files (x86)\\Bitvise SSH Client;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\ProgramData\\chocolatey\\bin;C:\\tools\\platform-tools;C:\\Program Files\\Calibre2\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\GNU\\GnuPG\\pub;C:\\texlive\\2020\\bin\\win32;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler;C:\\Users\\jcimb\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\gs\\gs9.50\\bin;C:\\Program Files\\Oracle\\VirtualBox;C:\\Program Files\\pdf2svg', 'MIC_LD_LIBRARY_PATH': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\intel64_win_mic', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'TEMP': 'C:\\Users\\jcimb\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Users\\jcimb\\AppData\\Local', 'HOMEPATH': '\\Users\\jcimb', 'USERDOMAIN_ROAMINGPROFILE': 'PEBBLES', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'jcimb', 'LOGONSERVER': '\\\\PEBBLES', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'PYTHONPATH': 'C:\\Program Files\\Inkscape\\share\\extensions;C:\\Program Files\\Inkscape\\python;C:\\Program Files\\Inkscape\\python\\Lib;C:\\Program Files\\Inkscape\\python\\DLLs', 'CHOCOLATEYTOOLSLOCATION': 'C:\\tools', 'ONEDRIVE': 'C:\\Users\\jcimb\\OneDrive - Lyc\xe9e Priv\xe9 Sainte Genevi\xe8ve', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'INKSCAPE_LOCALEDIR': 'C:\\Program Files\\Inkscape\\share/locale', 'ONEDRIVECOMMERCIAL': 'C:\\Users\\jcimb\\OneDrive - Lyc\xe9e Priv\xe9 Sainte Genevi\xe8ve', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\jcimb\\AppData\\Roaming', 'HOMEDRIVE': 'C:', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '8', 'CHOCOLATEYLASTPATHUPDATE': '132173649005690395', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\jcimb'}
>[TexText][SUCCESS ]: + [Succ] TexText requirements
>[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape
>[TexText][SUCCESS ]: |      `inkscape.exe` is found at `C:\Program Files\Inkscape`
>[TexText][SUCCESS ]: |      `inkscape.exe` is found at `C:\Program Files\Inkscape`
>[TexText][SUCCESS ]: |      `inkscape.exe` is found at `C:\Program Files\Inkscape`
>[TexText][SUCCESS ]: |      `inkscape.exe` is found at `C:\ProgramData\chocolatey\bin`
>[TexText][SUCCESS ]: /-and-* [Succ] Detect `python2.7`
>[TexText][SUCCESS ]: |      python2.7 is found at `C:\Program Files\Inkscape\pythonw.exe`
>[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
>[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex.exe` is found at `C:\texlive\2020\bin\win32`
>[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex.exe` is found at `C:\texlive\2020\bin\win32`
>[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex.exe` is found at `C:\texlive\2020\bin\win32`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][INFO    ]: |     /--or-* [Fail] PyGTK2 is not found
[TexText][INFO    ]: |     |      Please follow installation instructions at 
[TexText][INFO    ]: |     |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-pygtk2[0m
[TexText][SUCCESS ]: |     /--or-* [Succ] TkInter is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect pdf->svg conversion utility
[TexText][INFO    ]:       /--or-+ [Fail] Detect compatible pstoedit+ghostscript versions
[TexText][INFO    ]:       |      Please follow installation instructions at 
[TexText][INFO    ]:       |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-pstoedit[0m
[TexText][SUCCESS ]:       |     /-and-+ [Succ] 
[TexText][INFO    ]:       |     |     /-not-+ [Fail] Detect incompatible versions of pstoedit+ghostscript
[TexText][INFO    ]:       |     |           /--or-+ [Fail] 
[TexText][INFO    ]:       |     |           |     /-and-* [Fail] pstoedit=3.70 is not found
[TexText][INFO    ]:       |     |           |     /-and-* [Fail] ghostscript=9.22 is not found (but ghostscript=9.50 is found)
[TexText][INFO    ]:       |     |           /--or-+ [Fail] 
[TexText][INFO    ]:       |     |                 /-and-* [Fail] pstoedit=3.74 is not found
[TexText][INFO    ]:       |     |                 /-and-* [Fail] ghostscript=9.27 is not found (but ghostscript=9.50 is found)
[TexText][INFO    ]:       |     /-and-* [Fail] pstoedit is not found
[TexText][INFO    ]:       |     |      Please follow installation instructions at 
[TexText][INFO    ]:       |     |             [94m[4mhttps://textext.github.io/textext/install/windows.html#windows-install-pstoedit[0m
[TexText][INFO    ]:       |     |      If pstoedit is installed in custom location, specify it via 
[TexText][INFO    ]:       |     |             --pstoedit-executable=<path-to-pstoedit>
[TexText][INFO    ]:       |     |      and run setup.py again
[TexText][SUCCESS ]:       |     /-and-* [Succ] ghostscript is found
[TexText][SUCCESS ]:       /--or-* [Succ] Detect pdf2svg:
[TexText][SUCCESS ]:              `pdf2svg.exe` is found at `C:\Program Files\pdf2svg`
[TexText][DEBUG   ]: TexText.effect
[TexText][DEBUG   ]:   Pdf2SvgPlotSvg is usable
[TexText][DEBUG   ]:   Can't adjust scale to account node transformations done in inkscape. May result in loss of scale.
[TexText][DEBUG   ]:   Using default node alignment `middle center`
[TexText][DEBUG   ]:   Using default tex converter `lualatex` 
[TexText][DEBUG   ]:   Using default preamble file `default_packages.tex`
[TexText][DEBUG   ]:   Run TexText GUI
[TexText][DEBUG   ]:     TexText.do_convert
[TexText][DEBUG   ]:       args:
[TexText][DEBUG   ]:         converter = <__main__.Pdf2SvgPlotSvg object at 0x0000000003391e50>
[TexText][DEBUG   ]:         original_scale = None
[TexText][DEBUG   ]:         text = u'$\\frac{a}{b}$\n$\\vv{a}$\n'
[TexText][DEBUG   ]:         tex_command = u'lualatex'
[TexText][DEBUG   ]:         preamble_file = 'default_packages.tex'
[TexText][DEBUG   ]:         user_scale_factor = 1.0
[TexText][DEBUG   ]:         old_svg_ele = None
[TexText][DEBUG   ]:         tex_executable = 'C:\\texlive\\2020\\bin\\win32\\lualatex.exe'
[TexText][DEBUG   ]:         self = <__main__.TexText instance at 0x0000000002ff05f0>
[TexText][DEBUG   ]:         alignment = 'middle center'
[TexText][DEBUG   ]:       args: done
[TexText][DEBUG   ]:       Converting tex to svg
[TexText][DEBUG   ]:         Converting .tex to svg element
[TexText][DEBUG   ]:           Converting .tex to .pdf
[TexText][DEBUG   ]:             Parsing LaTeX log file
[TexText][DEBUG   ]:             Parsing LaTeX log file done
[TexText][DEBUG   ]:           Converting .tex to .pdf failed
[TexText][DEBUG   ]:         Converting .tex to svg element failed
[TexText][DEBUG   ]:       Converting tex to svg failed
[TexText][DEBUG   ]:     TexText.do_convert failed
[TexText][DEBUG   ]:   Run TexText GUI failed
[TexText][DEBUG   ]: TexText.effect failed
[TexText][ERROR   ]: 7: Error: Undefined control sequence \vv.
Problem exists here: $\vv

>[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 1156, in <module>
    effect.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 289, in affect
    self.effect()
  File "__init__.py", line 341, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "asktext.py", line 445, in ask
    tex_command_tk_str.get())
  File "__init__.py", line 331, in save_callback
    original_scale=current_scale)
  File "__init__.py", line 442, in do_convert
    new_svg_ele = converter.convert(text, preamble_file, scale_factor, tex_executable)
  File "__init__.py", line 661, in convert
    self.tex_to_pdf(tex_command, latex_text, preamble_file)
  File "__init__.py", line 620, in tex_to_pdf
    raise TexTextConversionError(parsed_log, error.return_code, error.stdout, error.stderr)
TexTextConversionError: 7: Error: Undefined control sequence \vv.
Problem exists here: $\vv

>[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new

I tried manually building the following MWE:

>\documentclass{article}
\usepackage{amsmath,amsthm,amssymb,amsfonts,libertinus}
\usepackage[b]{esvect}
\usepackage{color}
\pagestyle{empty}
\begin{document}
$\vv{a}$
\end{document}

with lualatex, then apply pdf2svg: no errors on compilation and output looks nice in inkscape.

Is it a problem with textext or am I missing something?

**Comment by jcwinkler** [comment]
Since the `\vv` command is not regognized I assume that the package `esvect` is not loaded in the preamble file Inkscape is using. Please double check that you entered the package name in the **correct** preamble file. On Windows you find it in `c:\Users\[Your Username]\AppData\Roaming\inkscape\extensions\textext\`

You can check if your preamble file is used by Inkscape by entering something wrong in that file, e.g. just `\xyz` and then compile a simple snippet. TexText should complain about something like `Undefined control sequence. <recently read> \xyz`

**Comment by Bobyl** [comment]
Silly me.
I edited `c:\Users\[Your Username]\AppData\Roaming\inkscape\extensions\textext\default_packages.tex` which was not, by default, the one used by textext.
Thanks for the quick answer and solution.
