### ISSUE TITLE
Error prevents running the extension on macOS

### ISSUE THREAD

**Issue by emanueledalsasso** [textext/textext#218]
I have followed step by step the installation instruction (from the very beginning, i.e. installation of inkscape using homebrew) on macOS Catalina Version 10.15.3. Yet, I get this error when trying to open tex text, along with the opening of XQuartz:

[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.0rc1 is found
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-latex[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

**Comment by jcwinkler** [comment]
I guess you are using TexText 1.0-dev.4, am I right?

The log states that setup does not find your LaTeX executable. Does the command `pdflatex --version` produces any output on the console from which you are launching the TexText setup?

**Comment by emanueledalsasso** [comment]
> I guess you are using TexText 1.0-dev.4, am I right?
Yes, you are.

Here is the output of `pdflatex --version` from the terminal I launched `python setup.py`:

pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02

**Comment by jcwinkler** [comment]
I think this is similar to #150 

Please enter `which pdflatex` in the terminal you are launching the setup from. Copy the result, e.g.`/opt/local/bin/pdflatex` and call setup with the option: `python setup.py --pdflatex-executable /opt/local/bin/pdflatex` (Replace the path to the pdflatex exe by the result of the `which` command)

Does this help?

**Comment by emanueledalsasso** [comment]
this time I managed to run the extension. I simply wrote down $\hat{x}$, I could display the preview in the window opened but I tried to save inkscape came up with the following message:
`
(__main__.py:30785): Gtk-WARNING **: 15:03:41.423: Locale not supported by C library.
	Using the fallback 'C' locale.

(__main__.py:30785): Gtk-WARNING **: 15:03:41.916: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 1): image not found

(__main__.py:30785): Gtk-WARNING **: 15:03:41.916: Loading IM context type 'quartz' failed`

**Comment by jcwinkler** [comment]
OK thanks. This is definitely an Inkscape bug. I will come back to this later.

You would do me and the TexText project a great favour if you could sketch the steps you performed for installation of Inkscape, LaTeX and TexText. Just a few words to outline the procedure. I will then make an updated doc. Thanks!

**Comment by emanueledalsasso** [comment]
EDIT: despite the message, it properly adds the desired text on my inkscape document.

Anyway, here you have the list of commands I have followed.
1. I installed inkscape
> brew cask install inkscape
2. I installed `pdf2svg`
> brew install pdf2svg
3. Installed the `mactex package`
> brew cask install mactex
4. Run installation of TexText: 
> python setup.py --skip-requirements-check

Then I run inkscape (from the app or the terminal, the result is the same) and when I save the text I write down in the TexText window I get the error outlined before.

Moreover, this is what I get if simply run `python setup.py`:

> TexText][INFO    ]: Using `pdflatex-executable` = `/Library/TeX/texbin/pdflatex`
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.0rc1 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/Library/TeX/texbin/pdflatex`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex` is found at `/Library/TeX/texbin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex` is found at `/Library/TeX/texbin`
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]:        Please follow installation instructions at
[TexText][CRITICAL]:               https://textext.github.io/textext/install/macos.html#macos-install-gui-library
[TexText][CRITICAL]:       /--or-* [Fail] GTK3 is not found
[TexText][CRITICAL]:       |      Please follow installation instructions at
[TexText][CRITICAL]:       |             https://textext.github.io/textext/install/macos.html#macos-install-pygtk2
[TexText][CRITICAL]:       /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]:              Please follow installation instructions at
[TexText][CRITICAL]:                     https://textext.github.io/textext/install/macos.html#macos-install-tkinter
[TexText][ERROR   ]: Automatic requirements check found issue
[TexText][ERROR   ]: Follow instruction above and run install script again
[TexText][ERROR   ]: To bypass requirement check pass `--skip-requirements-check` to setup.py

**Comment by emanueledalsasso** [comment]
thanks for the help, I hope in my turn that reporting this bug will help you!!

**Comment by jcwinkler** [comment]
Thank you, this is very helpful. Please stay tuned. I will contact you when I have written the doc.

**Comment by pai4451** [comment]
I also encounter the same bug as well. For Inkscape 1.0 (4035a4f, 2020-05-01) and TexText 1.0.0 on MacOS 10.14.6. It can still generate the equation correctly despite the following warning message came out.

(__main__.py:16113): Gtk-WARNING **: 16:49:13.975: Locale not supported by C library.
	Using the fallback 'C' locale.

(__main__.py:16113): Gtk-WARNING **: 16:49:14.937: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 1): image not found

(__main__.py:16113): Gtk-WARNING **: 16:49:14.937: Loading IM context type 'quartz' failed

**Comment by opticaller** [comment]
Worked very nicely for me as well. :)
Currently I'm using TeX Live 2019 via MacTex.
`python setup.py --pdflatex-executable=$(which pdflatex)`

**Comment by mattfack** [comment]
Yay! It worked for me as well, just I had to combine your commands. 
The following worked for me:
`python3 setup.py --pdflatex-executable=$(which pdflatex) --skip-requirements-check`

(`python3` is just because I am using python 3.7 with python3 command)

**Comment by yoramzarai** [comment]
Having a similar issue on MAC with ```python setup.py``` where it fails to find GTK3. Waiting for the install instructions on MAC.

**Comment by mattfack** [comment]
@yoramzarai have you tried the command I posted?

**Comment by yoramzarai** [comment]
Well, first I tried without the ```--skip-requirements-check``` and I got ```GTK3 is not found``` (pdflatex was found in ```/opt/local/bin/```). Then I used ```--skip-requirements-check```, ran Inkscape: Extensions->Text->Tex Text, then entered ```$1$``` in the TexText 1.0.1 window, and upon clicking save I get:
```
Command /opt/local/bin/pdflatex tmp.tex -interaction=nonstopmode -halt-on-error failed (code -6)
```

and in Stderr:
```
dyld: Library not loaded: /opt/local/lib/libpng16.16.dylib
  Referenced from: /opt/local/bin/pdflatex
  Reason: Incompatible library version: pdflatex requires version 54.0.0 or later, but libpng16.16.dylib provides version 51.0.0
```

**Comment by mattfack** [comment]
Ok, and I assume nothing was printed. 
Because the point is that when "it works" you get an error, but textext does its job.

You should consider installing gtk3 with homebrew: https://formulae.brew.sh/formula/gtk+3

**Comment by yoramzarai** [comment]
Thank you. Indeed, nothing is printed out.

I am using macports (not homebrew) and I did install gtk3 with macports (```gtk3 @3.24.12_0+x11```), however, I think I also have a problem with pdflatex for some reason.

**Comment by mattfack** [comment]
Ok, sorry I was unable to help you.

**Comment by yoramzarai** [comment]
I was able to fix the pdflatex issue by pointing to ```/Library/TeX/texbin``` instead of ```/opt/local/bin```.  Now I am getting the following warnings after clicking ```save``` in the textext window:
```
(__main__.py:2379): Gtk-WARNING **: 15:16:57.870: Locale not supported by C library.
	Using the fallback 'C' locale.

(__main__.py:2379): Gtk-WARNING **: 15:16:58.463: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 1): image not found

(__main__.py:2379): Gtk-WARNING **: 15:16:58.463: Loading IM context type 'quartz' failed
``` 
However, I do get the output correctly from textext.
