### ISSUE TITLE
TexText 1.0 with Inkscape 1.0 AppImage: No module named 'encodings'

### ISSUE THREAD

**Issue by Masacroso** [textext/textext#220]
**Description of the problem/ steps to reproduce**
I had installed textext for python3 (I cannot do it for python 2.7.x) and it doesn't work.

**Steps to reproduce the behavior (if not obvious from description)**:

I followed the instructions to install textext, however trying to run the setup.py it says that I have not installed the GTK3 neither the Tkinter libraries, then I tried to install the GTK3 for the current version of python (2.7.x) but it says that it is impossible because these libraries are already installed for python3

Then I ran the setup.py using instead python3, that is, I wrote `python3 setup.py --inkscape-executable /home/user/Documentos/inkscape/Ink*.AppImage` and the installation go well, however trying to use textext in inkscape it thrown the following error

````
Python path configuration:
  PYTHONHOME = '/tmp/.mount_InkscaVYpNXZ/usr/'
  PYTHONPATH = '/home/user/.config/inkscape/extensions:/tmp/.mount_InkscaVYpNXZ/usr/lib/share/../../share/inkscape/extensions:/tmp/.mount_InkscaVYpNXZ/usr/lib/share/../../share/inkscape/extensions/inkex/deprecated-simple'
  program name = '/usr/local/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/local/bin/python3'
  sys.base_prefix = '/tmp/.mount_InkscaVYpNXZ/usr'
  sys.base_exec_prefix = '/tmp/.mount_InkscaVYpNXZ/usr'
  sys.executable = '/usr/local/bin/python3'
  sys.prefix = '/tmp/.mount_InkscaVYpNXZ/usr'
  sys.exec_prefix = '/tmp/.mount_InkscaVYpNXZ/usr'
  sys.path = [
    '/home/user/.config/inkscape/extensions',
    '/tmp/.mount_InkscaVYpNXZ/usr/lib/share/../../share/inkscape/extensions',
    '/tmp/.mount_InkscaVYpNXZ/usr/lib/share/../../share/inkscape/extensions/inkex/deprecated-simple',
    '/tmp/.mount_InkscaVYpNXZ/usr/lib/python38.zip',
    '/tmp/.mount_InkscaVYpNXZ/usr/lib/python3.8',
    '/tmp/.mount_InkscaVYpNXZ/usr/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fc9ac7bb280 (most recent call first):
<no Python frame>
````

**System information**

- TexText version: the last at today 6 of may 2020
- Inkscape version: 1.0 (no beta)
- Operating system: kubuntu 19.10
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): installed the GTK3 library for python3

**Comment by jcwinkler** [comment]
> Then I ran the setup.py using instead python3, that is, I wrote `python3 setup.py --inkscape-executable /home/user/Documentos/inkscape/Ink*.AppImage` and the installation go well, however trying to use textext in inkscape it thrown the following error

I discovered the same problem and confirm this error. It is not a problem of TexText. It is a missing Python package in the Inkscape AppImage. It has to be solved on Inkscape's side and I will file a report there. 

Additionally I will change the doc such it discourages the use of app image.

**Comment by jcwinkler** [comment]
See https://gitlab.com/inkscape/inkscape/-/issues/1306

**Comment by probonopd** [comment]
Is a test AppImage available for download somewhere?

**Comment by jcwinkler** [comment]
To my knowledge currently not.

**Comment by sizmailov** [comment]
If you need inkscape appimage you can download CI builds from gitlab (available for various branches): 

https://gitlab.com/inkscape/inkscape

![image](https://user-images.githubusercontent.com/2975991/82252930-a73a2980-9958-11ea-82b1-353383e33879.png)

**Comment by jcwinkler** [comment]
@sizmailov These have been buit with ubuntu 20.04 and will not work. Its a big problem in inkscape packaging process. See https://gitlab.com/inkscape/inkscape/-/issues/1458

**Comment by sizmailov** [comment]
Right, it doesn't work for 19.04 I'm currently on.
