### ISSUE TITLE
Problem with setup on Windows

### ISSUE THREAD

**Issue by Zawarud** [textext/textext#221]
I try to install textext in inkscape but give this problem.
**Logfile**
```
C:\Users\DIO\Downloads\textext-1.0.0>setup_win.bat --inkscape-executable "C:\Program Files\Inkscape\bin\"
"C:\Program Files\Inkscape\bin\" found
Trying to detect Python interpreter in Inkscape installation directory...
"C:\Program Files\Inkscape\bin\\python.exe" found

Trying to run "C:\Program Files\Inkscape\bin\\python.exe" C:\Users\DIO\Downloads\textext-1.0.0\setup.py --inkscape-executable "C:\Program Files\Inkscape\bin\"...

[TexText][ERROR   ]: Bad `inkscape` executable provided: `C:\Program Files\Inkscape\bin"`. Abort installation.
```

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 1.0.0
- Inkscape version: 1.0
- Operating system: Winows 10 64bit
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): idk
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter):  PyGTK-Sourceview 3.24.11
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):   MiKTeX-pdfTeX 2.9.7338
- Windows only: TexText installed via batch script or installer file:   setup_win.bat

**Comment by jcwinkler** [comment]
If you installed Inkscape using one of the installers it is enough to simply double click on `setup_win.bat`.

If you have installed inkscape from a zip package then the correct call of `setup_win.bat` from the command line is
```bash
setup_win.bat --inkscape-executable "C:\Program Files\Inkscape\bin\inkscape.exe"
```

Note, you have to pass the path+executable, not the path only, as you did.
