### ISSUE TITLE
Fedora Linux 31: Python 2.7 required for Textext

### ISSUE THREAD

**Issue by huubvanniekerk** [textext/textext#222]
**Description of the problem/ steps to reproduce**
Textext 0.11.0 doesn't work with Inkscape1.0rc1

**Steps to reproduce the behavior (if not obvious from description)**:
1. After installing Textext in Inkscape 1.0rc1 (09960d6f05, 2020-04-09) on Fedora 31, it appears in the menu and can be selected. However, directly after selecting
[textext.log](https://github.com/textext/textext/files/4607995/textext.log)
 it, the error as described appears. After that, you can only click the message box away.
2. ....
3. ....

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```
<<< Error: Python 2.7 is required, but found 3.7.7 >>> 
```
</details>

<details>
<summary>output of stdout (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 0.11.0
- Inkscape version: 1.0rc1
- Operating system: Fedora Linux 31
- SVG-converter installed (pstoedit+ghostscript or pdf2svg): pstoedit-3.73-5.fc31.x86_64, ghostscript-9.27-4.fc31.x86_64,pdf2svg-0.2.3-9.fc31.x86_64
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): none
![Screenshot-Inkscape-textext-2020-05-11_09-04-34](https://user-images.githubusercontent.com/13077765/81533444-8117f680-9366-11ea-86da-5550ad873751.png)

- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Comment by sizmailov** [comment]
Use TexText 0.x is incompatible with inkscape 1.x. Use TexText 1.0 release.

**Comment by huubvanniekerk** [comment]
Thank you. It's working now.
