### ISSUE TITLE
TexTextConversionError: 6

### ISSUE THREAD

**Issue by mallowcodes** [textext/textext#226]
Hi, I keep getting the following error complaining of an undefined control sequence \text. I have checked that on my local installation of tex that I don't get such an error - can load and compile fine, and packages seem to be there.

`[TexText][DEBUG   ]: Enforcing DEBUG mode due to previous exit code `60`
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '0.10.0' (md5sum = a545ab70c1eaff22ec4829307e1f02c8)
[TexText][DEBUG   ]: platform.system() = 'Windows'
[TexText][DEBUG   ]: platform.release() = '10'
[TexText][DEBUG   ]: platform.version() = '10.0.18362'
[TexText][DEBUG   ]: platform.machine() = 'AMD64'
[TexText][DEBUG   ]: platform.uname() = ('Windows', 'DESKTOP-AK1LS25', '10', '10.0.18362', 'AMD64', 'Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')
.
.
.
[TexText][DEBUG   ]: TexText.effect
[TexText][DEBUG   ]:   Pdf2SvgPlotSvg is usable
[TexText][DEBUG   ]:   Old node text = '$\\Psi(\\tau_{\\mathrm{BLR}})$\n\n\n\n\n'
[TexText][DEBUG   ]:   Old node scale = 2.0
[TexText][DEBUG   ]:   Adjust scale factor to account transformations in inkscape
[TexText][DEBUG   ]:   Old node alignment `middle center`
[TexText][DEBUG   ]:   Using node preamble file
[TexText][DEBUG   ]:   Preamble file found by absolute path
[TexText][DEBUG   ]:   Run TexText GUI
[TexText][DEBUG   ]:     TexText.do_convert
[TexText][DEBUG   ]:       args:
[TexText][DEBUG   ]:         converter = <__main__.Pdf2SvgPlotSvg object at 0x00000000030b0450>
[TexText][DEBUG   ]:         original_scale = 2.0
[TexText][DEBUG   ]:         text = u'$\\Psi(\\tau_{\\text{BLR}})$\n\n\n\n\n\n'
[TexText][DEBUG   ]:         tex_command = 'pdflatex'
[TexText][DEBUG   ]:         preamble_file = 'default_packages.tex'
[TexText][DEBUG   ]:         user_scale_factor = 2.0
[TexText][DEBUG   ]:         old_svg_ele = <__main__.Pdf2SvgSvgElement object at 0x00000000030b01d0>
[TexText][DEBUG   ]:         tex_executable = 'C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\pdflatex.exe'
[TexText][DEBUG   ]:         self = <__main__.TexText instance at 0x0000000002c4ea70>
[TexText][DEBUG   ]:         alignment = 'middle center'
[TexText][DEBUG   ]:       args: done
[TexText][DEBUG   ]:       Converting tex to svg
[TexText][DEBUG   ]:         Converting .tex to svg element
[TexText][DEBUG   ]:           Converting .tex to .pdf
[TexText][DEBUG   ]:             Parsing LaTeX log file
[TexText][DEBUG   ]:             Parsing LaTeX log file done
[TexText][DEBUG   ]:           Converting .tex to .pdf failed
[TexText][DEBUG   ]:         Converting .tex to svg element failed
[TexText][DEBUG   ]:       Converting tex to svg failed
[TexText][DEBUG   ]:     TexText.do_convert failed
[TexText][DEBUG   ]:   Run TexText GUI failed
[TexText][DEBUG   ]: TexText.effect failed
[TexText][ERROR   ]: 6: Error: Undefined control sequence \text.
Problem exists here:         $\Psi(\tau_{\text

[TexText][ERROR   ]: Traceback (most recent call last):
  File "__init__.py", line 1156, in <module>
    effect.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "__init__.py", line 341, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "asktext.py", line 437, in ask
    tex_command_tk_str.get())
  File "__init__.py", line 331, in save_callback
    original_scale=current_scale)
  File "__init__.py", line 442, in do_convert
    new_svg_ele = converter.convert(text, preamble_file, scale_factor, tex_executable)
  File "__init__.py", line 661, in convert
    self.tex_to_pdf(tex_command, latex_text, preamble_file)
  File "__init__.py", line 620, in tex_to_pdf
    raise TexTextConversionError(parsed_log, error.return_code, error.stdout, error.stderr)
TexTextConversionError: 6: Error: Undefined control sequence \text.
Problem exists here:         $\Psi(\tau_{\text

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new
`

**Comment by jcwinkler** [comment]
I guess you are using Inkscape 0.92.x, right?

Two things:
- Please update TexText to version 0.11.1, you are using outdated version 0.10. By this we can be sure that any error processing in TexText is fixed.
- I think there is an error in your preamble file. Please double check the content of `c:\Users\[Your Username]\AppData\Roaming\inkscape\extensions\textext\default_packages.tex`

**Comment by mallowcodes** [comment]
Just did a fresh installl/update of inkscpe and textext and seems ok. Thanks.
