### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cedricesc** [textext/textext#232]
Hi,

I have encountered an issue that I solved and I think it should be mentionned in the installation procedure for the Windows installation. When we run the file setup_win.batch, the folder in which the file is must be in another area than Program Files. In fact, it seems the space between the Program and Files is not handled. To tackle this issue, I have placed the folder in my desktop to avoid this path. The error encountered is something like that "Program [Errorn2]".
Thank you in advance for sharing,

Cédric

**Comment by jcwinkler** [comment]
You mean when you unpack the installation package in ```C:\Program Files``` and then run ```setup_win.bat```  from this directory?

**Comment by jcwinkler** [comment]
I confirm this error: If the path from which ```setup_win.bat``` is invoked contains spaces batch execution fails.

**Comment by cedricesc** [comment]
> You mean when you unpack the installation package in `C:\Program Files` and then run `setup_win.bat` from this directory?

Sorry for the delay. Yes exactly. We need to move the bat file outside from the Program Files ; otherwise it is not working.
