### ISSUE TITLE
crash of invoked inkscape process after upgrading to Ubuntu 20.04 from 18.04 

### ISSUE THREAD

**Issue by derMart** [textext/textext#234]
**Description of the problem/ steps to reproduce**
Crash of the from textext invoked inscape process while saving / previewing text entered in the textext dialog

**Steps to reproduce the behavior (if not obvious from description)**:
1. Open Textext (via menu Text -> Tex Text)
2. Type anything
3. Click preview or save
4. Invoked inkscape instance crashes

**Message(s) in error dialog (if this comes up)**

Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```
Command /usr/bin/inkscape --pdf-poppler --pdf-page=1 --export-type=png --export-area-drawing --export-dpi=300 --export-filename tmp.png tmp.pdf failed (code -11)
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
** (org.inkscape.Inkscape:11761): WARNING **: 17:11:02.832: Fonts dir '/home/martin/.config/inkscape/fonts' does not exist and will be ignored.

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at https://inkscape.org/report
with a detailed description of the steps leading to the crash, so we can fix it.
** Message: 17:11:02.835: Error: Inkscape encountered an internal error and will close now.

```
</details>

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on 
~/.config/inkscape/extensions/textext/textext.log was not modified since month (!) as such skipping since unrelated...

**System information**

- TexText version: 1.0.1
- Inkscape version: 1.0 (1.0+r73+1)
- Operating system: Ubuntu 20.04 (upgraded from 18.04)

- SVG-converter installed (pstoedit+ghostscript or pdf2svg): pdf2svg
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter): sorry no idea, don't know how to find out

**Comment by derMart** [comment]
reinstallation of textext using setup.py does not solve the problem :-(

**Comment by sizmailov** [comment]
1. Apparently it's inkscape bug, not textext. 
2. Bug report is not actionable, please add more info, so other can reproduce it.

**Comment by derMart** [comment]
Please tell me what exactly I should add to the report?

**Comment by sizmailov** [comment]
The only thing that evident from you bug report is inkscape fail of convert pdf to png. Textext has nothing to do here.

IMO should be reported to inkscape [bug tracker](https://gitlab.com/inkscape/inbox/). Please attach troubling  `.pdf` (first figure out  whether it's opens fine with okular/evince/inkscape in gui mode, etc.) 

Also check out [troubleshooting doc page](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain) if you not sure how to obtain intermediate pdf

**Comment by derMart** [comment]
Well again, from the error of Textext, to me it is not obvious where the problem lies.
I followed the manual process described in the troubleshooting doc (between these instruction do not explain how / where to obtain the intermediate pdf generated by textext, only the ones generated yourself using the commands listed there, which is a difference)
Indeed it seems that inkscape has some trouble, given the commands in the doc are valid still.
I just added 'test' to the .tex document. The generated pdf seems fine ([test.pdf](https://github.com/textext/textext/files/4897967/test.pdf))
On this pdf
```
inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf
```
fails with the same error as above.
I will open an issue in inkscape tracker

**Comment by jcwinkler** [comment]
> (between these instruction do not explain how / where to obtain the intermediate pdf generated by textext, only the ones generated yourself using the commands listed there, which is a difference)

What exactly do you mean? The manual toolchain just performs the steps TexText does automatically, as stated in the [doc](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain) If there is any misunderstanding the doc we could improve it but currently I do not see where the problem is...

**Comment by derMart** [comment]
> What exactly do you mean? The manual toolchain just performs the steps TexText does automatically, as stated in the doc If there is any misunderstanding the doc we could improve it but currently I do not see where the problem is...

No, that is not what I meant. In the issue you have written I should follow the docs to obtain the intermediate pdf generated by Textext. The docs however document how to *manually* do the steps TexText is supposed to do automatically. But in the case of an error in TexText, what TexText  does automatically might not be the same as the manual steps documented. I would have expected a location of the intermediate files automatically generated from TexText instead from your description in the issue

**Comment by derMart** [comment]
Inkscape issue: https://gitlab.com/inkscape/inbox/-/issues/3247

**Comment by jcwinkler** [comment]
OK, thanks @derMart, I do understand the source of confusion. Unfortunately, TexText stores its intermediate results in a temp folder which is deleted after operation. Anyway, you found the source of the error.

I will update the documentation so users of Inkscape on ubuntu 20.04 are guided to install the correct Inkscape 1.0 via apt-get.
