### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jeremyyi** [textext/textext#235]
Hi there,
I found this error below when I tried to open the textext extension. I have no idea how to find the solution? Can you please give some help?
> [TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.0 is found
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]:        Please follow installation instructions at 
[TexText][CRITICAL]:               [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-gui-library[0m
[TexText][CRITICAL]:       /--or-* [Fail] GTK3 is not found
[TexText][CRITICAL]:       |      Please follow installation instructions at 
[TexText][CRITICAL]:       |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-gtk3[0m
[TexText][CRITICAL]:       /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]:              Please follow installation instructions at 
[TexText][CRITICAL]:                     [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-tkinter[0m
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

It seems that it failed at detecting latex distribution. However, I'm pretty sure I have installed them on my laptop. Here is the requirement check log when installing the textext.

> [TexText][[49m[32mSUCCESS [0m]: [49m[32m+ [Succ][0m TexText requirements
[TexText][[49m[32mSUCCESS [0m]: [49m[32m/-and-[49m[32m* [Succ][0m Detect inkscape>=1.0
[TexText][[49m[32mSUCCESS [0m]: [49m[32m|[0m      inkscape=1.0 is found
[TexText][[49m[32mSUCCESS [0m]: [49m[32m/-and-[49m[32m+ [Succ][0m Detect *latex
[TexText][[49m[32mSUCCESS [0m]: [49m[32m|[0m     [49m[32m/--or-[49m[32m* [Succ][0m `pdflatex` is found at `/usr/bin`
[TexText][[49m[32mSUCCESS [0m]: [49m[32m|[0m     [49m[32m/--or-[49m[32m* [Succ][0m `lualatex` is found at `/usr/bin`
[TexText][[49m[32mSUCCESS [0m]: [49m[32m|[0m     [49m[32m/--or-[49m[32m* [Succ][0m `xelatex` is found at `/usr/bin`
[TexText][[49m[32mSUCCESS [0m]: [49m[32m/-and-[49m[32m+ [Succ][0m Detect GUI library
[TexText][[49m[32mSUCCESS [0m]:       [49m[32m/--or-[49m[32m* [Succ][0m GTK3 is found
[TexText][[49m[32mSUCCESS [0m]:       [49m[32m/--or-[49m[32m* [Succ][0m TkInter is found

Thank you so much for your help!

Cheers,
Jeremy

**Comment by jeremyyi** [comment]
BTW, I'm a Linux user :)

**Comment by jcwinkler** [comment]
Did you install Inkscape via snap?

**Comment by jeremyyi** [comment]
> Did you install Inkscape via snap?

I think I got my previous inkscape from Ubuntu software center since I could only find inkscape 0.92 from apt-get at that time.
And here is what i found from inkscape.org. This allows me to install the newest version, so problem sovled and now textext works perfectly fine!

> sudo add-apt-repository ppa:inkscape.dev/stable
sudo apt update
sudo apt install inkscape
