### ISSUE TITLE
Warning message with texText 1.1.0 on MacOS

### ISSUE THREAD

**Issue by PasLafon** [textext/textext#238]
**Description of the problem/ steps to reproduce**
A clear and concise description of what the bug is and what you expected to happen.
After executing tex text extension with InkScape 1.0 (4035a4f, 2020-05-01) on Mac OS 10.13.6 I obtain the following warning message :
**Steps to reproduce the behavior (if not obvious from description)**:
1. ....Install tex text extension following recommendation
2. ....Use extension to write LaTeX text : eg : $\vec{AB}$

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```


(__main__.py:23574): Gtk-WARNING **: 13:46:00.659: Locale not supported by C library.
	Using the fallback 'C' locale.

(__main__.py:23574): Gtk-WARNING **: 13:46:01.462: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 1): image not found

(__main__.py:23574): Gtk-WARNING **: 13:46:01.462: Loading IM context type 'quartz' failed

```
</details>

<details>
<summary>output of stdout (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 1.1.0
- Inkscape version:  1.0 (4035a4f, 2020-05-01)
- Operating system: [e.g. Windows 10, 1803, 32-bit] : Mac OS 10.13.6
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Additional information if you still use Inkscape 0.92.x / TexText 0.11**

- SVG-converter installed (pstoedit+ghostscript or pdf2svg):
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter):

**Comment by jcwinkler** [comment]
Thanks! This has already been reported in #218 . It should be investigated by an experienced MacOS user knowing how GTK is working/ installed on the system. Anyway, you get correct svg nodes from TexText placed into your document, am I right?

**Comment by mgnisia** [comment]
@jcwinkler I face the same issue and I can confirm that the svg nodes are placed correctly and I am able to edit the nodes afterwards. Nevertheless, the GTK Warning requires are restart of TexText, if the GTK Warning is not closed properly.
