### ISSUE TITLE
In TexText v1.1 tmp.tex file is non-utf8 encoded. Is it a bug or a feature?

### ISSUE THREAD

**Issue by kvic1950** [textext/textext#241]
**Description of the problem/ steps to reproduce**
In Windows (Russian locale) + TexText v1.X tmp.tex file created during formula compilation is non-utf8 encoded. With TexText versions <= 0.11.1 this file was utf8-encoded.

**Steps to reproduce the behaviour (if not obvious from description)**:
In Windows 10 and Windows 7 (Russian locale), in TexText v0.11.1 and earlier, to use Russian letters in formulas I used the following default_packages.tex preamble file:

    \usepackage[T2A]{fontenc}
    \usepackage[utf8]{inputenc}
    \usepackage{amsmath,amsthm,amsbsy,amsfonts,amssymb}
    \usepackage{mathrsfs}
     
    \usepackage{color}

and all the compilations were without problems.

Now, in both versions 1.0 and 1.1 of TexText, the same compilation results in hanging TexTex+Inkscape (no log file produced at this step). Only after pressing cross in the upper-right corner of TexText window I got a list of errors and the log file created.

After looking at the created during the formula compilation file tmp.tex I found that now it is composed not in utf8 encoding but in ANSI encoding which apparently conflicting with the string \usepackage[utf8]{inputenc} in the preamble of tmp.tex file.

**My way of correction:** After replacing the line 524 in base.py

            with open(self.tmp('tex'), 'w') as f_tex:
			
with the following one

            with open(self.tmp('tex'), mode='w', encoding='utf-8') as f_tex:

the created during the formula compilation file tmp.tex becoming utf8-encoded, and the compilation of formulas with Russian letters goes OK!

**Logfile**
[textext.log](https://github.com/textext/textext/files/5049449/textext.log)

**System information**

- TexText version: 1.1.0
- Inkscape version: 1.1 
- Operating system: Windows 10, 64bit, Russian locale: system code page cp1251; 
Windows 7, 64bit, Russian locale: system code page cp1251
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): TeX-Live-2020
- Windows only: TexText installed via batch script or installer file: installer

**Additional information if you still use Inkscape 0.92.x / TexText 0.11**

- SVG-converter installed (pstoedit+ghostscript or pdf2svg):
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter):

**Comment by jcwinkler** [comment]
Thanks for the report. I can reproduce the problem on Windows 8 with German Umlauts ä ö ü ß and German locale system (cp1252).

Your fix works as well. However, we have to keep in mind that we have to ensure compatibility to Python 2 users on Linux (native Python 2 open command does not offer the mode and encoding arg so we use `io.open` here). This has to be addressed properly. I will check this and come back shortly.

**Comment by kvic1950** [comment]
OK! I am happy that attracted your attention to this issue. I am absolutely ignorant in Python, so my 'fix' is quite naive. But now I am sure that you will find a 'real fix'
