### ISSUE TITLE
Textext, fails to generate output (error occured while conterting text from latex to svg)

### ISSUE THREAD

**Issue by mikhailiuk** [textext/textext#244]
I am working with inkscape 1.0 (1.0+r73+1)

After launching textext a normal window appears, prompting to input text. After pressing preview or save the following message appears:

Command inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename tmp.svg tmp.pdf failed (code 1)

stderr:

Unknown option --export-filename

I was wondering

**Comment by sizmailov** [comment]
Hi!  You need to install latest inkscape. The set of command line options was changed one more time (right) before the final 1.0 release.

**Comment by jcwinkler** [comment]
@mikhailiuk, @sizmailov  ``--export-filename`` **is supported** by Version 1.0+r73+1. There must be something else wrong. Are you sure the command ``inkscape`` calls the correct executable?

@mikhailiuk What are the outputs of ``inkscape --help | grep export-filename`` and ``inkscape --version`` ?
