### ISSUE TITLE
 Disable alignment controls when creating a new node (Tk and GTK)

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#25]
Relates to the release of 0.8: Alignment controls do not make sense when a new node is created. Hence, disable them in such cases.

**Comment by leberwurstsaft** [comment]
I agree on hiding them, but I also want to voice my concern regarding "muscle memory". The arrangement of the remaining buttons should not change. There must be empty space where the button was, instead of simply putting the remaining buttons closer together or making them wider.

**Comment by jcwinkler** [comment]
In release 0.8 they are disabled. Seemed to be complicated to hide them while keeping the space. But if someone has a solution which does not blow up the code feel free to add it.
