### ISSUE TITLE
Error: could not get a reference to type class on first launch of TexText

### ISSUE THREAD

**Issue by unamunoe** [textext/textext#251]
**Description of the problem/ steps to reproduce**
I have installed Inkscape 1.0 following [these steps](https://textext.github.io/textext/install/windows.html), and I am not able to open the TexText console because of an error.

**Steps to reproduce the behavior**:
1. Installed Inkscape 1.0 and removed the previous version (in which I had TexText already installed).
2. Checked that my LaTeX distribution is ok
3. Installed GtkSourceview 3 for Inkscape 1.0 64-bit by copying the files manually
4. Installed TexText with the setup script
5. Restarted PC and launched Inkscape, then TexText without success

**Message in error dialog**
<details>
<summary>dialog output :</summary>

```
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.0 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex.exe` is found at `C:\Users\eunamuno\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex.exe` is found at `C:\Users\eunamuno\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex.exe` is found at `C:\Users\eunamuno\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][DEBUG   ]: TexText.effect
[TexText][DEBUG   ]:   Using default preamble file `default_packages.tex`
[TexText][DEBUG   ]:   Run TexText GUI
[TexText][DEBUG   ]:   Run TexText GUI failed
[TexText][DEBUG   ]: TexText.effect failed
[TexText][ERROR   ]: could not get a reference to type class
[TexText][ERROR   ]: Traceback (most recent call last):
  File "__main__.py", line 8, in <module>
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "C:\Users\eunamuno\AppData\Roaming\inkscape\extensions\textext\base.py", line 282, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "C:\Users\eunamuno\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1204, in ask
    window = self.create_window()
  File "C:\Users\eunamuno\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1045, in create_window
    text_buffer = GtkSource.Buffer()
TypeError: could not get a reference to type class
```
</details>

**Logfile**
[textext.log](https://github.com/textext/textext/files/5163177/textext.log)

**System information**

- TexText version: 
- Inkscape version: 1.0
- Operating system: Windows 10, 1903, 64-bit
- LaTeX-distribution: MiKTeX
- TexText installed via batch script

**Comment by jcwinkler** [comment]
@unamunoe Sorry for the late reply.

A a fist step please try the following:
1. Please uninstall Inkscape and GTKSourceView completely. 
2. Check if the installation directory (usually `C:\Program Files\Inkscape`) does not exist anymore. If it exists, please remove it manually.
3. Install Inkscape only

Are you able to access TexText?

**Comment by unamunoe** [comment]
@jcwinkler I followed your steps and now it is opening correctly.

Many thanks!
