### ISSUE TITLE
Inkscape 1.0.1 (Windows): No GTK interface

### ISSUE THREAD

**Issue by orengt** [textext/textext#253]
On: 1.0.1 (3bc2e813f5, 2020-09-07)
Win
With TexText: 1.1.0

The texText dialog does not display the preview button.
![image](https://user-images.githubusercontent.com/31801615/93708026-c67dd900-fb3b-11ea-8ddb-fd82f1ad892d.png)

**Comment by sizmailov** [comment]
Tk interface never had one. Try GTK.

**Comment by orengt** [comment]
Thanks for the quick reply. 
From the manual I thought there should be one (there was one in the in 0.92) my bad I guess.
Anyway I don't really know what you mean by using GTK, so I guess I'll do with it as it is hopping the preview button will be added in the future.
Oren

**Comment by sizmailov** [comment]
In fact TK interface is about to be deprecated completely. GTK would be the only supported interface in the next major release. 

See installation instructions in doc: 
https://textext.github.io/textext/install/linux.html#install-python-gtk3-bindings-recommended

**Comment by orengt** [comment]
OK. 
pls note i'm on WIN not Linux.
However seems GTK was installed but I reinstalled it to be on the safe side.
Then I reinstalled TexText but it still show me the TK interface, how should I switch to GTK?
Thanks!

**Comment by sizmailov** [comment]
Must be issue with inkscape installation. GTK should be available out of box in 1.0+ release series. You might have a better luck with newer inkscape version.

**Comment by orengt** [comment]
OK.
Thanks a lot for all.
Just for the information I tried reinstalling everything after clearing the registry and deleting all my AppData.
Still TexText shows with th TK interface, so I guess I'll need to wait for the next Inkscape version. (i'm on 1.0.1).
Oren

**Comment by jcwinkler** [comment]
I confirm this error. GTK3 support in Inkscape 1.0.1 on Windows is broken.

Reason is that here

https://github.com/textext/textext/blob/90868fbb1ec364cca1e7cf287792686d050824d7/textext/asktext.py#L48-L51

the import of the `HarfBuzz` library fails:

``` bash
gi.RepositoryError: Typelib file for namespace 'HarfBuzz', version '0.0' not found
```
(It is a problem of the underlying msys2 system on Windows)

I will open an issue on Inkscape.

@orengt Use Inkscape 1.0.0 from here instead: https://inkscape.org/release/1.0/platforms/

**Comment by orengt** [comment]
Thnaks Jan, if it's important that I confirm it works on 1.0.0 I'll go back to it, otherwise I'll wait the next version and use online LaTex testing tools instead.
Oren

**Comment by jcwinkler** [comment]
I opened a merge request in Inkscape fixing this issue in a future version:

https://gitlab.com/inkscape/inkscape/-/merge_requests/2338
