### ISSUE TITLE
TexText 1.1.0 fails to run with Inkscape 1.0.1 on MAC 10.15.6 

### ISSUE THREAD

**Issue by yoramzarai** [textext/textext#254]
**Description of the problem/ steps to reproduce**
Tex Text fails to run with Inkscape 1.0.1.

I have both Inkscape 1.0 and Inkscape 1.0.1 installed on my MAC. I have Tex Text 1.1.0 installed. Tex Text works fine when using the steps below with Inkscape 1.0, but fails when using the steps below with Inkscape 1.0.1. 

**Steps to reproduce the behavior (if not obvious from description)**:
1. Run Inkscape 1.0.1
2. Chose ```Extensions - > Text -> Tex Text``` 
3. A dialog box appears with the content listed below. Upon clicking ```OK```, it gets back to the Inkscape window (but no TexText window appears).

When running steps 1 and 2 above in Inkscape 1.0, Tex Text works well.

**Message(s) in error dialog (if this comes up)**
```
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
    from textext.base import *
  File "/Users/yoramzarai/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/base.py", line 105, in <module>
    import inkex
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 33, in <module>
    from .elements import load_svg, BaseElement, ShapeElement, Group, Layer, Grid, \
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 8, in <module>
    from ._base import SVG_PARSER, load_svg, ShapeElement, BaseElement
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module>
    from lxml import etree
ImportError: dlopen(/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so: code signature in (/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Logfile**
No log file was created.

**System information**

- Tex Text version 1.1.0
- Inkscape 1.0.1
-  Operating system: MAC OS 10.15.6

**Comment by sizmailov** [comment]
You see a problem with importing `lxml` library which should be available in proper inkscape installation. Either you messed with python interpreter or inkscape installation went wrong. It's not textext bug. You can check that other extensions do not work either and raise simlilar error.

**Comment by yoramzarai** [comment]
Thank you for the reply. I re-installed Inkscape 1.0.1 and had the same issue. Isn't the fact that Tex Text works fine with my Inkscape 1.0 implies that Python is intact?

**Comment by sizmailov** [comment]
Could be that 1.0.1 release is just broken on Mac. Try to ask on [inkscape user support channel](https://chat.inkscape.org/channel/inkscape_user) to confirm. Their issue tracker (gitlab) is not really searchable, so can't tell if the issue already exist. Most likely inkscape devs are already aware of this problem.

**Comment by yoramzarai** [comment]
Ok, Thanks
