### ISSUE TITLE
Request for enhancement: TexText Group ID change on edit

### ISSUE THREAD

**Issue by orengt** [textext/textext#256]
Is it possible to prevent the change of TexText objects group ID (and label) after being edited?
I often give these groups significant name as I'm using it for creating presentation.
It's very annoying thus that after editing formulas the ID is replaced and is set back to g#####.
Thanks!

On Inkscape 1.0.1 & Win 10.

**Comment by jcwinkler** [comment]
@orengt In TexText 1.2.0 being just released your issue is fixed!
