### ISSUE TITLE
/usr/bin/python3: can't open file 'latextext.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by eltonfernando** [textext/textext#258]
I followed the instructions [install](https://textext.github.io/textext/install/linux.html)

exit when running on inskpace

/usr/bin/python3: can't open file 'latextext.py': [Errno 2] No such file or directory

[textextsetup.log](https://github.com/textext/textext/files/5330696/textextsetup.log)

**Comment by jcwinkler** [comment]
The file `latextext.py` is not part of TexText. Did you try to open TexText via `Text`-`TexText` Menu entry ?

**Comment by eltonfernando** [comment]
the `Text-TexText` option does not show up for me

that worked
I am restarted inkscape, in opencv Extensions> render> mathematics> LaTex pdflatx

thank you

**Comment by jcwinkler** [comment]
I have to be precise: `Extensions` > `Text` > `TexText`  There is no entry?

**Comment by eltonfernando** [comment]
was looking for in text. in `Extensions > Text > TexText` have entry.

now everything is working fine

sorry for the lack of attention.

**Comment by jcwinkler** [comment]
No problem!
