### ISSUE TITLE
Opening extensions takes surprisingly long

### ISSUE THREAD

**Issue by gncs** [textext/textext#263]
I use this extension a lot and noticed that opening the extension window (through the menu item or the keyboard short cut) takes relatively long (~ 1 second) for what it's doing. It's not exactly an issue but I am still surprised. Is this supposed to be like that or is this just me?

Could you give me some intuition as to why it takes that long? What is the extension doing in the background? 

Thank you.

**Comment by sizmailov** [comment]
Hi! Thanks for report! 
On my system the requirements check takes ~0.7 second and ~0.5 second is GTK window creation. I cached requirements check  results to improve the situation, but it still feels like a bit more than one second when I open it from inkscape. Probably there is a lag associated with inkscape shortcut system & python invocation, but we can't do anything about it, sorry.
