### ISSUE TITLE
Double backslash (\\) when editing text from previous versions

### ISSUE THREAD

**Issue by orengt** [textext/textext#265]
I just installed Inkscape 1.0.1 on an new computer with TexTex 1.2.0.
When I open existing TexTex object an additional backslash is added to all commands.
For instance in the attached file I get $\\beta$ instead of $\beta$.
[em00001-0011a Two Pending Balls.zip](https://github.com/textext/textext/files/5520425/em00001-0011a.Two.Pending.Balls.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/31801615/98737681-375ca700-23af-11eb-8075-bf74c5c5f041.png)

**System information**

- TexText version: 1.2.0
- Inkscape version: 1.0.1
- Operating system: Windows 10, Version 10.0.19041 Build 19041, 64-bit]
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTeX
- Windows only: TexText installed via batch script or installer file: batch

**Comment by sizmailov** [comment]
Hi, thanks for the report! 

I recently saw similar thing on my documents: slashes were replaced by double slashes and new lines replaced by `\n` (two chars). Not sure were it comes from. At the moment of TexText object creation everything seems to be OK. My guess is that inkscape somewhere does "normalization" of attribute values. In the file you attached the value of text is already has double slashes, so it's not really helpful :(

I'm afraid we can't do much to already corrupted nodes. I'm curious where this corruption comes from :thinking: 

Note: space characters in xml attributes [are recommend to be replaced](https://www.w3.org/TR/1998/REC-xml-19980210#AVNormalize) by whitespace, so plain text attribute is not sufficient to keep arbitrary user input intact. 

@jcwinkler I think we should (optionally?) store base64-encoded text input in addition to plain `text` field to avoid this kind of problems. See #266 for details.

**Comment by sizmailov** [comment]
Ok, my bad. It's actually problem of textext :disappointed: The difference comes from #242 which removes escaping difference for different python interpreters but introduces discrepancy between textext versions.

Looks like we don't store enough meta information to 100% reliably restore corrupted strings. Probably guess-and-fix could be good enough?

**Comment by orengt** [comment]
Hi Sergei 

It's amazing how quickly you answered. 
I just don't understand if your question "Probably guess-and-fix could be good enough?" was for me, if it is to me, could you please explain it for me I don't think I get it.

Thanks,
Oren

**Comment by sizmailov** [comment]
@orengt No, It's just me thinking in loud, no extra input required, thanks.

**Comment by jcwinkler** [comment]
@sizmailov After some testing I think best is to revert commit 9889c086a3109ee7eb0a4956c904d9175f9800a9

My assumption that escaping is handled properly by the inkex methods seems to be wrong, So what did I miss? Very frustrating.

**Comment by jcwinkler** [comment]
It is not that easy. Text of nodes created with TexText < 1.2.0 can be easily read back via

```python
value = self.get(ns_key).encode('utf-8').decode('unicode_escape')
```

However, this fails with nodes created with TexText 1.2.0. For this kind of nodes we need to call
```
value = self.get(ns_key)
```
Anyway, the newlines are lost by this approach when reading back TexText 1.2.0 nodes (at least on Windows).

Unfortunately this seems not possible to be handled in a try ... except block, since applying the encode-decode procedure on 1.2.0 nodes results in a deprecation warning only:
```
<input>:1: DeprecationWarning: invalid escape sequence '\p'
'\x08egin{align*} y_1 &= \\pm \\sqrt{x_1^2 + x_2^2} \\sin(\x0barphi)\\ y_2 &= \x0crac{x_1}{x_2} \\end{align*}'
```

Some test files are in the snippets directory of the develop branch.

**Comment by sizmailov** [comment]
> Anyway, the newlines are lost by this approach when reading back TexText 1.2.0 nodes (at least on Windows).

Inkscape simply follows w3 recommendation linked above and replaces new lines with spaces on node copy or save/open, so *some* encoding needs to be applied.

I think we use universally use `unicode_escape` from 1.3? It did work quite well for TexText<1.2.0. We can avoid some `try-except` blocks by switching encoding method based on stored `textext_version` node attribute.

For nodes created with TexText<1.2.0 we should try two possible escaping methods. Probably we can first look for `\\` in node text or use `try-except`? 

> Some test files are in the snippets directory of the develop branch.

Great! At the moment #242 when was merged we have [disabled tests](https://travis-ci.com/github/textext/textext/builds/179296453) and it lead us down. It would be quite important to be able to read nodes of all previous versions. So this is definitely worth of effort.

**Comment by jcwinkler** [comment]
@orengt The issue should be fixed now in the most recent [development release](https://github.com/textext/textext/releases/tag/1.3.0-dev.1).

Please note that a one time recompilation of nodes created with TexText 1.2.0 may be required to get rid of missing line breaks (needed to be inserted manually).

Any feedback is highly appreciated.

**Comment by orengt** [comment]
@jcwinkler I tested 1.3.0_Dev on few cases in which I saw the problem and now it looks ok.
Will let you know if something goes wrong.
Thanks for the quick solution.
Oren
