### ISSUE TITLE
Can I use Textex in a PDF, export it into PDF, then reopen it back up and re-edit it?

### ISSUE THREAD

**Issue by DUOLabs333** [textext/textext#269]
I want to use Tetex for editing PDFs, but I'm going to be saving the PDFs and reopening them a lot, so I don't know if the PDFs preserve the images' information.

**Comment by sizmailov** [comment]
There is no way to edit objects imported from pdf. The most what you can do is import pdf in inkscape and ADD some TexText nodes.

**Comment by DUOLabs333** [comment]
But can't you re-edit Textex nodes, even after closing the file? How would I do that?

**Comment by sizmailov** [comment]
Exporting to pdf is one-way operation. Once you converted svg to pdf you can't restore TexText information from it. Keep the original svg and you are good.

**Comment by DUOLabs333** [comment]
Ok, if I save a pdf to an "Inkscape svg", does it retain the text in the pdf?
