### ISSUE TITLE
Possible bug in TexTex

### ISSUE THREAD

**Issue by hbbingham** [textext/textext#275]
I'm running ubuntu 20.04 and I believe that I carefully followed the installation instructions for Inkscape and TexTex here: https://textext.github.io/textext/install/linux.html . 

The installation looked to be successful with no errors after running: 
python setup.py

However, when I try to invoke it from Inkscape, I get the following error: 

![Screenshot from 2021-01-04 20-01-52](https://user-images.githubusercontent.com/14147694/103582075-74d83f00-4edd-11eb-884a-849ad3718165.png)

Here are my versions of the required packages: 

pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01

XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 66.1; using 66.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.1; using 2.10.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.6.4; using 2.6.4
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.1; using 2.13.1

This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)

Inkscape 1.0.1 (1.0.1+r74)
    Pango version: 1.44.7

Hoping you can help me get it running. 

Harry

**Comment by jcwinkler** [comment]
The error message shown in the screenshot refers to an extension called `latextext` (the simple one shipped with Inkscape), not `TexText`. 

Are you sure you invoked `TexText` via the `Extensions` - `Text` - `TexText` entry?

**Comment by hbbingham** [comment]
Sorry! I mixed up the two paths through extensions. It works fine. Thanks for your help and time.
