### ISSUE TITLE
TexText is grayed out in the Inkscape's Extension menu

### ISSUE THREAD

**Issue by horror-vacui** [textext/textext#278]
**Description of the problem/ steps to reproduce**
TexText is grayed out in the Inkscape's Extension.

**Steps to reproduce the behavior (if not obvious from description)**:
Open Inkscape and select the Extension menu

**Screenshots**
![textext_menu](https://user-images.githubusercontent.com/31111509/105145974-b41ea680-5aff-11eb-8eb4-e9d87fd1e686.png)

**Story**
I've got an error message using inkscape 1.01 and textext 0.11 regarding that my python version is 3.8 instead of 2.7. After that I've noticed, that there is are newer textext versions, so I've installed it -- for inkscape 1.02, because it was upgraded as well -- and then have I seen the grayed out menu items.
textext was installed with setup.py without error or warning messages.
The files in ~/.config/inkscape/extensions/textext are all new.

**System information**
- TexText version: 0.11 and 1.3
- Inkscape version: 1.01 and 1.02
- Operating system: Xubuntu 20.04 LTS

**Comment by sizmailov** [comment]
Hm, that's strange. This probably caused by missing textext file. 

Can you attach output for 

```bash
ls "$(inkscape --user-data-directory)/extensions/textext/"
cat "$(inkscape --user-data-directory)/extensions/textext/textext.inx"
cat "$(inkscape --user-data-directory)/extensions/textext/VERSION"
```

**Comment by horror-vacui** [comment]
```
zoltan@aprosag ~ $ ls "$(inkscape --user-data-directory)/extensions/textext/"
asktext.py            errors.py    requirements_check.py  VERSION
base.py               icons        texoutparse.py         win_app_paths.py
config.json           __init__.py  textext.inx
default_packages.tex  __main__.py  utility.py
```
```
zoltan@aprosag ~ $ cat "$(inkscape --user-data-directory)/extensions/textext/textext.inx"
<inkscape-extension xmlns="http://www.inkscape.org/namespace/inkscape/extension">
  <name>Tex Text</name>
  <id>org.ekips.filter.textext</id>
  <effect implements-custom-gui="true">
    <object-type>all</object-type>
    <effects-menu>
        <submenu name="Text"/>
    </effects-menu>
  </effect>
  <script>
    <command location="inx" interpreter="python">__main__.py</command>
  </script>
</inkscape-extension>
```

```
zoltan@aprosag ~ $ cat "$(inkscape --user-data-directory)/extensions/textext/VERSION"
```


```

**Comment by sizmailov** [comment]
I've tried AppImage inkscape-1.0.2 with textext-1.2 and textext-1.3 and menu entery didn't appear gray. The missing file was my only guess so far. Probably one need to dive into inkscape sources to find out what went wrong, unless inkscape writes anything about disabled plugin to console (to check run inkscape from command line).

**Comment by horror-vacui** [comment]
> unless inkscape writes anything about disabled plugin to console (to check run inkscape from command line).

Indeed. Starting from the terminal I got the following warnings:
```
** (org.inkscape.Inkscape:18497): WARNING **: 12:05:34.345: Failed to find resource file 'textext.py'. Looked in:
	/home/zoltan/.config/inkscape/extensions/textext.py
	/usr/share/inkscape/extensions/textext.py
```
It searches for a python file, instead of a python module. Shall I contact the inkscape developers about this? Does inkscape behave in an unexpected way?
```
zoltan@aprosag ~ $ ls -la /home/zoltan/.config/inkscape/extensions/textext/
total 180
drwxrwxr-x 3 zoltan zoltan  4096 Jan 20 08:24 .
drwxr-x--x 5 zoltan zoltan  4096 Jan 20 08:24 ..
-rw-rw-r-- 1 zoltan zoltan 55163 Jan 20 08:24 asktext.py
-rw-rw-r-- 1 zoltan zoltan 35818 Jan 20 08:24 base.py
-rw-rw-r-- 1 zoltan zoltan   300 Jan 20 08:24 config.json
-rw-rw-r-- 1 zoltan zoltan    64 Jan 20 08:24 default_packages.tex
-rw-rw-r-- 1 zoltan zoltan  1380 Jan 20 08:24 errors.py
drwxrwxr-x 2 zoltan zoltan  4096 Jan 20 08:24 icons
-rw-rw-r-- 1 zoltan zoltan     0 Jan 20 08:24 __init__.py
-rw-rw-r-- 1 zoltan zoltan  2023 Jan 20 08:24 __main__.py
-rw-rw-r-- 1 zoltan zoltan 25796 Jan 20 08:24 requirements_check.py
-rw-rw-r-- 1 zoltan zoltan 10280 Jan 20 08:24 texoutparse.py
-rw-rw-r-- 1 zoltan zoltan   415 Jan 20 08:24 textext.inx
-rw-rw-r-- 1 zoltan zoltan  7809 Jan 20 08:24 utility.py
-rw-rw-r-- 1 zoltan zoltan     5 Jan 20 08:24 VERSION
-rw-rw-r-- 1 zoltan zoltan  2407 Jan 20 08:24 win_app_paths.py
```

**Comment by sizmailov** [comment]
That's odd. It _does_ work for inkscape-1.0 and current master branch (I've built it yesterday) ... 
Not sure why this get broken in the "middle" release. 

I think you can circumvent this bug by creating a file it looks for. 
It's a good idea to contact inkscape devs.

**Comment by horror-vacui** [comment]
I found the reason, though I am not sure how it triggered this problem.

I've used other inkscape extensions as well with version 0.92. They are from the inkscapeMadeEasy family. Once I've updated them, textext worked also as expected.

Sorry for the false alarm.
