### ISSUE TITLE
textext uses a different pdflatex

### ISSUE THREAD

**Issue by horror-vacui** [textext/textext#279]
**Description of the problem/ steps to reproduce**
textext does not produce output once a command from a package is used, for example \SI{5}{\volt} from \usepackage{siunitx}.
Also the stdout returns `This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)`, while running pdflatex from the command line (which I do quite often) returns `This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)`.

This led me to think to that textext does not use the `pdflatex` command of my shell. I've taken a cursory look at the source code, but I do not felt confident understanding it.

```
zoltan@aprosag ~/.config/inkscape/extensions/textext $ which pdflatex
/usr/local/texlive/2020/bin/x86_64-linux/pdflatex
```
According to textext log, this has been found.

**Steps to reproduce the behavior (if not obvious from description)**:
1. Add `\usepackage{siunitx}` into the `default_packages.tex` or an alternative preamble file.
2. Open textext gui and write in something like: `lorem ipsum \SI{5}{\volt}`
3. Compile by clickong on the Save button

**Message(s) in error dialog (if this comes up)**
! LaTeX Error: File `siunitx.sty' not found.

<details>
<summary>output of stdout (if available):</summary>

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./tmp.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amscls/amsthm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))

! LaTeX Error: File `siunitx.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.6 ^^M
       
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on tmp.log.


```
</details>

**Logfile**
[textext.log](https://github.com/textext/textext/files/5866095/textext.log)

**System information**

- TexText version: 1.3.0
- Inkscape version: 1.0.2 (1.0.2+r75+1)
- Operating system: Ubuntu 20.04.1 LTS

**Comment by jcwinkler** [comment]
According to the log file TexText uses `/usr/bin/pdflatex` not `/usr/local/texlive/2020/bin/x86_64-linux/pdflatex`

If you are usually working with the `pdflatex` command mapped to `/usr/local/texlive/2020/bin/x86_64-linux/pdflatex` I recommend to install TexText with the command

``` bash
python3 setup.py --pdflatex-executable /usr/local/texlive/2020/bin/x86_64-linux/pdflatex
```

**Comment by horror-vacui** [comment]
Thanks! It has solved the problem. It seems like that I had texlive both from repo and from source, without realizing it.

**Comment by horror-vacui** [comment]
The error was on the user side.
