### ISSUE TITLE
the setup_win.bat _requires_ double quotes on pathname, this isn't clear

### ISSUE THREAD

**Issue by PinkMushroom** [textext/textext#280]
First of all, i had a freshly installed inkscape using the msi and the batch file couldn't find it, but that's a different issue. 
However, not a problem, I'll just specify the installation path, thusly

`setup_win.bat --inkscape-executable C:\Program Files\Inkscape\bin\`

and then got this message

> Trying to detect Python interpreter in Inkscape installation directory...
> No Python interpreter found within your Inkscape installation.
> Expected as "C:\Users\xxxxxx\Downloads\textext-1.3.0\Files\Inkscape\\python.exe"
> You have to install Inkscape with the Python option enabled
> in the Inkscape installer.

well that's interesting because i absolutely did enable python.

Then i noticed this ;

> Specifiy an explicit directory via the --inkscape-executable option
> to look for if you installed Inkscape from a zip package. E.g.:
> setup_win --inkscape-executable "C:\Path\to\Inkscape installation\"

maybe i need double quotes !

`setup_win.bat --inkscape-executable "C:\Program Files\Inkscape\bin\"`

```
"C:\Program Files\Inkscape\bin\" found
Trying to detect Python interpreter in Inkscape installation directory...
"C:\Program Files\Inkscape\bin\\python.exe" found

Trying to run "C:\Program Files\Inkscape\bin\\python.exe" "C:\Users\xxxxxx\Downloads\textext-1.3.0\setup.py" --inkscape-executable "C:\Program Files\Inkscape\bin\"...

[TexText][ERROR   ]: Bad `inkscape` executable provided: `C:\Program Files\Inkscape\bin"`. Abort installation.
```

huh that's weird.   ohhhhh. i bet it's not the directory i need but the actual path to the executable, like so

`setup_win.bat --inkscape-executable "C:\Program Files\Inkscape\bin\inkscape.exe"`

success... but at every step the error message had nothing to do with what was actually wrong. in particular the batch file is specifically requesting a directory but it's the full path to the executable that is required.

**Comment by jcwinkler** [comment]
Thanks for the report!

> using the msi and the batch file couldn't find it

I will check this since the batch script is looking for the registry keys which should be set by the msi installer.

I agree that the help text

> Specifiy an explicit directory via the --inkscape-executable option
> to look for if you installed Inkscape from a zip package. E.g.:
> setup_win --inkscape-executable "C:\Path\to\Inkscape installation"

is misleading. What is meant (as the option says and you discovered) is the the full path to the inkscape executable. I will fix this right now. Double quotes are mandatory due to possible spaces in the path name. They are automatically set when autocompleting the path in the command window. But anyway, I will add a note to the doc.
