### ISSUE TITLE
amscls package is not installed by default in miktex but textext needs it

### ISSUE THREAD

**Issue by PinkMushroom** [textext/textext#281]
First of all be SURE and disable update on-the-fly in miktex, i.e. set it to **never** (not "ask me" like I did).  Setting to anything else, will cause miktex to run the console, textext will error out and you will go to the miktex log file and find out that

`GUI cannot be initialized`

That's because amsthm.sty is missing and miktex is attempting to run the console to install it. Since this is tex and package management is a completely non-obvious, amsthm.sty is not in the package amsthm it's in the package **amscls**. 

install **amscls** it manually using the miktex console once again checking sure that "update on the fly" is set to **never**, and things should work.

**Comment by jcwinkler** [comment]
> First of all be SURE and disable update on-the-fly in miktex

This is already covered by the documentation: https://textext.github.io/textext/install/windows.html If you use "auto" you will never by confronted with this problem. It is also addressed in the FAQ: https://textext.github.io/textext/usage/faq.html#windows-with-miktex-compilation-fails-with-empty-error-dialog

However, to be on the save side I will add a comment to the installation instructions directing the user to the fact that `amsmath,amsthm,amssymb,amsfonts` should be installed in the LaTeX distro. Thanks for the hint!
