### ISSUE TITLE
Error during TexText initialization

### ISSUE THREAD

**Issue by gforti84** [textext/textext#282]
Installed the TexText using the TexText-Windows-1.3.0.exe file and every time a open it the following error appears.
It eventually works after clicking in 'Continuar' (Continue) button.
![error_TexText](https://user-images.githubusercontent.com/77789351/107644673-7de3cb00-6c56-11eb-9edd-1b25545cc41c.JPG)

**Comment by jcwinkler** [comment]
Did you install the pygtk source view package? If so please remove it and try again. What happens? If not (i.e. you installed plain TexText package only) then I do not think that this is a TexText problem but rather an Inkscape one.

**Comment by gforti84** [comment]
pygtk was not installed. Later, the error also happened when I clicked on the "Export PNG Image -> Export As..." button.

**Comment by jcwinkler** [comment]
So I guess this is really related to Inkscape. It makes sense that this error also appears in TexText since TexText uses png related libs during processing the snippets.

Did you try the beloved "uninstall - install" method with Inkscape 😃 ?

**Comment by gforti84** [comment]
Yes, I tried it. 
Thanks for the attention, anyway.

**Comment by jcwinkler** [comment]
If you have a minimal working example (e.g. just a red rectangle) with the error occuring when clicking "Export PNG Image -> Export As..." I suggest to file a bug report at https://gitlab.com/inkscape/inbox.
