### ISSUE TITLE
Should we leave Travis?

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#286]
CI tests, packaging and documentation building is done via travis-ci.com for TexText. Travis has been bought by another company (see https://ropensci.org/blog/2020/11/19/moving-away-travis/#a-change-of-management)

I am not very happy with the new terms of usage for OSS. Especially https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source. I don't want to go begging every ~1000 minutes in a framework that is 0% transparent.

@sizmailov What do you think? I could imagine switching to github actions. Or do you have another recommendation?

**Comment by sizmailov** [comment]
I was unhappy with travis long before it changed owner, but I'm too ~~lazy~~ busy to put my own projects on new rails 

We have pretty straightforward tests, so any CI would work. I think github actions is the way to go, we are hosting here after all :)
