### ISSUE TITLE
TexText window looks nothing like the one in the documentation

### ISSUE THREAD

**Issue by mapfiable** [textext/textext#287]
**Description of the problem/ steps to reproduce**
I just installed the newest version of Inkscape (1.0.2-2) as well as the latest TexText version (1.3.1) on my Windows 10 machine (64bit). However, the TexText interface looks nothing like the one in the documentation. In fact, it's even missing the menu bar. Is this correct?

![image](https://user-images.githubusercontent.com/48512334/111032453-9a695380-840c-11eb-9eaa-910bf0d3beab.png)

**Comment by jcwinkler** [comment]
@mapfiable I did a mistake during packaging. Please download the TexText Version 1.3.1 windows package again and re-install TexText. After a re start of Inkscape you should see the gtk gui when invoking the TexText extension. Please report if this works for you.

**Comment by mapfiable** [comment]
Looks good now, thanks!
