### ISSUE TITLE
Preparation for Inkscape's 1.1 extension manager

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#289]
@sizmailov Do you know if we have to do any changes to the TexText extension in order to be well prepared for the Inkscape extension manager which will be released together with Inkscape 1.1? If I am correct you are still working with 1.1-dev so maybe you know anything?

**Comment by sizmailov** [comment]
Hi, I've never used the extension-manager. At the time of my interest it was in pre-alpha state.

If I recall it right, there is no changes required in a plugin itself, only in its packaging. I think extension manager supports `pip` channel, so it's should be matter of writing a 100 lines of boilerplate. But it's always to check official documentation.
