### ISSUE TITLE
When click textex buttom, a Error occurs: ImportError: DLL load failed while importing _socket, Is must I install a python 3.x ?

### ISSUE THREAD

**Issue by caixxiong** [textext/textext#290]
**Description of the problem/ steps to reproduce**
A clear and concise description of what the bug is and what you expected to happen.

**Steps to reproduce the behavior (if not obvious from description)**:
1. ....
2. ....
3. ....

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stdout (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version:latest 
- Inkscape version: 1.0.1
- Operating system: [e.g. Windows 10, 1803, 32-bit] windows 10
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): miktex latest
- Windows only: TexText installed via batch script or installer file:

**Additional information if you still use Inkscape 0.92.x / TexText 0.11**

- SVG-converter installed (pstoedit+ghostscript or pdf2svg):
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter):

**Comment by jcwinkler** [comment]
Thanks for the report. With the provided spare information it is not possible to detect the cause for this error.

Dll-load errors are not related to TexText itself. Most likely, your Inkscape installation is corrupt.

I suggest to reinstall Inkscape and make sure that Python and Extensions are selected during installation.
