### ISSUE TITLE
Convert line elements to objects for easy colour change

### ISSUE THREAD

**Issue by jocelynetienne** [textext/textext#291]
Observation: 

- When creating a formula such as $\frac{\overline{x}}{2}$, then changing colour of whole formula requires changing colour of both area and line. Alternatively, changing colour or area and then re-opening Textext interface applies area colour to all elements (one-off effect, next area colour change will not change overlines and fraction bars colour)
![image](https://user-images.githubusercontent.com/43367014/114311148-e384f400-9aed-11eb-89c4-3c7e2603d022.png)

-  Also, scaling of formula object will not thicken fraction bar and overline if scaling of lines is not activate in inkscape, which can be annoying if formula is part of a group one wants to scale without scaling of line thickness.

Analysis: The rendering tools, when converting formulae, converts at least fraction bars and overlines to lines, whereas the other symbols in formulae are borderline-free filled paths. 

Feature request: apply a transform similar to Inkscape's Path > Stroke to Path command to all shapes generated by the renderer.

**Comment by jcwinkler** [comment]
Thanks for the report. Since I have been participating in the development of this extension, the coloring of lines has been driving me crazy and the responsible code is weird. 

> apply a transform similar to Inkscape's Path > Stroke to Path

I will check if the extension API supports this. Doing it manually it seems to solve the scaling issue and makes coloring easier, thanks for the idea!

**Comment by jcwinkler** [comment]
OK, I think with the `--verb=StrokeToPath` option we can process the converted node. May require an additional Inkscape call. I will make an example implementation.

**Comment by jcwinkler** [comment]
Intermediate result: Having a snippet `frac.svg` containing a fraction as in the OP the following command converts the strokes to paths and saves it as `frac_path.svg` so colorization of the output can be done by one click:

```bash
inkscape -g --batch-process --actions="EditSelectAll;StrokeToPath;export-filename:frac_path.svg;export-do;FileClose" frac.svg
```
Big disadvantage: Inkscape will be invoked again.

Hence, I will now try to combine this action list with the TexText pdf->svg conversion command. 

Eventually, we should use the `inkex.command`-Python-API for the execution of the commands.
