### ISSUE TITLE
Import EPS file

### ISSUE THREAD

**Issue by lelandolt** [textext/textext#292]
I was trying to use EPSLatex (from Gnuplot) with TexText to plot something. For this, I use \input{fullpathgoeshere}, which works perfectly fine. However, in the process it converts the eps file to pdf. TexText somehow can't find this temporary pdf-file and i get "*-eps-converted-to.pdf not found".

So I am wondering, what the working directory of TexText is or if it's possible to set it manually, so I can try putting my files there. It doesn't seem to be the folder where the Inkscape document is located (which would be the case with a normal Latex editor).

**Comment by jcwinkler** [comment]
TexText generates a tex file which is stored in a temporary directory with a random name. Then the compile toolchain is initiated in this directory. It is deleted after the generated svg node is inserted into the document.

I am not 100% sure if I understand your question correctly. Could you provide a minimum (not) working example?

**Comment by lelandolt** [comment]
Thanks for your answer! I think I can reduce my problem to one thing: It's just that the import of eps files don't seem to be working with TexText. In my Latex editor this works, but TexText can't complete the conversion.

\includegraphics{.../plot.eps}

Do you have the same issue?

**Comment by jcwinkler** [comment]
Do you have the correct packages included into the preamble file? (graphics, epslatex...).

https://textext.github.io/textext/usage/gui.html#usage-preamble-file

**Comment by lelandolt** [comment]
\usepackage{epsfig} did the trick. So sorry, but thanks a lot!

**Comment by lelandolt** [comment]
I realized this only worked, since I had previously manually created the file "*-eps-converted-to.pdf" before, when I tried to fix the problem. I think the thing is, that TexText creates this file in the temporary directory you mentioned. However the compiler searches for it in the same folder as the eps I want to import (that is the path put in \includegraphics{}). Is that possible?

**Comment by jcwinkler** [comment]
Please provide a minimal working example as described here: https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain so we can investigate the cause of the error in more detail.

**Comment by lelandolt** [comment]
I already get an error at step 3. This probably means, the problem is in pdflatex and not TexText. I uploaded the error log but if this doesn't belong here, I can also close this thread.
[test.log](https://github.com/textext/textext/files/6429596/test.log)

**Comment by lelandolt** [comment]
I found a workaround that is converting to pdf manually with repstopdf --outfile=plot-eps-converted-to.pdf plot.eps

Since shell escape is a possible feature and not a bug, I will close this thread.
