### ISSUE TITLE
Possible fix of the error “GUI framework cannot be initialized” with TexText and MiKTeX?

### ISSUE THREAD

**Issue by srazasyed** [textext/textext#296]
I resolved the above error as follows. I am posting here in case some other users have a similar issue.

On the latest version of my **Windows 10 Pro** (Version 20H2), I installed **latest version 21.3 of MikTeX**  and latest version of [InScape ](https://inkscape.org/)(**version 1.1**), and the l**atest version 1.3.1 of TexText.** But when, on TexText, I ran even a simple LaTeX code `\[a^4\]` I got the following error: 
>FATAL pdflatex.core - GUI framework cannot be initialized.

I then followed [these ](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain) instructions titled `Manual use of the toolchain` from the author of the TexText.  And when I ran following command (from step 3 of the instructions), I got the following message from MikTeX:

`pdflatex test.tex -interaction=nonstopmode -halt-on-error`

MikTeX error:

![Untitled](https://user-images.githubusercontent.com/62360693/119923743-41578900-bf40-11eb-983c-0a7f97a4d0d0.png)

After that missing file was installed by MikTeX the TexText extension in InkScape started working.

**Comment by sizmailov** [comment]
Hi, thanks for sharing!

I think doc covers this issue [here](https://textext.github.io/textext/usage/faq.html#windows-with-miktex-compilation-fails-with-empty-error-dialog), though it might be not really discoverable :)

@jcwinkler Probably we should encourage bug-reporters to check FAQ/troubleshooting sections in `.github/ISSUE_TEMPLATE/bug_report.md`

**Comment by sizmailov** [comment]
`GUI framework cannot be initialized` message seems to be quite misleading with the solution given. We might want this line to doc pages to let people google it.

**Comment by srazasyed** [comment]
Thanks to user `@sizmailov`, a solution to the issue has been provided in the Q&A section [here](https://textext.github.io/textext/usage/faq.html#windows-with-miktex-compilation-fails-with-empty-error-dialog).

**Comment by jcwinkler** [comment]
@sizmailov I will update the docs accordingly.
