### ISSUE TITLE
TexText installed via Inkscape's extension manager cannot be treated as a module (?)

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#299]
When TexText is installed manually as we have done it up to now the complete `textext` directory is copied into `~/.config/inkscape/extensions`. It can then be invoked as a module via `__main__.py`.

When TexText is installed via Inkscape's new extension manager (manually via `Extensions`- `Manage Extensions...` - `Install packages`, there use the disk symbol) the `textext` directory is put into `~/.config/inkscape/extensions/org.ekips.filter.textext/textext`. Obviously the module invocation does not work there: 

```bash
  File "__main__.py", line 11, in <module>
    from textext.base import *
ModuleNotFoundError: No module named 'textext.base'
```

Changing `from textext.base import *` to `from .base import *` results in `ImportError: attempted relative import with no known parent package`, as exepcted.

Removing all relative imports (=destroying the package) makes TexText work again.

@sizmailov What do you think, should we switch to absolute imports and drop the "module" character of the extension? (Review of the extension by doctormo is stuck due to this issue)

You can download the package for manual install from here: https://inkscape.org/~jcwinkler/%E2%98%85textext

**Comment by sizmailov** [comment]
There should be a way to keep extension as a package without messing with paths, otherwise it would defeat the whole idea of an extension manager. Unfortunately I'm not familiar with inkscape extension manager. First we need to learn how it works, probably there is nothing fancy but still takes time, not sure when I'll be able to do that :/

As a last resort we can always ask inkscape devs for guidance, after all this functionality is still new and might have some undocumented corners. Martin, Patrick and many others were quite quick and open to help before.

**Comment by jcwinkler** [comment]
Thanks @sizmailov, you're right, I was too hasty once again. I contacted Martin and we are on track to find a solution.

**Comment by jcwinkler** [comment]
@sizmailov After some investigation and chat discussion the following can be concluded:

When a Python extension is invoked by Inkscape the following directories are added to the module search path:
- the user's extension directory (`~/.config/inkscape/extensions`)
- the directory in which the called Python file resides (specified in the `inx`file, in our case `__main__.py`)

When installing TexText from the command line we have the following structure:

```bash
~/.config/inkscape/extensions/textext/
~/.config/inkscape/extensions/textext/textext.inx
~/.config/inkscape/extensions/textext/__init__.py
~/.config/inkscape/extensions/textext/__main__.py
~/.config/inkscape/extensions/textext/(other files)
```
The directories ` ~/.config/inkscape/extensions` and `~/.config/inkscape/extensions/textext` are added to the path when TexText is called and due to ` ~/.config/inkscape/extensions`  being present there module import succeeds.

When TexText is installed from the extension manager it is installed into a different directory. One ends up with
```bash
~/.config/inkscape/extensions/org.ekips.filter.textext/textext/
~/.config/inkscape/extensions/org.ekips.filter.textext/textext/textext.inx
~/.config/inkscape/extensions/org.ekips.filter.textext/textext/__init__.py
~/.config/inkscape/extensions/org.ekips.filter.textext/textext/__main__.py
~/.config/inkscape/extensions/org.ekips.filter.textext/textext/(other files)
```
The directories ` ~/.config/inkscape/extensions` and `~/.config/inkscape/extensions/org.ekips.filter.textext/textext` are added to the path when TexText is called. Hence, all `textext` imports fail.

So what can we do? I have the following suggestion:
- Change`textext/__main__.py` to
  ```python
   from textext.base import *
   import traceback
   
   def run():   
     # Code goes here

   if __name__ == "__main__":
    run()
   ```
- Move `textext/textext.inx` one level up and let it call a new python script `textext_run.py` on that level.
- `textext_run.py` just contains:
  ```pyhton
  from textext.__main__ import run
  run()
  ```

So new extensions structure would be
```bash
textext.inx
textext_run.py
textext/
textext/__init__.py
textext/__main__.py
textext/(other files)
```

Advantage: Our module/package can be kept as is (except for the slight modification of `__main__.py`). Also setup from the command line needs not to be changed.

Disadvantage: Quite spooky import from `__main__` in `textext_run.py`

What do you think?

BTW: I suggested to the developers to make it possible to launch an extension directly as a module (`python -m textext') but I think this will be a long way to get realized - if ever...

**Comment by sizmailov** [comment]
> The directories ~/.config/inkscape/extensions and ~/.config/inkscape/extensions/org.ekips.filter.textext/textext 

This doesn't make sense to me. Why `~/.config/inkscape/extensions/org.ekips.filter.textext/textext` is added while `~/.config/inkscape/extensions/org.ekips.filter.textext/` is not? How extension manager knows that `textext` subdirectory exists in first place?!

WRT solutions. Of course we can circumvent any peculiarities of inkscape extension subsystem but IMO it would be in everybody's best interest to make healthy system with low level of surprise and confusion. 

Probably `textext` is one of few package-like extensions, so it would be us who finds this type of bugs...
