### ISSUE TITLE
Provide XeTeX and LuaTeX support

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#3]
XeTeX and LuaTeX become more and more prominent, especially due to their native UTF-8 support. It would be nice if TexText supports snippets for these compilers.

**Comment by jcwinkler** [comment]
The current development of this feature can be tracked in the branch [feature/xetex_luatex_support](https://github.com/jcwinkler/textext/tree/feature/xetex_luatex_support). It will be merged back as far as it is production ready to use.

**Comment by leberwurstsaft** [comment]
Was the TK interface done in the merged pull request?  The description initially said, it wasn't.
In case it is still not done, we should leave this open. Or close this, but add another issue specific to that missing part.

**Comment by jcwinkler** [comment]
At this moment, I am working on the TK implementation for xetex/luatex and anchor alignment.

**Comment by jcwinkler** [comment]
Provided as of release 0.8. (Why did automatic close did not work? :angry: )

**Comment by leberwurstsaft** [comment]
@jcwinkler You can automatically close issues with commit messages like this: https://help.github.com/articles/closing-issues-using-keywords/

Or with pull request descriptions like this: https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/

**Comment by jcwinkler** [comment]
I thought I did so, but I consequently wrote e.g. `resolves issue #3` (as in this case) instead of `resolves #3` as I am aware now after reading the links you provided :sob:
