### ISSUE TITLE
Does TexText 1.4.0 work with Inkscape 1.1 under (K)Ubuntu 21.04?

### ISSUE THREAD

**Issue by mocalvao** [textext/textext#303]
I used to have TexText 1.3.0 working seamlessly with Inkscape 1.0 in my desktop under Kubuntu 21.04 . I have just now upgrade Inkscape, via the Ubuntu ppa:inkscape.dev/stable-1.1, as officially recommended. The subsequent installation via the deb package worked completely fine. However, when I tried to launch the TexText extension GUI, through my former keyboard shortcut (Ctrl+T), there appeared an error message reading that Inkscape requires Python 3.6 or higher, and no gui showed up. 

Does anyone know any fix for this? Should I try and install now TexText 1.4.0, after removing TexText 1.3.0?

Thanks

**Comment by mocalvao** [comment]
I have checked that the system Python for Kubuntu 21.04 is still 2.7.18, as per the output from the command python --version in my default (fish) shell. Might this have some bearing on the issue?

**Comment by mocalvao** [comment]
I have also confirmed, under my ~/.config/inkscape/preferences.xml file, that my older Inkscape 1.0 installation (to which I have reverted right now), has the lines:

<group
     id="extensions"
     python-interpreter="/usr/bin/python2.7"
...

which, I guess, tell any extensions to use Python 2.7 instead of 3.6 or higher. I hope this helps solving this issue.
Regards

**Comment by mocalvao** [comment]
I installed again, from scratch, Inkscape 1.1 from the ppa, and then installed textext extension 1.4.0 with the simple plain command:

python setup.py

Apparently, the installation was completely succesfull, acording to the final message:

[TexText][SUCCESS ]: --> TexText has been SUCCESSFULLY installed on your system <--

However, when I launch Inkscape 1.1 and the brand new TexText 1.4.0 extension, the following message pops up:

Inkscape has received additional data from the script executed. The
script did not return an error, but this may indicate the results will 
not be as expected.
---
Inkscape extensions require Python 3.6 or greater.

As I said before, my Kubuntu system still has, as its system wide Python, the version 2.7.18. Might this be relevant? How does TexText in particular determines which version of Python to use?

Cheers

**Comment by sizmailov** [comment]
Hi! 

>  error message reading that Inkscape requires Python 3.6 or higher,

Did you try to install python3.6+ and follow "python3 branch" from https://textext.github.io/textext/install/linux.html? Does it work? 

You might be required to manually set python interpreter to python3.6+ (Inkscape use it  for _all extensions_), see https://wiki.inkscape.org/wiki/index.php/Extension_Interpreters

**Comment by mocalvao** [comment]
Dear Sergei Izmailov,

Your suggestion and link to redefine the python interpreter for Inkscape extensions nailed it! The problem is solved. Thank you very much. Perhaps the link should be more outstanding in the github repo.
