### ISSUE TITLE
Error and no output under Windows 10, Inkscape version 1.1 - "Toolchain" works fine

### ISSUE THREAD

**Issue by cvanberg** [textext/textext#306]
Apologies if this problem has been discussed elsewhere, I have not been able to find it.

**Description of the problem/ steps to reproduce**
I'm running Windows 10, texttext, MikTex etc. are all installed. The "toolchain" works: When I follow the instructions for manual use of the toolchain posted here https://textext.github.io/textext/usage/troubleshooting.html, I can produce all the expected output.)

When I use the extension in Inkscape, I get the following error and no output is produced: (Following: "Inkscape has received additional data... etc.")

**Message(s) in error dialog (if this comes up)**

<details>
<summary>dialog output (if available):</summary>

```
Traceback (most recent call last):
  File "pdflatex.py", line 89, in <module>
    PdfLatex().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\extensions.py", line 193, in effect
    for child in fragment:
  File "pdflatex.py", line 49, in generate
    call('pdflatex', tex_file,\
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\command.py", line 188, in call
    stdout = _call(program, *args, **kwargs)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\command.py", line 172, in _call
    raise ProgramRunError(f"Return Code: {process.returncode}: {stderr}\n{stdout}\nargs: {args}")
inkex.command.ProgramRunError: Return Code: 1: b''
b"This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.7)\r\nentering extended mode\r\n! I can't find file `C:/Users/C287B'.\r\n<to be read again> \r\n                   \\protect \r\n<*> C:/Users/C287B~\r\n                   1.VAN/AppData/Local/Temp/inktmpcaer0qo9/input.tex\r\nPlease type another input file name: \r\n! Emergency stop.\r\n<to be read again> \r\n                   \\protect \r\n<*> C:/Users/C287B~\r\n                   1.VAN/AppData/Local/Temp/inktmpcaer0qo9/input.tex\r\n!  ==> Fatal error occurred, no output PDF file produced!\r\nTranscript written on C:\\Users\\C287B~1.VAN\\AppData\\Local\\Temp\\inktmpcaer0qo9\\te\r\nxput.log.\r\n"
args: ['C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\pdflatex.EXE', '-output-directory=C:\\Users\\C287B~1.VAN\\AppData\\Local\\Temp\\inktmpcaer0qo9', '-halt-on-error', 'C:\\Users\\C287B~1.VAN\\AppData\\Local\\Temp\\inktmpcaer0qo9\\input.tex']
```
</details>

BTW The directory "C:/Users/C287B" and "C:\\Users\\C287B~1.VAN" do not exist, so I suspect that the error has something to do with this path being wrong. I can't find where to change this though.

**Logfile**
I am NOT finding a log file under the path `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext`

**System information**

- TexText version: 1.0 (I think)
- Inkscape version: 1.1
- Operating system: Windows 10 19042
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTex (latest version)
- Windows only: TexText installed via batch script or installer file: I don't remember. But as I said, the "toolchain" works.

**Comment by jcwinkler** [comment]
Hi @cvanberg, thanks for the report. Unfortunately, I currently have no access to my development tools. I will dive into this issue when I am back at home next weekend.
Regards, Jan
--
Jan Winkler
Mobil versandt, daher knapp gehalten.

*Von: *cvanberg ***@***.***>
*An: *textext/textext ***@***.***>
*Kopie: *Subscribed ***@***.***>
*Datum: *03.08.2021 10:08:46
*Betreff: *[textext/textext] Error and no output under Windows 10, Inkscape version 1.1 - "Toolchain" works fine (#306)

> Apologies if this problem has been discussed elsewhere, I have not been able to find it.
> 
> *Description of the problem/ steps to reproduce*
> I'm running Windows 10, texttext, MikTex etc. are all installed. The "toolchain" works: When I follow the instructions for manual use of the toolchain posted here https://textext.github.io/textext/usage/troubleshooting.html, I can produce all the expected output.)
> 
> When I use the extension in Inkscape, I get the following error and no output is produced: (Following: "Inkscape has received additional data... etc.")
> 
> *Message(s) in error dialog (if this comes up)*
> 
> dialog output (if available):
> Traceback (most recent call last):
>   File "pdflatex.py", line 89, in <module>
>     PdfLatex().run()
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
>     self.save_raw(self.effect())
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\extensions.py", line 193, in effect
>     for child in fragment:
>   File "pdflatex.py", line 49, in generate
>     call('pdflatex', tex_file,\
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\command.py", line 188, in call
>     stdout = _call(program, *args, **kwargs)
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\command.py", line 172, in _call
>     raise ProgramRunError(f"Return Code: {process.returncode}: {stderr}\n{stdout}\nargs: {args}")
> inkex.command.ProgramRunError: Return Code: 1: b''
> b"This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.7)\r\nentering extended mode\r\n! I can't find file `C:/Users/C287B'.\r\n<to be read again> \r\n                   \\protect \r\n<*> C:/Users/C287B~\r\n                   1.VAN/AppData/Local/Temp/inktmpcaer0qo9/input.tex\r\nPlease type another input file name: \r\n! Emergency stop.\r\n<to be read again> \r\n                   \\protect \r\n<*> C:/Users/C287B~\r\n                   1.VAN/AppData/Local/Temp/inktmpcaer0qo9/input.tex\r\n!  ==> Fatal error occurred, no output PDF file produced!\r\nTranscript written on C:\\Users\\C287B~1.VAN\\AppData\\Local\\Temp\\inktmpcaer0qo9\\te\r\nxput.log.\r\n"
> args: ['C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\pdflatex.EXE', '-output-directory=C:\\Users\\C287B~1.VAN\\AppData\\Local\\Temp\\inktmpcaer0qo9', '-halt-on-error', 'C:\\Users\\C287B~1.VAN\\AppData\\Local\\Temp\\inktmpcaer0qo9\\input.tex']
> 
> *Logfile*
> I am NOT finding a log file under the path *C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext*
> 
> *System information*
> 
* > TexText version: 1.0 (I think)
* > Inkscape version: 1.1
* > Operating system: Windows 10 19042
* > Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTex (latest version)
* > Windows only: TexText installed via batch script or installer file: I don't remember. But as I said, the "toolchain" works.

**Comment by jcwinkler** [comment]
@cvanberg Does your Windows user name contain whitespaces or non ascii symbols like ä or å?

**Comment by jcwinkler** [comment]
@cvanberg After inspecting the log information you provided I am little bit confused:

```
Traceback (most recent call last):
  File "pdflatex.py", line 89, in <module>
    PdfLatex().run()
```

The file `pdflatex.py` is not part of TexText. Are you sure you used TexText via the command `Extensions` - `Text` - `TexText` ?

Maybe you used the standard extension shipped with Inkscape which is accessed via `Extensions` - `Mathematics` - `LaTeX (pdflatex)` ?

**Comment by cvanberg** [comment]
Hi Jan,
you are right!! I simply didn't understand that these are different things. Sorry!
(BTW I'm glad to have discovered textext because it seems to be superior to what I had been using.)
Thanks for your help!
