### ISSUE TITLE
TexText on MAC OS

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#31]
This issue relates to the installation of TexText on MAC OS as this seems not to be as straight forward has it has been in the past. Especially the [ghostscript/pstoedit issue](https://bitbucket.org/pitgarbe/textext/issues/48/ghostscript-still-bug-under-linux) seems to be problematic.

From github issue #9:

> Thanks, I ended up building Ghostscript from source, but it didn't solve my issue. 

Relating to the neweset development in pstoedit and ghostscript: Please try to install

- ghostscript version 9.23
- pstoedit version 3.71

> Is there a good guide to debugging Inkscape extensions? 

Try PyCharm. Save an empty svg document and setup PyCharm such that it uses the Python 2.7 interpreter used by Inkscape and calls textext.py with the file name of the svg document as parameter. Ensure that the files bezmisc.py, cubicsuperpath.py, inkex.py, simplepath.py, simplestyle.py, simpletransform.py shipped with Inkscape are on the path. By this procedure you can debug TexText from the point where Inkscape has passed the svg document to TexText. (When testing a document which already contains TexText nodes you also have to pass the id of the node as parameter, e.g. the parameter line would read `--id=g1096 snippets/empty_eq_pdf2svg.svg`)

> I'm having trouble even figuring out what is failing.

What exactly happens from the user's view? Any messages?

**Comment by mpritzkoleit** [comment]
installation on macOS High Sierra, which worked for me:

1) install inkscape 0.91

2) copy files to your user path
    - with command+shift+. make .config in your user directory visible
    - copy the content (textext.py, asktext.py, etc.) of the textext folder you downloaded into     
       /Users/YourUserName/.config/inkscape/extensions

3) install pstoedit, ghostscript and imagemagick
    - install homebrew to use brew formulas
      run in terminal:
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - install pstoedit, ghostscript and imagemagick
      run in terminal:
      brew install pstoedit
     (this should install ghostscript and imagemagick as well. can be checked with the command: "brew info)

4) if you get an error in using textext in inkscape try:

 - replace "pdflatex" with: the result you get, when you enter "which pdflatex" in the terminal in my case: "/Library/TeX/texbin/pdflatex"
in asktex.py  /Users/YourUserName/.config/inkscape/extensions

Currently, preview is not working.

**Comment by BeastyBlacksmith** [comment]
> copy files to your user path
What files to which path exactly? Thats a little vague.
The inkscape files from `/Applications/Inkscape.app/` ?

**Comment by mpritzkoleit** [comment]
as described in 2) you copy the content of the textext-master repo (textext.py, asktext.py, default_packages.tex, latexlogparser.py, etc.) to  /Users/YourUserName/.config/inkscape/extensions.

**Comment by bdhammel** [comment]
To get it working on osx I also had to remove this line https://github.com/textext/textext/blob/master/textext.inx#L9

**Comment by jcwinkler** [comment]
I investigated the situation on MacOS together with @linneman and we came to the following conclusion:

1. When Inkscape is launched it sets up the environment such that MacOS’s system Python interpreter in `/usr/bin` is used. Hence, any installs in Homebrew Python are useless.

2. Inkscape is shipped with several Python modules and the directories of these modules are added to the `PYTHON_PATH` so they are found by the system interpreter. `PyGTK` and `TkInter` are included in these modules.

3. Having installed a Homebrew Python results in calls to this Python distribution if python is directly called from the command line, not the system Python.

From these observations one can conclude the following:

1. If one calls `python setup.py` from the command line the requirement check is meaningless because it calls a) the Homebrew interpreter which is not used by Inkscape or b)  the system interpreter (if Homebrew is not installed) which does not include `PyGTK` (but `TkInter`). Installation succeeds but with an incorrect alert w.r.t. missing `PyGTK`.

2. When TexText is launched from Inkscape everything is fine since `requirements_check.py` is called by the system interpreter with the Python modules shipped by Inkscape.

From my point of view the path to the Python modules shipped with Inkscape needs to be added in `setup.py` and user has to be forced to call setup.py as `/usr/bin/python setup.py`.

I attach the Inkscape script which is called during Inkscape startup which shows what is done.

<details>
  <summary>Click to expand</summary>

``` bash

#!/bin/sh
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications:
#	Michael Wybrow <mjwybrow@users.sourceforge.net>
#	Jean-Olivier Irisson <jo.irisson@gmail.com>
#	~suv <suv-sf@users.sourceforge.net>
#

get_env_current ()
{
	env | awk -F= '/[a-zA-Z_][a-zA-Z_0-9]*=/ {if (!system("[ -n \"${" $1 "+y}\" ]")) print $1 }' | sort | uniq
}
[ -z "$_env_orig" ] && export _env_orig="$(get_env_current)"

[ -n "$INK_DEBUG_LAUNCHER" ] && set -x

CMD="$(readlink $0 || echo $0)"
CWD="$(cd "$(dirname "$CMD")" && pwd -P)"
# e.g. /Applications/Inkscape.app/Contents/Resources/bin
TOP="$(dirname "$CWD")"
# e.g. /Applications/Inkscape.app/Contents/Resources
BASE="$(echo "$TOP" | sed -e 's/\/Contents\/Resources.*$//')"
# e.g. /Applications/Inkscape.app

# FIXME: Inkscape needs better relocation support for OS X (get rid of the relative 
# path hack in src/path-prefix.h for osxapp-enabled builds). Until then, below change
# of working directory is required:
#
# Due to changes after 0.48, we have to change working directory in the script named 'inkscape':
# recursive calls to inkscape from python-based extensions otherwise cause the app to hang or
# fail (for python-based extensions, inkscape changes the working directory to the 
# script's directory, and inkscape launched by python script thus can't find resources
# like the now essential 'units.xml' in INKSCAPE_UIDIR relative to the working directory).
cd "$BASE" || exit 1

# don't prepend to $PATH in recursive calls:
if [ -z "$INK_PATH_ORIG" ]; then

	# Brutally add many things to the PATH. If the directories do not exist, they won't be used anyway. 
	# the 'classic' PATH additions:
	#	/usr/local/bin which, though standard, doesn't seem to be in the PATH
	#	Fink
	#	MacPorts (former DarwinPorts)
	#	LaTeX distribution for Mac OS X
	PATH_OTHER="/Library/TeX/texbin:/usr/texbin:/opt/local/bin:/sw/bin/:/usr/local/bin"

	# Put /usr/bin at beginning of path so we make sure we use Apple's python 
	# over one that may be installed be Macports, Fink or some other means.
	PATH_PYTHON="/usr/bin"

	# Put $TOP/bin at beginning of path so we make sure that recursive calls
	# to inkscape don't pull in other inkscape binaries with different setup.
	# Also allows to override system python with custom wrapper script, and
	# e.g. to support GIMP.app or gimp for external editing and GIMP XCF export.
	PATH_pkgbin="$TOP/bin"

	# save orig, new PATH
	export INK_PATH_ORIG="$PATH"
	export PATH="$PATH_pkgbin:$PATH_PYTHON:$PATH_OTHER:$INK_PATH_ORIG"
fi

# Setup PYTHONPATH to use python modules shipped with Inkscape
OSXMINORNO="$(/usr/bin/sw_vers -productVersion | cut -d. -f2)"
build_arch=x86_64
if [ $OSXMINORNO -gt "5" ]; then
	if [ $OSXMINORNO -eq "6" ]; then
		export VERSIONER_PYTHON_VERSION=2.6
	else # if [ $OSXMINORNO -ge "7" ]; then
		export VERSIONER_PYTHON_VERSION=2.7
	fi
	if [ $build_arch = "i386" ]; then
		export VERSIONER_PYTHON_PREFER_32_BIT=yes
	else # build & runtime arch x86_64
		export VERSIONER_PYTHON_PREFER_32_BIT=no
	fi
fi
PYTHON_VERS="$(python -V 2>&1 | cut -c 8-10)"
export PYTHONPATH="$TOP/lib/python$PYTHON_VERS/site-packages/"

export FONTCONFIG_PATH="$TOP/etc/fonts"
export PANGO_RC_FILE="$TOP/etc/pango/pangorc"
export PANGO_SYSCONFDIR="$TOP/etc"
export GTK_IM_MODULE_FILE="$TOP/lib/gtk-2.0/2.10.0/immodules.cache"
export GDK_PIXBUF_MODULE_FILE="$TOP/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
export GTK_DATA_PREFIX="$TOP"
export GTK_EXE_PREFIX="$TOP"
export GTK_PATH="$TOP"
export GNOME_VFS_MODULE_CONFIG_PATH="$TOP/etc/gnome-vfs-2.0/modules"
export GNOME_VFS_MODULE_PATH="$TOP/lib/gnome-vfs-2.0/modules"
export GIO_USE_VFS="local"
export GVFS_REMOTE_VOLUME_MONITOR_IGNORE=1
export GVFS_DISABLE_FUSE=1
export XDG_DATA_DIRS="$TOP/share"
export ASPELL_CONF="prefix $TOP;"
export POPPLER_DATADIR="$TOP/share/poppler"

# Using fontconfig backend for slightly crisper UI text rendering
export PANGOCAIRO_BACKEND="fontconfig"
#export PANGOCAIRO_BACKEND="coretext"

# no DBUS for now
unset DBUS_LAUNCHD_SESSION_BUS_SOCKET
unset DBUS_SESSION_BUS_ADDRESS

# Note: This requires the path with the exact ImageMagic version number.
#       The actual version is inserted by the packaging script.
export MAGICK_CONFIGURE_PATH="$TOP/lib/ImageMagick-6.9.7/config:$TOP/share/ImageMagick-6.9.7_MAJOR/config"
export MAGICK_CODER_FILTER_PATH="$TOP/lib/ImageMagick-6.9.7/modules-Q16/filters"
export MAGICK_CODER_MODULE_PATH="$TOP/lib/ImageMagick-6.9.7/modules-Q16/coders"

export INKSCAPE_SHAREDIR="$TOP/share/inkscape"
export INKSCAPE_PLUGINDIR="$TOP/lib/inkscape"
export INKSCAPE_LOCALEDIR="$TOP/share/locale"

# Handle the case where the directory storing Inkscape has special characters
# ('#', '&', '|') in the name.  These need to be escaped to work properly for 
# various configuration files.
ESCAPEDTOP=`echo "$TOP" | sed 's/#/\\\\\\\\#/' | sed 's/&/\\\\\\&/g' | sed 's/|/\\\\\\|/g'`

# Set GTK theme (only if there is no .gtkrc-2.0 in the user's home)
if [[ ! -e "$HOME/.gtkrc-2.0" ]]; then
	export GTK2_RC_FILES="$ESCAPEDTOP/etc/gtk-2.0/gtkrc"
fi

# If the AppleCollationOrder preference doesn't exist, we fall back to using
# the AppleLocale preference.
LANGSTR=`defaults read .GlobalPreferences AppleCollationOrder 2>/dev/null`
if [ "x$LANGSTR" == "x" -o "x$LANGSTR" == "xroot" ]
then
    LANGSTR=`defaults read .GlobalPreferences AppleLocale 2>/dev/null | \
            sed 's/_.*//'`
	[ $_DEBUG ] && echo "Setting LANGSTR from AppleLocale: $LANGSTR" 1>&2
else
	[ $_DEBUG ] && echo "Setting LANGSTR from AppleCollationOrder: $LANGSTR" 1>&2
fi

# NOTE: Have to add ".UTF-8" to the LANG since omitting causes Inkscape
#       to crash on startup in locale_from_utf8().
if [ "x$LANGSTR" == "x" ]
then 
	# override broken script
	[ $_DEBUG ] && echo "Overriding empty LANGSTR" 1>&2
	export LANG="en_US.UTF-8"
else
	tmpLANG="`grep \"\`echo $LANGSTR\`_\" /usr/share/locale/locale.alias | \
		tail -n1 | awk '{print $2}' | sed 's/\./ /' | awk '{print $1}'`"
	if [ "x$tmpLANG" == "x" ]
	then
		# override broken script
		[ $_DEBUG ] && echo "Overriding empty LANG from /usr/share/locale/locale.alias" 1>&2
		export LANG="en_US.UTF-8"
	else
		[ $_DEBUG ] && echo "Setting LANG from /usr/share/locale/locale.alias" 1>&2
		export LANG="$tmpLANG.UTF-8"
	fi
fi
[ $_DEBUG ] && echo "Setting Language: $LANG" 1>&2
export LC_ALL="$LANG"

case "$INK_DEBUG" in
	gdb)
		EXEC="gdb --args" ;;
	lldb)
		EXEC="lldb -- " ;;
	dtruss)
		EXEC="dtruss" ;;
	*)
		EXEC="exec" ;;
esac
unset INK_DEBUG # ignore for recursive calls

if [ "x$INK_DEBUG_SHELL" != "x" ]; then
	unset INK_DEBUG_SHELL  # ignore for recursive calls
	exec bash
else
	$EXEC "$CWD/inkscape-bin" "$@"
fi

```

</details>

**Comment by sizmailov** [comment]
Thanks for investigation, but I think the conclusions cannot be extrapolated to be universal.

The interpreter used by inkscape *might* be configured to be anything, see http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters#Selecting_a_specific_interpreter_version_.28via_preferences_file.29

The default python interpreter on MacOS is just "python". I think the `/usr/bin/python` is used because of specific initialization of environment for GUI applications, similar to what happens on linux, recall https://github.com/textext/textext/issues/43#issuecomment-421490682 

For now I think the only 100% correct way to check requirements is to temporary install "textext-installer" extension (via any python) and run this extension from command line. It would be a way easier and less error prone than mocking python setup in inkscape. The downside: it need to call inkscape...
