### ISSUE TITLE
Cannot run TexText using Inkscape 1.1 after successful installation on Ubuntu 18.04

### ISSUE THREAD

**Issue by fel-ap** [textext/textext#312]
**Description of the problem/ steps to reproduce**
After a successful installation of TexText 1.5.0 (the python installation script outputs a sucess message), when running the plugin from within Inkscape 1.1 I get an error message and cannot get TexText to run.
This happens on a fresh Ubuntu 18.04 install. I installed Inkscape 1.1 using snap. I ran the install script using the built-in python interepreter in Ubuntu 18.04 (version 2.7.17). I also tried with the built-in Python 3 without success (version 3.6.9).

**Message(s) in error dialog (if this comes up)**
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]:        Please follow installation instructions at 
[TexText][CRITICAL]:               [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-gui-library[0m
[TexText][CRITICAL]:       /--or-* [Fail] GTK3 is not found
[TexText][CRITICAL]:       |      Please follow installation instructions at 
[TexText][CRITICAL]:       |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-gtk3[0m
[TexText][CRITICAL]:       /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]:              Please follow installation instructions at 
[TexText][CRITICAL]:                     [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-tkinter[0m
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

**Logfile**
[textext.log](https://github.com/textext/textext/files/7115629/textext.log)

**System information**

- TexText version: 1.5.0
- Inkscape version: 1.1
- Operating system: Ubuntu 18.04 64 bits

**Comment by jcwinkler** [comment]
As stated in the [documentation](https://textext.github.io/textext/install/linux.html) it is not possible to use TexText in Inkscape installed via snap. Reason is that Inkscape runs in an isolated environment when installed via snap and does not see your LaTeX distribution (as stated in the log message you posted).

Please follow the instructions mentioned in the documentation (i.e. install Inkscape via apt-get).
