### ISSUE TITLE
Plugin crashes on some SVG files

### ISSUE THREAD

**Issue by AdelKS** [textext/textext#321]
Hello,

First of all, thank you for this awesome plugin!

I am encountering an issue running the plugin on my machine, please find the install script output (successful) and the log file bellow. The error is essentially this one:

```
[TexText][ERROR   ]: xmlns:i: '&#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;ns_ai;' is not a valid URI, line 19, column 73 (ink_ext_XXXXXX.svgI9FJC1, line 19)
```

I cannot see any easy fix x)

**Install script output**
[textext-install.log](https://github.com/textext/textext/files/7496835/textext-install.log)

**Logfile**
[textext.log](https://github.com/textext/textext/files/7496816/textext.log)

**System information**

- TexText version: 1.6.0
- Inkscape version: Inkscape 1.1 (c68e22c387, 2021-05-23)
- Operating system: Linux (Gentoo)

Thanks!

**Comment by AdelKS** [comment]
Okay, I just tried it on a new empty document and it works. So I suppose my working `svg` file is broken ? Any ideas ?

**Comment by AdelKS** [comment]
Okay I narrowed it down to this logo (rename `broken.txt` to `broken.svg`)

[broken.txt](https://github.com/textext/textext/files/7496914/broken.txt)

**Comment by sizmailov** [comment]
Your svg file has invalid XML namespace declaration on line 16:
```xml
xmlns:ns="&amp;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;#38;ns_ai;"
```

> An XML namespace is declared using the reserved XML attribute xmlns or xmlns:prefix, the value of which must be a valid namespace name.  A namespace name is a uniform resource identifier (URI)

(from https://en.wikipedia.org/wiki/XML_namespace#Namespace_declaration)

Plugin provides a clear error message on invalid input. I think there is nothing to be done here.

**Comment by AdelKS** [comment]
I searched for that sequence within my original SVG file and I don't know why I did not find it... Thanks for your input.
