### ISSUE TITLE
Warning messsage pops up after compiling TeX code imported via File -> Open

### ISSUE THREAD

**Issue by RichardScharf** [textext/textext#322]
## Warning message pop up
after opening and inserting a .tex file using ctrl + o:

Inkscape has recieved additional data from the script executed. The script did not return an error, but this may indicate the results will not be as expected.
```
/home/myuser/.config/inkscape/extensions/textext/asktext.py:654: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/myuser/.config/inkscape/extensions/textext/my_texfile.tex' mode='r' encoding='UTF-8'>
  text = open(path).read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

### Steps to reproduce
1. Open textext extension
2. import an existing .tex file using File -> open (or use shortcut ctrl+o)
3. press save (or use shortcut ctrl + return)

## attempted fix:
**replaced line 654 in asktext.py**:
`text = open(path).read()`

with
```
file = open(path)
text = file.read()
file.close
```

Now I'm stuck with a 

## New warning:
```
/home/myuser/.config/inkscape/extensions/textext/asktext.py:679: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/myuser/.config/inkscape/extensions/textext/my_texfile.tex' mode='r' encoding='UTF-8'>
  AskTextGTKSource.load_file(text_buffer, path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by jcwinkler** [comment]
Thanks for the report. I confirm this behaviour on Windows as well (Honestly speaking: I have not used this feature for years...). I will check what's going on the next days.

Additional detail to have a complete overview: Although the warning message pops up the LaTeX snippet is correctly compiled and the svg node is placed into the document.
