### ISSUE TITLE
M1 Mac not work

### ISSUE THREAD

**Issue by Var-void** [textext/textext#323]
It seems Rosetta can not render TexText yet:
`rosetta error: /var/db/oah/279281325309952_279281325309952/53848c5cecf504fb2f445e61637f5b110f790ed68267e7ff16f5d6a82b886a39/_gi.cpython-38-darwin.so.aot: unable to mmap __TEXT: 1
`

**Comment by jcwinkler** [comment]
@Var-void The error is thrown from the python gi library, not by TexText. Most likely the Python installation used by Inkscape's extension subsystem is broken or Inkscape is incorrectly configured so it calls the wrong Python interpreter. A similar problem has been discussed and solved [here](https://gitlab.com/inkscape/extensions/-/issues/414). Maybe this does help?
