### ISSUE TITLE
Dependencis are met during installations but fails to find the dependencies in runtime.

### ISSUE THREAD

**Issue by Angshumank** [textext/textext#324]
Hi,
I installed textext for ubuntu 20.04 as mentioned in the website with the following command
`python setup.py --pdflatex-executable=/usr/bin/pdflatex --lualatex-executable=/usr/bin/lualatex --xelatex-executable=/usr/bin/lualatex`

The installation carries out without any problem. Part of the output is 
[TexText][INFO    ]: Using `pdflatex-executable` = `/usr/bin/pdflatex`
[TexText][INFO    ]: Using `lualatex-executable` = `/usr/bin/lualatex`
[TexText][INFO    ]: Using `xelatex-executable` = `/usr/bin/lualatex`
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/usr/bin/pdflatex`
[TexText][SUCCESS ]: |     /--or-* [Succ] lualatex is found at `/usr/bin/lualatex`
[TexText][SUCCESS ]: |     /--or-* [Succ] xelatex is found at `/usr/bin/lualatex`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][INFO    ]: `textext/default_packages.tex` is not found in distribution, keep old file
[TexText][INFO    ]: Removing `/home/angshu/.config/inkscape/extensions/textext`

However when I try to run textext from the inkscape I get the following errors

[TexText][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '1.6.0' (md5sum = 2a46b2ff9e56a6090725b8f55f9142eb)
[TexText][DEBUG   ]: platform.system() = 'Linux'
[TexText][DEBUG   ]: platform.release() = '5.11.0-40-generic'
[TexText][DEBUG   ]: platform.version() = '#44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021'
[TexText][DEBUG   ]: platform.machine() = 'x86_64'
[TexText][DEBUG   ]: platform.uname() = uname_result(system='Linux', node='angshu-HP-laptop-15-G6', release='5.11.0-40-generic', version='#44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021', machine='x86_64', processor='x86_64')
[TexText][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')
[TexText][DEBUG   ]: sys.executable = '/snap/inkscape/9256/bin/python3'
[TexText][DEBUG   ]: sys.version = '3.8.10 (default, Jun  2 2021, 10:49:15) \n[GCC 9.4.0]'
[TexText][DEBUG   ]: os.environ = environ({'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/angshu-HP-laptop-15-G6:@/tmp/.ICE-unix/2024,unix/angshu-HP-laptop-15-G6:/tmp/.ICE-unix/2024', 'QT_ACCESSIBILITY': '1', '__EGL_VENDOR_LIBRARY_DIRS': '/var/lib/snapd/lib/glvnd/egl_vendor.d', 'SNAP_REVISION': '9256', 'XDG_CONFIG_DIRS': '/snap/inkscape/9256/etc/xdg:/etc/xdg/xdg-ubuntu:/etc/xdg', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'SNAP_REAL_HOME': '/home/angshu', 'SNAP_USER_COMMON': '/home/angshu/snap/inkscape/common', 'FONTCONFIG_PATH': '/snap/inkscape/9256/etc/fonts', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LC_ADDRESS': 'en_IN.UTF-8', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'LC_NAME': 'en_IN.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XDG_DATA_HOME': '/home/angshu/snap/inkscape/9256/.local/share', 'XDG_CONFIG_HOME': '/home/angshu/snap/inkscape/9256/.config', 'XCURSOR_PATH': '/snap/inkscape/9256/data-dir/icons:/snap/inkscape/9256/usr/share/icons', 'SNAP_INSTANCE_KEY': '', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'ubuntu', 'LC_MONETARY': 'en_IN.UTF-8', 'SSH_AGENT_PID': '1990', 'GDK_PIXBUF_MODULE_FILE': '/home/angshu/snap/inkscape/common/.cache/gdk-pixbuf-loaders.cache', 'BAMF_DESKTOP_FILE_HINT': '/var/lib/snapd/desktop/applications/inkscape_inkscape.desktop', 'GTK_MODULES': 'gail:atk-bridge', 'PWD': '/home/angshu', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LOGNAME': 'angshu', 'XDG_SESSION_TYPE': 'x11', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'TEMPDIR': '/tmp', 'SNAP_CONTEXT': '7rbTBZ6CF_S3QZWFs8TVdSPja5EX8vfa4ZF2g4yQ1PnkxbOP2S-u', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'WINDOWPATH': '2', 'GST_PLUGIN_SCANNER': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner', 'LD_PRELOAD': ':/snap/inkscape/9256/lib/bindtextdomain.so', 'GI_TYPELIB_PATH': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/girepository-1.0', 'HOME': '/home/angshu/snap/inkscape/9256', 'USERNAME': 'angshu', 'IM_CONFIG_PHASE': '1', 'LC_PAPER': 'en_IN.UTF-8', 'LANG': 'en_US.UTF-8', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'SNAP_ARCH': 'amd64', 'SNAP_INSTANCE_NAME': 'inkscape', 'SNAP_USER_DATA': '/home/angshu/snap/inkscape/9256', 'TMPDIR': '/tmp', 'INVOCATION_ID': 'ef7c63ba793b4bfb9f7d72d035b71b19', 'SNAP_LAUNCHER_ARCH_TRIPLET': 'x86_64-linux-gnu', 'MANAGERPID': '1802', 'SNAP_REEXEC': '', 'INKSCAPE_DATADIR': '/snap/inkscape/9256/share', 'XDG_CACHE_HOME': '/home/angshu/snap/inkscape/common/.cache', 'GJS_DEBUG_OUTPUT': 'stderr', 'XDG_SESSION_CLASS': 'user', 'LC_IDENTIFICATION': 'en_IN.UTF-8', 'GTK_PATH': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/gtk-3.0', 'XLOCALEDIR': '/snap/inkscape/9256/usr/share/X11/locale', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'USER': 'angshu', 'SNAP': '/snap/inkscape/9256', 'SNAP_COMMON': '/var/snap/inkscape/common', 'SNAP_VERSION': '1.1.1-eb90963e84-2021-10-02', 'DISPLAY': ':1', 'SHLVL': '0', 'GDK_PIXBUF_MODULEDIR': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders', 'LOCPATH': '/snap/inkscape/9256/usr/lib/locale', 'SNAP_LIBRARY_PATH': '/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void', 'SNAP_COOKIE': '7rbTBZ6CF_S3QZWFs8TVdSPja5EX8vfa4ZF2g4yQ1PnkxbOP2S-u', 'LC_TELEPHONE': 'en_IN.UTF-8', 'INKSCAPE_PROFILE_DIR': '/home/angshu/.config/inkscape', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'en_IN.UTF-8', 'LIBGL_DRIVERS_PATH': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/dri', 'PAPERSIZE': 'a4', 'SNAP_DATA': '/var/snap/inkscape/9256', 'GST_PLUGIN_PATH': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/gstreamer-1.0', 'GS_LIB': '/snap/inkscape/9256/usr/share/ghostscript/9.50/Resource/Init/', 'LD_LIBRARY_PATH': '/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/inkscape/9256/lib:/snap/inkscape/9256/usr/lib:/snap/inkscape/9256/lib/x86_64-linux-gnu:/snap/inkscape/9256/usr/lib/x86_64-linux-gnu', 'XDG_RUNTIME_DIR': '/run/user/1000/snap.inkscape', 'LC_TIME': 'en_IN.UTF-8', 'GST_PLUGIN_SYSTEM_PATH': '/snap/inkscape/9256/usr/lib/x86_64-linux-gnu/gstreamer-1.0', 'FONTCONFIG_FILE': '/home/angshu/snap/inkscape/9256/.config/fontconfig/fonts.conf', 'SNAP_NAME': 'inkscape', 'JOURNAL_STREAM': '8:52142', 'XDG_DATA_DIRS': '/home/angshu/snap/inkscape/9256/.local/share:/home/angshu/snap/inkscape/9256:/snap/inkscape/9256/data-dir:/snap/inkscape/9256/share:/snap/inkscape/9256/usr/share:/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/snap/inkscape/9256/share/inkscape', 'PATH': '/snap/inkscape/9256/bin:/snap/inkscape/9256/usr/sbin:/snap/inkscape/9256/usr/bin:/snap/inkscape/9256/sbin:/snap/inkscape/9256/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games', 'GTK_USE_PORTAL': '1', 'GDMSESSION': 'ubuntu', 'GTK_IM_MODULE_FILE': '/home/angshu/snap/inkscape/common/.cache/immodules/immodules.cache', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'VDPAU_DRIVER_PATH': '/var/lib/snapd/lib/gl/vdpau', 'GIO_MODULE_DIR': '/home/angshu/snap/inkscape/common/.cache/gio-modules', 'PULSE_SERVER': 'unix:/run/user/1000/snap.inkscape/../pulse/native', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '119198', 'XKB_CONFIG_ROOT': '/snap/inkscape/9256/usr/share/X11/xkb', 'GIO_LAUNCHED_DESKTOP_FILE': '/var/lib/snapd/desktop/applications/inkscape_inkscape.desktop', 'LC_NUMERIC': 'en_IN.UTF-8', 'INKSCAPE_LOCALEDIR': '/snap/inkscape/9256/share/locale', 'PYTHONPATH': '/home/angshu/.config/inkscape/extensions:/snap/inkscape/9256/share/inkscape/extensions:/snap/inkscape/9256/share/inkscape/extensions/inkex/deprecated-simple', 'PYTHONIOENCODING': 'UTF-8', 'DOCUMENT_PATH': '', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKEX_GETTEXT_DIRECTORY': '/snap/inkscape/9256/share/locale'})
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][CRITICAL]: /-and-+ [Fail] Detect *latex
[TexText][CRITICAL]: |      Please follow installation instructions at 
[TexText][CRITICAL]: |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     /--or-* [Fail] `pdflatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     |      If pdflatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --pdflatex-executable=<path-to-pdflatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `lualatex` is NOT found in PATH
[TexText][CRITICAL]: |     |      Please follow installation instructions at 
[TexText][CRITICAL]: |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][CRITICAL]: |     |      and run setup.py again
[TexText][CRITICAL]: |     /--or-* [Fail] `xelatex` is NOT found in PATH
[TexText][CRITICAL]: |            Please follow installation instructions at 
[TexText][CRITICAL]: |                   [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-preparation[0m
[TexText][CRITICAL]: |            If xelatex is installed in custom location, specify it via 
[TexText][CRITICAL]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][CRITICAL]: |            and run setup.py again
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]:        Please follow installation instructions at 
[TexText][CRITICAL]:               [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-gui-library[0m
[TexText][CRITICAL]:       /--or-* [Fail] GTK3 is not found
[TexText][CRITICAL]:       |      Please follow installation instructions at 
[TexText][CRITICAL]:       |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-gtk3[0m
[TexText][CRITICAL]:       /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]:              Please follow installation instructions at 
[TexText][CRITICAL]:                     [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-tkinter[0m
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/

Please let me know if I need to provide anything else to help to understand the issue.
Thank you for your help.

**Comment by jcwinkler** [comment]
@Angshumank The log file points out that you have installed **Inkscape** via the **snap package manager**. It is impossible to use TexText when Inkscape is installed via snap, please see the green box in https://textext.github.io/textext/install/linux.html.

I recommend to uninstall Inkscape via snap and then install it via `apt` as described in the documentation linked above.

**Comment by Angshumank** [comment]
Yes, you are right. Thank you for your help.
