### ISSUE TITLE
TexText is not responding

### ISSUE THREAD

**Issue by E1onE2** [textext/textext#326]
Hey, clicking on "Preview" or "Save" I always get a non responding TexText box.
Older version were running fine. I am not even recieving an error message or a log file.
It's independent of the Tex used. I am using Windows 10 and newest Inkscape.

*Update*
I reinstalled Inkscape and TextTex and it worked fine for about 2h. Now I got the same problem again. How can that happen?

![image](https://user-images.githubusercontent.com/73277076/141824637-6b754d9e-0542-4cfd-a4d4-d3bec00ae3eb.png)

![image](https://user-images.githubusercontent.com/73277076/141824704-88dd7a0c-7fd7-4f56-ba27-645d47092896.png)

**Comment by jcwinkler** [comment]
Thanks for the report @E1onE2.

Some questions:
1. If you downgrade to TexText 1.5.0, does this also happen?
2. Do the snippets which fail to compile also fail to compile in the manual toolchain (refer to [documentation](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain) how to test it).
3. Do the same snippets sometimes compile and sometimes not?

**Comment by E1onE2** [comment]
To point 1:
Inkscpae is not responding opening the extension.
![Inkscpae_TexText_not_responding](https://user-images.githubusercontent.com/73277076/142630904-5bedab6d-3a4e-49e6-b068-a440392ed0e5.PNG)

To point 2:
It fails too. Here the output:
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/tracefnt.s
ty")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/latexsym.s
ty"))
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/article.cl
s"
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/size10.clo
" ("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/lm/ot1lmr.fd"
))) ("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/mff.sty
"
LaTeX Style file MFF.STY, ver. 1.21 [June 1996]

("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/mfdcdata.te
x")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/mfsauter.te
x")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/mfcorfnt.te
x")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/mftricks.te
x")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/mfarithm.te
x"))
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/l3backend/l3bac
kend-luatex.def") (./test.aux)
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/ts1cmr.fd"
)
<MFF/line=11>: No file xxz15.tfm -- dummy font will be used

warning  (font): lua-loaded font '26' with name 'dummy' has no characters
<MFF/line=11>: Do not forget to process xxz15.mf and reprocess this file
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/mff/table.tex")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/ulasy.fd")
("C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/tex/latex/lm/ot1lmtt.fd")
 [1{C:/Users/qe85pumi/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}
Missing character: There is no ^^@ (U+0000) in font dummy!
Missing character: There is no ^^A (U+0001) in font dummy!
Missing character: There is no ^^B (U+0002) in font dummy!
Missing character: There is no ^^C (U+0003) in font dummy!
Missing character: There is no ^^D (U+0004) in font dummy!
Missing character: There is no ^^E (U+0005) in font dummy!
Missing character: There is no ^^F (U+0006) in font dummy!
Missing character: There is no ^^G (U+0007) in font dummy!
Missing character: There is no ^^H (U+0008) in font dummy!
Missing character: There is no   (U+0009) in font dummy!
Missing character: There is no
 (U+000A) in font dummy!
Missing character: There is no ^^K (U+000B) in font dummy!
Missing character: There is no ^^L (U+000C) in font dummy!
 (U+000D) in font dummy! is no
Missing character: There is no ^^N (U+000E) in font dummy!
Missing character: There is no ^^O (U+000F) in font dummy!
Missing character: There is no ^^P (U+0010) in font dummy!
Missing character: There is no ^^Q (U+0011) in font dummy!
Missing character: There is no ^^R (U+0012) in font dummy!
Missing character: There is no ^^S (U+0013) in font dummy!
Missing character: There is no ^^T (U+0014) in font dummy!
Missing character: There is no ^^U (U+0015) in font dummy!
Missing character: There is no ^^V (U+0016) in font dummy!
Missing character: There is no ^^W (U+0017) in font dummy!
Missing character: There is no ^^X (U+0018) in font dummy!
Missing character: There is no ^^Y (U+0019) in font dummy!
Missing character: There is no ^^Z (U+001A) in font dummy!
Missing character: There is no ^^[ (U+001B) in font dummy!
Missing character: There is no ^^\ (U+001C) in font dummy!
Missing character: There is no ^^] (U+001D) in font dummy!
Missing character: There is no ^^^ (U+001E) in font dummy!
Missing character: There is no ^^_ (U+001F) in font dummy!
Missing character: There is no   (U+0020) in font dummy!
Missing character: There is no ! (U+0021) in font dummy!
Missing character: There is no " (U+0022) in font dummy!
Missing character: There is no # (U+0023) in font dummy!
Missing character: There is no $ (U+0024) in font dummy!
Missing character: There is no % (U+0025) in font dummy!
Missing character: There is no & (U+0026) in font dummy!
Missing character: There is no ' (U+0027) in font dummy!
Missing character: There is no ( (U+0028) in font dummy!
Missing character: There is no ) (U+0029) in font dummy!
Missing character: There is no * (U+002A) in font dummy!
Missing character: There is no + (U+002B) in font dummy!
Missing character: There is no , (U+002C) in font dummy!
Missing character: There is no - (U+002D) in font dummy!
Missing character: There is no . (U+002E) in font dummy!
Missing character: There is no / (U+002F) in font dummy!
Missing character: There is no 0 (U+0030) in font dummy!
Missing character: There is no 1 (U+0031) in font dummy!
Missing character: There is no 2 (U+0032) in font dummy!
Missing character: There is no 3 (U+0033) in font dummy!
Missing character: There is no 4 (U+0034) in font dummy!
Missing character: There is no 5 (U+0035) in font dummy!
Missing character: There is no 6 (U+0036) in font dummy!
Missing character: There is no 7 (U+0037) in font dummy!
Missing character: There is no 8 (U+0038) in font dummy!
Missing character: There is no 9 (U+0039) in font dummy!
Missing character: There is no : (U+003A) in font dummy!
Missing character: There is no ; (U+003B) in font dummy!
Missing character: There is no < (U+003C) in font dummy!
Missing character: There is no = (U+003D) in font dummy!
Missing character: There is no > (U+003E) in font dummy!
Missing character: There is no ? (U+003F) in font dummy!
Missing character: There is no @ (U+0040) in font dummy!
Missing character: There is no A (U+0041) in font dummy!
Missing character: There is no B (U+0042) in font dummy!
Missing character: There is no C (U+0043) in font dummy!
Missing character: There is no D (U+0044) in font dummy!
Missing character: There is no E (U+0045) in font dummy!
Missing character: There is no F (U+0046) in font dummy!
Missing character: There is no G (U+0047) in font dummy!
Missing character: There is no H (U+0048) in font dummy!
Missing character: There is no I (U+0049) in font dummy!
Missing character: There is no J (U+004A) in font dummy!
Missing character: There is no K (U+004B) in font dummy!
Missing character: There is no L (U+004C) in font dummy!
Missing character: There is no M (U+004D) in font dummy!
Missing character: There is no N (U+004E) in font dummy!
Missing character: There is no O (U+004F) in font dummy!
Missing character: There is no P (U+0050) in font dummy!
Missing character: There is no Q (U+0051) in font dummy!
Missing character: There is no R (U+0052) in font dummy!
Missing character: There is no S (U+0053) in font dummy!
Missing character: There is no T (U+0054) in font dummy!
Missing character: There is no U (U+0055) in font dummy!
Missing character: There is no V (U+0056) in font dummy!
Missing character: There is no W (U+0057) in font dummy!
Missing character: There is no X (U+0058) in font dummy!
Missing character: There is no Y (U+0059) in font dummy!
Missing character: There is no Z (U+005A) in font dummy!
Missing character: There is no [ (U+005B) in font dummy!
Missing character: There is no \ (U+005C) in font dummy!
Missing character: There is no ] (U+005D) in font dummy!
Missing character: There is no ^ (U+005E) in font dummy!
Missing character: There is no _ (U+005F) in font dummy!
Missing character: There is no ` (U+0060) in font dummy!
Missing character: There is no a (U+0061) in font dummy!
Missing character: There is no b (U+0062) in font dummy!
Missing character: There is no c (U+0063) in font dummy!
Missing character: There is no d (U+0064) in font dummy!
Missing character: There is no e (U+0065) in font dummy!
Missing character: There is no f (U+0066) in font dummy!
Missing character: There is no g (U+0067) in font dummy!
Missing character: There is no h (U+0068) in font dummy!
Missing character: There is no i (U+0069) in font dummy!
Missing character: There is no j (U+006A) in font dummy!
Missing character: There is no k (U+006B) in font dummy!
Missing character: There is no l (U+006C) in font dummy!
Missing character: There is no m (U+006D) in font dummy!
Missing character: There is no n (U+006E) in font dummy!
Missing character: There is no o (U+006F) in font dummy!
Missing character: There is no p (U+0070) in font dummy!
Missing character: There is no q (U+0071) in font dummy!
Missing character: There is no r (U+0072) in font dummy!
Missing character: There is no s (U+0073) in font dummy!
Missing character: There is no t (U+0074) in font dummy!
Missing character: There is no u (U+0075) in font dummy!
Missing character: There is no v (U+0076) in font dummy!
Missing character: There is no w (U+0077) in font dummy!
Missing character: There is no x (U+0078) in font dummy!
Missing character: There is no y (U+0079) in font dummy!
Missing character: There is no z (U+007A) in font dummy!
Missing character: There is no { (U+007B) in font dummy!
Missing character: There is no | (U+007C) in font dummy!
Missing character: There is no } (U+007D) in font dummy!
Missing character: There is no ~ (U+007E) in font dummy!
Missing character: There is no  (U+007F) in font dummy!
Missing character: There is no  (U+0080) in font dummy!
Missing character: There is no  (U+0081) in font dummy!
Missing character: There is no  (U+0082) in font dummy!
Missing character: There is no  (U+0083) in font dummy!
Missing character: There is no  (U+0084) in font dummy!
Missing character: There is no  (U+0085) in font dummy!
Missing character: There is no  (U+0086) in font dummy!
Missing character: There is no  (U+0087) in font dummy!
Missing character: There is no  (U+0088) in font dummy!
Missing character: There is no  (U+0089) in font dummy!
Missing character: There is no  (U+008A) in font dummy!
Missing character: There is no  (U+008B) in font dummy!
Missing character: There is no  (U+008C) in font dummy!
Missing character: There is no  (U+008D) in font dummy!
Missing character: There is no  (U+008E) in font dummy!
Missing character: There is no  (U+008F) in font dummy!
Missing character: There is no  (U+0090) in font dummy!
Missing character: There is no  (U+0091) in font dummy!
Missing character: There is no  (U+0092) in font dummy!
Missing character: There is no  (U+0093) in font dummy!
Missing character: There is no  (U+0094) in font dummy!
Missing character: There is no  (U+0095) in font dummy!
Missing character: There is no  (U+0096) in font dummy!
Missing character: There is no  (U+0097) in font dummy!
Missing character: There is no  (U+0098) in font dummy!
Missing character: There is no  (U+0099) in font dummy!
Missing character: There is no  (U+009A) in font dummy!
Missing character: There is no  (U+009B) in font dummy!
Missing character: There is no  (U+009C) in font dummy!
Missing character: There is no  (U+009D) in font dummy!
Missing character: There is no  (U+009E) in font dummy!
Missing character: There is no  (U+009F) in font dummy!
Missing character: There is no   (U+00A0) in font dummy!
Missing character: There is no ¡ (U+00A1) in font dummy!
Missing character: There is no ¢ (U+00A2) in font dummy!
Missing character: There is no £ (U+00A3) in font dummy!
Missing character: There is no ¤ (U+00A4) in font dummy!
Missing character: There is no ¥ (U+00A5) in font dummy!
Missing character: There is no ¦ (U+00A6) in font dummy!
Missing character: There is no § (U+00A7) in font dummy!
Missing character: There is no ¨ (U+00A8) in font dummy!
Missing character: There is no © (U+00A9) in font dummy!
Missing character: There is no ª (U+00AA) in font dummy!
Missing character: There is no « (U+00AB) in font dummy!
Missing character: There is no ¬ (U+00AC) in font dummy!
Missing character: There is no ­ (U+00AD) in font dummy!
Missing character: There is no ® (U+00AE) in font dummy!
Missing character: There is no ¯ (U+00AF) in font dummy!
Missing character: There is no ° (U+00B0) in font dummy!
Missing character: There is no ± (U+00B1) in font dummy!
Missing character: There is no ² (U+00B2) in font dummy!
Missing character: There is no ³ (U+00B3) in font dummy!
Missing character: There is no ´ (U+00B4) in font dummy!
Missing character: There is no µ (U+00B5) in font dummy!
Missing character: There is no ¶ (U+00B6) in font dummy!
Missing character: There is no · (U+00B7) in font dummy!
Missing character: There is no ¸ (U+00B8) in font dummy!
Missing character: There is no ¹ (U+00B9) in font dummy!
Missing character: There is no º (U+00BA) in font dummy!
Missing character: There is no » (U+00BB) in font dummy!
Missing character: There is no ¼ (U+00BC) in font dummy!
Missing character: There is no ½ (U+00BD) in font dummy!
Missing character: There is no ¾ (U+00BE) in font dummy!
Missing character: There is no ¿ (U+00BF) in font dummy!
Missing character: There is no À (U+00C0) in font dummy!
Missing character: There is no Á (U+00C1) in font dummy!
Missing character: There is no Â (U+00C2) in font dummy!
Missing character: There is no Ã (U+00C3) in font dummy!
Missing character: There is no Ä (U+00C4) in font dummy!
Missing character: There is no Å (U+00C5) in font dummy!
Missing character: There is no Æ (U+00C6) in font dummy!
Missing character: There is no Ç (U+00C7) in font dummy!
Missing character: There is no È (U+00C8) in font dummy!
Missing character: There is no É (U+00C9) in font dummy!
Missing character: There is no Ê (U+00CA) in font dummy!
Missing character: There is no Ë (U+00CB) in font dummy!
Missing character: There is no Ì (U+00CC) in font dummy!
Missing character: There is no Í (U+00CD) in font dummy!
Missing character: There is no Î (U+00CE) in font dummy!
Missing character: There is no Ï (U+00CF) in font dummy!
Missing character: There is no Ð (U+00D0) in font dummy!
Missing character: There is no Ñ (U+00D1) in font dummy!
Missing character: There is no Ò (U+00D2) in font dummy!
Missing character: There is no Ó (U+00D3) in font dummy!
Missing character: There is no Ô (U+00D4) in font dummy!
Missing character: There is no Õ (U+00D5) in font dummy!
Missing character: There is no Ö (U+00D6) in font dummy!
Missing character: There is no × (U+00D7) in font dummy!
Missing character: There is no Ø (U+00D8) in font dummy!
Missing character: There is no Ù (U+00D9) in font dummy!
Missing character: There is no Ú (U+00DA) in font dummy!
Missing character: There is no Û (U+00DB) in font dummy!
Missing character: There is no Ü (U+00DC) in font dummy!
Missing character: There is no Ý (U+00DD) in font dummy!
Missing character: There is no Þ (U+00DE) in font dummy!
Missing character: There is no ß (U+00DF) in font dummy!
Missing character: There is no à (U+00E0) in font dummy!
Missing character: There is no á (U+00E1) in font dummy!
Missing character: There is no â (U+00E2) in font dummy!
Missing character: There is no ã (U+00E3) in font dummy!
Missing character: There is no ä (U+00E4) in font dummy!
Missing character: There is no å (U+00E5) in font dummy!
Missing character: There is no æ (U+00E6) in font dummy!
Missing character: There is no ç (U+00E7) in font dummy!
Missing character: There is no è (U+00E8) in font dummy!
Missing character: There is no é (U+00E9) in font dummy!
Missing character: There is no ê (U+00EA) in font dummy!
Missing character: There is no ë (U+00EB) in font dummy!
Missing character: There is no ì (U+00EC) in font dummy!
Missing character: There is no í (U+00ED) in font dummy!
Missing character: There is no î (U+00EE) in font dummy!
Missing character: There is no ï (U+00EF) in font dummy!
Missing character: There is no ð (U+00F0) in font dummy!
Missing character: There is no ñ (U+00F1) in font dummy!
Missing character: There is no ò (U+00F2) in font dummy!
Missing character: There is no ó (U+00F3) in font dummy!
Missing character: There is no ô (U+00F4) in font dummy!
Missing character: There is no õ (U+00F5) in font dummy!
Missing character: There is no ö (U+00F6) in font dummy!
Missing character: There is no ÷ (U+00F7) in font dummy!
Missing character: There is no ø (U+00F8) in font dummy!
Missing character: There is no ù (U+00F9) in font dummy!
Missing character: There is no ú (U+00FA) in font dummy!
Missing character: There is no û (U+00FB) in font dummy!
Missing character: There is no ü (U+00FC) in font dummy!
Missing character: There is no ý (U+00FD) in font dummy!
Missing character: There is no þ (U+00FE) in font dummy!
Missing character: There is no ÿ (U+00FF) in font dummy!
] (./test.aux))
(see the transcript file for additional information)
 406 words of node memory still in use:
   3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 1 glyph, 4 attribute, 48 glue_spec
, 4 attribute_list, 1 write nodes
   avail lists: 2:2243,3:4,4:1,5:25,6:1,7:7272,8:1,9:1764
{C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/fonts/enc/dvips/lm/lm-rm.e
nc}{C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/fonts/enc/dvips/lm/lm-r
mtt.enc}<C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/fonts/type1/public
/lm/lmr10.pfb><C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/fonts/type1/
public/lm/lmr12.pfb><C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/fonts/
type1/public/lm/lmtt8.pfb>
Output written on test.pdf (1 page, 63637 bytes).
Transcript written on test.log

To Point 3:
It worked for some time, but after that not anymore.

Thanks for the help.

**Comment by jcwinkler** [comment]
Hmm, at first you should ensure that the [manual toolchain](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain) is working properly. Try to compile
```tex
$x=y$
```
with the standard preamble, i.e. the document
```tex
\documentclass{article}

\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}

\pagestyle{empty}

\begin{document}
$x=y$
\end{document}
```
using pdflatex. If this runs without any errors then we can have a look what's going wrong using TexText. Thanks!

**Comment by E1onE2** [comment]
Hey, 

that works! So text in math mode with pdflatex and lualatex is working properly. 

C:\Users\qe85pumi\Desktop>pdflatex test.tex -interaction=nonstopmode -halt-on-error
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.10)
entering extended mode
(test.tex
LaTeX2e <2021-11-15>
L3 programming layer <2021-11-12>
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size10.clo)
)
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsmath.
sty
For additional information on amsmath, use the `?' option.

(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amstext.
sty
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsgen.s
ty))
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsbsy.s
ty)
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsmath\amsopn.s
ty))
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amscls\amsthm.st
y)
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsfonts\amssymb
.sty
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsfonts\amsfont
s.sty))
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics\color.s
ty
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics-cfg\col
or.cfg)
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/graphics-def\pdf
tex.def))
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/l3backend\l3back
end-pdftex.def)
No file test.aux.

(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/context/base/mkii\supp
-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsfonts\umsa.fd
)
(C:\Users\qe85pumi\AppData\Local\Programs\MiKTeX 2.9\tex/latex/amsfonts\umsb.fd
) [1{C:/Users/qe85pumi/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
(test.aux) )<C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.9/fonts/type1/pu
blic/amsfonts/cm/cmmi10.pfb><C:/Users/qe85pumi/AppData/Local/Programs/MiKTeX 2.
9/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 18241 bytes).
Transcript written on test.log.

After that the extension is also working fine.  I don't know why and when the error occurs.
