### ISSUE TITLE
macOS (Big Sur): Textext crashes when I type in the "^" character

### ISSUE THREAD

**Issue by eliedl** [textext/textext#328]
Hi all ! As I say in the title, The Textext GUI crashes when I type in the "^" character. I use Inkscape 1.1 on macOS Big Sur with apple M1 processor. 

2021-11-22 09:35:43.408 Python[25562:337929] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff204a8083 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201e017c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2055cc82 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff2055ccae -[__NSCFString getCharacters:range:].cold.1 + 0
	4   CoreFoundation                      0x00007fff2040ab7c -[__NSCFString characterAtIndex:] + 95
	5   Tk                                  0x00007fff7024fb6c TkpInitKeymapInfo + 723
	6   Tk                                  0x00007fff702556e0 Tk_MacOSXSetupTkNotifier + 835
	7   Tcl                                 0x00007fff7014c242 Tcl_DoOneEvent + 305
	8   _tkinter.cpython-38-darwin.so       0x000000010a504faa _tkinter_tkapp_mainloop_impl + 234
	9   Python                              0x00000001085b6ae6 method_vectorcall_FASTCALL + 150
	10  Python                              0x00000001086695f7 _PyEval_EvalFrameDefault + 36935
	11  Python                              0x000000010866b93c _PyEval_EvalCodeWithName + 508
	12  Python                              0x00000001085b0446 _PyFunction_Vectorcall + 390
	13  Python                              0x00000001085b1e53 method_vectorcall + 131
	14  Python                              0x00000001086696e8 _PyEval_EvalFrameDefault + 37176
	15  Python                              0x000000010866b93c _PyEval_EvalCodeWithName + 508
	16  Python                              0x00000001085b0446 _PyFunction_Vectorcall + 390
	17  Python                              0x00000001086695f7 _PyEval_EvalFrameDefault + 36935
	18  Python                              0x000000010866b93c _PyEval_EvalCodeWithName + 508
	19  Python                              0x00000001085b0446 _PyFunction_Vectorcall + 390
	20  Python                              0x00000001086695f7 _PyEval_EvalFrameDefault + 36935
	21  Python                              0x000000010866b93c _PyEval_EvalCodeWithName + 508
	22  Python                              0x00000001085b0446 _PyFunction_Vectorcall + 390
	23  Python                              0x00000001086695f7 _PyEval_EvalFrameDefault + 36935
	24  Python                              0x000000010866b93c _PyEval_EvalCodeWithName + 508
	25  Python                              0x0000000108660520 PyEval_EvalCode + 48
	26  Python                              0x000000010873f8d0 PyRun_FileExFlags + 272
	27  Python                              0x000000010873ee0a PyRun_SimpleFileExFlags + 378
	28  Python                              0x0000000108745f6f pymain_run_file + 303
	29  Python                              0x00000001086bd97e Py_RunMain + 974
	30  Python                              0x0000000108745a63 pymain_main + 35
	31  Python                              0x0000000108745ac7 Py_BytesMain + 39
	32  libdyld.dylib                       0x00007fff20351621 start + 1
	33  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jcwinkler** [comment]
From the traceback I see that the TkInter user interface is shown, not the GTK3 interface which should be the standard.

- Did you install Inkscape and TexText using the [documentation](https://textext.github.io/textext/install/macos.html) ?
- What did the setup script of TexText says relating GTK3 and TkInter toolkit? 

Most likely you ran into this bug: https://www.python.org/download/mac/tcltk/

Unfortunately I do not have a Mac for testing. So maybe you manager to get your Python installation to work using the provided links?
