### ISSUE TITLE
TexText still does not work on M1 mac after many attempts

### ISSUE THREAD

**Issue by wanghaoming17** [textext/textext#329]
TexText version: 1.6.1
Inkscape version: 1.1.1
Operating system: M1 Mac

Hello, I have encountered some problems and hope to get your help:
When installing TexText on my m1 Mac, I encountered the same problem as the previous ones (https://github.com/textext/textext/issues/323):

```rosetta error: /var/db/oah/279281325309952_279281325309952/53848c5cecf504fb2f445e61637f5b110f790ed68267e7ff16f5d6a82b886a39/_gi.cpython-38-darwin.so.aot: unable to mmap __TEXT: 1```
————————————————
Follow the instructions in the link you responded to, in the preferences.xml file,
if i add the code:
`python-interpreter="/usr/bin/python2.7" />`
behind the` <group id="extensions"`
inkscape reported an error:

`Inkscape extensions require Python 3.6 or greater.`
————————————————
if i add the code:
`python-interpreter="/usr/bin/python3" />`
behind the` <group id="extensions"`
inkscape reported an error:

```Traceback (most recent call last):
  File "__main__.py", line 17, in <module>
    from textext.base import *
  File "/Users/wanghaoming/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/base.py", line 70, in <module>
    import inkex
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 17, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 33, in <module>
    from .elements import load_svg, BaseElement, ShapeElement, Group, Layer, Grid, \
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 9, in <module>
    from ._base import SVG_PARSER, load_svg, ShapeElement, BaseElement
  File "/Applications/Inksc
[textext.log](https://github.com/textext/textext/files/7618396/textext.log)
ape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module>
    from lxml import etree
ModuleNotFoundError: No module named'lxml'
```
————————————————
Although I have downloaded the lxml module by pip and pip3.

How should I deal with this situation? The log file is there:
[textext.log](https://github.com/textext/textext/files/7618447/textext.log)
thank you.

**Comment by jcwinkler** [comment]
@wanghaoming17 Please try to set the Python interpreter to `/Applications/Inkscape.app/Contents/Resources/bin/python3` instead of `/usr/bin/python3` in `preferences.xml`

Does this help?

**Comment by wanghaoming17** [comment]
Thanks for your reply. 

Does that mean add the code:
`python-interpreter="/Applications/Inkscape.app/Contents/Resources/bin/python3" />`
behind the `<group id="extensions"`?

After doing this, when I click extensions>Text>TexText, python exits unexpectedly and inkscape displays the error 
`rosetta error: /var/db/oah/279281325309952_279281325309952/79350291770a306420623e84262eec807d3efe7a2779ac55927ce6ead93d552e/_gi.win. __TEXT: 1`

When I click extensions>Manage Extensions, inkscape displays the error 
```Traceback (most recent call last):
   File "extension-manager-bootstrap.py", line 133, in <module>
     Bootstrap().run()
   File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
     self.save_raw(self.effect())
   File "extension-manager-bootstrap.py", line 78, in effect
     if self.install_fallback():
   File "extension-manager-bootstrap.py", line 96, in install_fallback
     from urllib3.exceptions import NewConnectionError
ModuleNotFoundError: No 
module named'urllib3'
```
The log file is here: [textext.log](https://github.com/textext/textext/files/7624722/textext.log)
The Details of python's unexpected exit is here:
[Details of python's unexpected exit.txt](https://github.com/textext/textext/files/7624881/Details.of.python.s.unexpected.exit.txt)

Thank you very much.

**Comment by jcwinkler** [comment]
I think you hit this [Inkscape issue](https://gitlab.com/inkscape/inkscape/-/issues/2500) on MAC.

The only way to fix this is to update the Python subsystem shipped with Inkscape on MAC. But I do not know how to do this exactly.

**Comment by jcwinkler** [comment]
Maybe user `@dehesselle` on gitlab can help you (in the issue referenced above).

**Comment by wanghaoming17** [comment]
My major is not computer science, and this solution is too complicated for me. But I found a temporary alternative , I put it here for reference: 

Use "LaTeXiT" to export the formula as an SVG file, and then insert it into inkscape. When you want to modify the formula, use "Mathpix" to convert the formula image into LaTeX code.

This is a bit cumbersome, but it is acceptable.

Finally, anyway, thank you for your reply, and hope that Inkscape and TexText will get better and better.

**Comment by jcwinkler** [comment]
@wanghaoming17 I fully understand. Inkscape on Mac and extensions is a pain. It is not only related to TexText. The Inkscape developer team is missing developers who are familiar with MacOS.
