### ISSUE TITLE
Error Message after "Save"

### ISSUE THREAD

**Issue by Somlex** [textext/textext#331]
**Description**
I get the following error-message after clicking the "Save" Button in the input window of TexText:

<details>
<summary>dialog output (if available):</summary>

```
<<< (__main__.py:12486): Gtk-WARNING **: 08:51:20.503: dlopen(@executable_path/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so, 0x0001): tried: '/Applications/Inkscape.app/Contents/Resources/lib/im-quartz.so' (no such file), '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/im-quartz.so' (no such file), '/Applications/Inkscape.app/Contents/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/../Resources/lib/gtk-3.0/3.0.0/immodules/im-quartz.so' (no such file), '/usr/lib/im-quartz.so' (no such file)

(__main__.py:12486): Gtk-WARNING **: 08:51:20.503: Loading IM context type 'quartz' failed
 >>> 
```
</details>

**System information**

- TexText version: 1.6.1
- Inkscape version: 1.1
- Operating system: [macOS Monterey 12.0.1]

Thank you in advance!
Best regards

Alex

**Comment by jcwinkler** [comment]
This is an error in Inkscape's extension sub system on Mac. It has been already reported several times (#238, #218, #250 and also occurs in other extensions like [Gradient Saver](https://inkscape.org/~raniaamina/%E2%98%85gradient-saver)). However, unfortunately, I do not have a solution for you. It is up to the Inkscape developers to provide a working system on Mac the extensions can rely on. They are in trouble with their Inkscape port, see [here](https://inkscape.org/news/2021/06/22/seeking-macos-dev-contributor-inkscape-project/). Personally, I do not have a Mac system available for further testing.

As a workaround you might open `asktext.py` and replace `gi` by `gix` in the code line `import gi`. This will force TexText to load the tkinter version of the GUI. But only if the tkinter system is properly set up in your Inkscape installation.
