### ISSUE TITLE
GUI Library, GTK3, and TkInter Issue on 2020 M1 MacBook

### ISSUE THREAD

**Issue by Daludot** [textext/textext#332]
**Description of the problem/ steps to reproduce**
TexText fails to launch on my Late 2020 Macbook Pro. I encountered some of the same errors other users experienced with M1 Macs and was able to overcome them by adding the python-interpreter path to preferences.xml and pip installing the lxml module. The error I have now seems to be caused by a failure to detect GUI Library. TexText is also not able to find GTK3 or TkInter, which I do not recall installing or being prompted to install. Is there anything I can do to get this working?

<details>
<summary>dialog output (if available):</summary>
```
[TexText][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '1.6.1' (md5sum = 2a46b2ff9e56a6090725b8f55f9142eb)
[TexText][DEBUG   ]: platform.system() = 'Darwin'
[TexText][DEBUG   ]: platform.release() = '21.2.0'
[TexText][DEBUG   ]: platform.version() = 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101'
[TexText][DEBUG   ]: platform.machine() = 'arm64'
[TexText][DEBUG   ]: platform.uname() = uname_result(system='Darwin', node='MacBook-Pro.local', release='21.2.0', version='Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101', machine='arm64')
[TexText][DEBUG   ]: platform.mac_ver() = ('12.1', ('', '', ''), 'arm64')
[TexText][DEBUG   ]: sys.executable = '/opt/homebrew/opt/python@3.9/bin/python3.9'
[TexText][DEBUG   ]: sys.version = '3.9.9 (main, Nov 21 2021, 03:16:13) \n[Clang 13.0.0 (clang-1300.0.29.3)]'
[TexText][DEBUG   ]: os.environ = environ({'USER': 'danieldotson', '__CFBundleIdentifier': 'org.inkscape.Inkscape', 'COMMAND_MODE': 'unix2003', 'DISPLAY': '/private/tmp/com.apple.launchd.go2XgNbOuq/org.macosforge.xquartz:0', 'LOGNAME': 'danieldotson', 'PATH': '/Applications/Inkscape.app/Contents/MacOS:/Applications/Inkscape.app/Contents/Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.Z7xwRiRuOu/Listeners', 'SHELL': '/bin/bash', 'HOME': '/Users/danieldotson', '__CF_USER_TEXT_ENCODING': '0x1F6:0x0:0x0', 'TMPDIR': '/var/folders/y1/n4zyh4jx0ddgyznx8xqbz1800000gp/T/', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'XDG_DATA_HOME': '/Users/danieldotson/Library/Application Support/org.inkscape.Inkscape/share', 'XDG_DATA_DIRS': '/Applications/Inkscape.app/Contents/Resources/share:/Applications/Inkscape.app/Contents/Resources/share/inkscape', 'XDG_CONFIG_HOME': '/Users/danieldotson/Library/Application Support/org.inkscape.Inkscape/config', 'XDG_CONFIG_DIRS': '/Applications/Inkscape.app/Contents/Resources/etc/xdg', 'XDG_CACHE_HOME': '/Users/danieldotson/Library/Application Support/org.inkscape.Inkscape/cache', 'GTK_EXE_PREFIX': '/Applications/Inkscape.app/Contents/Resources', 'GTK_DATA_PREFIX': '/Applications/Inkscape.app/Contents/Resources', 'GDK_PIXBUF_MODULE_FILE': '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache', 'FONTCONFIG_PATH': '/Applications/Inkscape.app/Contents/Resources/etc/fonts', 'GIO_MODULE_DIR': '/Applications/Inkscape.app/Contents/Resources/lib/gio/modules', 'GI_TYPELIB_PATH': '/Applications/Inkscape.app/Contents/Resources/lib/girepository-1.0', 'DYLD_LIBRARY_PATH': '/Applications/Inkscape.app/Contents/Resources/lib:/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders', 'PYTHONPATH': '/Users/danieldotson/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated-simple', 'PYTHONIOENCODING': 'UTF-8', 'INKSCAPE_PROFILE_DIR': '/Users/danieldotson/Library/Application Support/org.inkscape.Inkscape/config/inkscape', 'DOCUMENT_PATH': '/Users/danieldotson/Downloads/wasd-inkscape-104-04.20.2021.svg', '__KMP_REGISTERED_LIB_30305': '0x11144f268-cafeac10-libomp.dylib', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKEX_GETTEXT_DIRECTORY': '/Applications/Inkscape.app/Contents/Resources/share/locale', 'LC_CTYPE': 'UTF-8'})
[TexText][INFO    ]: Using `pdflatex-executable` = `/Library/TeX/texbin/pdflatex`
[TexText][CRITICAL]: + [Fail] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/Library/TeX/texbin/pdflatex`
[TexText][INFO    ]: |     /--or-* [Fail] `lualatex` is NOT found in PATH
[TexText][INFO    ]: |     |      Please follow installation instructions at 
[TexText][INFO    ]: |     |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][INFO    ]: |     |      If lualatex is installed in custom location, specify it via 
[TexText][INFO    ]: |     |             --lualatex-executable=<path-to-lualatex>
[TexText][INFO    ]: |     |      and run setup.py again
[TexText][INFO    ]: |     /--or-* [Fail] `xelatex` is NOT found in PATH
[TexText][INFO    ]: |            Please follow installation instructions at 
[TexText][INFO    ]: |                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][INFO    ]: |            If xelatex is installed in custom location, specify it via 
[TexText][INFO    ]: |                   --xelatex-executable=<path-to-xelatex>
[TexText][INFO    ]: |            and run setup.py again
[TexText][CRITICAL]: /-and-+ [Fail] Detect GUI library
[TexText][CRITICAL]:        Please follow installation instructions at 
[TexText][CRITICAL]:               [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gui-library[0m
[TexText][CRITICAL]:       /--or-* [Fail] GTK3 is not found
[TexText][CRITICAL]:       |      Please follow installation instructions at 
[TexText][CRITICAL]:       |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gtk3[0m
[TexText][CRITICAL]:       /--or-* [Fail] TkInter is not found
[TexText][CRITICAL]:              Please follow installation instructions at 
[TexText][CRITICAL]:                     [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-tkinter[0m
[TexText][ERROR   ]: TexText requirements are not met. Please follow instructions https://textext.github.io/textext/
```
</details>

**Logfile**
[textext.log](https://github.com/textext/textext/files/7738563/textext.log)

**System information**
- TexText version: 1.6.1
- Inkscape version: 1.1.1
- Operating system: MacOS Monterey v12.1

**Comment by jcwinkler** [comment]
Hi @Daludot From the log I conclude that your Inkscape installation uses the Python interpreter `/opt/homebrew/opt/python@3.9/bin/python3.9`. Furthermore, the Python path is setup correctly. 

What you need to do now is to install the tkinter library in the Homebrew Python 3.9 installation. This will enable TexText to launch its basic tkinter gui. I do not have a Mac so I can only guess (see [here...](https://formulae.brew.sh/formula/python-tk@3.9)):

```bash
brew install python-tk@3.9
```

You can check if this has been successful by launching the above mentioned Python interpreter and enter

```python
import Tkinter
```

this shouldn't throw an error. Then you can test it in Inkscape.

If TexText successfully launches with the tkinter gui we can try to enable the more powerful gtk3 gui. But it has more dependencies so try tkinter first, please.

**Comment by Daludot** [comment]
Looks like its working perfectly now. Thanks!

**Comment by jcwinkler** [comment]
Good to hear that!

It would be very helpful for me and others if you could sketch all steps you did to get the stuff working. For example:

1. Install Inkscape via...
2. Install Python via..
3. Setting ,.. in the xml file

etc. etc.

I will update the documentation accordingly.

Thanks!

**Comment by Daludot** [comment]
Install Inkscape:
1. Download Inkscape installer from the inkscape.org website.
2. Run installer (.dmg file).

Install Python:
I think I installed Python as a dependency while installing some other software with Homebrew. I don't remember what software it was that had this Python dependency.

Install Latex:
I think I just downloaded and ran the MacTex pkg file off of the MacTex website a long time ago. This distribution includes pdflatex.

At some point I also installed pdf2svg with Homebrew. This enables svg export in LaTeXiT, which also came with MacTex. I don't know if this is relevant to TexText but I figured I would include it here just in case.

Installing TexText and Getting It to Work:
1. Download TexText zip off of GitHub.
2. Unzip TexText
3. Navigate to unzipped folder in terminal and run: 
`python3 setup.py --pdflatex-executable=$(which pdflatex) --skip-requirements-check`
4. Get path of python installation by running in terminal:
`which python3`
5. Navigate to preferences.xml file. Mine was at the following path.
`/Users/<user>/Library/Application Support/org.inkscape.Inkscape/config/inkscape`
6. In preferences.xml, add the following line under the line that syas id="extensions":
`python-interpreter="<python path>"`
7. pip install the lxml module for python. I did not have pip so I had to install pip too.
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python3 get-pip.py`
`pip install lxml`
8. Install TkInter by running the following command in terminal:
`brew install python-tk@3.9`

There may be a couple other dependencies along the way that I am forgetting here, but this covers all the major ones. Anything else was either installed automatically or clearly prompted after a failed run in terminal.
