### ISSUE TITLE
Gtk-Message: 17:38:19.469: Failed to load module "gtk-vector-screenshot" with AppImage

### ISSUE THREAD

**Issue by A3EKV** [textext/textext#336]
Hello I am using the dev version: `Inkscape 1.2-dev (c4f5fa2, 2021-12-17)` (The AppImage on Ubuntu 20.04).

When I open the extension and write an equation then press Save I get the following message:

```
Gtk-Message: 17:38:19.469: Failed to load module "gtk-vector-screenshot"
```

![image](https://user-images.githubusercontent.com/90999345/147365307-5893183a-822f-4dde-b43a-1f78ef323666.png)

**Comment by jcwinkler** [comment]
I strongly recommend to use Inkscape 1.1 together with TexText as described in the [documentation](https://textext.github.io/textext/install/linux.html).

Inkscape as AppImage has several drawbacks and issues and also the behavior of the  API changed in 1.2-dev. Please use Inkscape via apt-get.

**Comment by A3EKV** [comment]
Hi,
I am using the dev version to help in Inkscape testing. So I thought it would be useful to report this now so it gets fixed before the final release (April/may 2022). You can also open an issue on Inkscape : https://gitlab.com/inkscape/inkscape/-/issues

As an example, please take a look at this issue: https://gitlab.com/inkscape/inkscape/-/issues/3019

It will get fixed soon.

**Comment by A3EKV** [comment]
Issue reported here:  https://gitlab.com/inkscape/inbox/-/issues/6024

AppImages exist for a reason.

**Comment by jcwinkler** [comment]
Hi @A3EKV I did not realize that you are involved in Inkscape testing, hence my suggestion using `apt-get`. Anyway, thank you for discovering the issue and open the issue on gitlab.

Currently I am adapting TexText to Inkscape 1.2 but I use self compiled Inkscape on Linux as well as on Windows. In App Images you never know if errors result from the program you are testing itself or from errors in the AppImage building process, That's why I am not a fan of AppImages. But I know that they have their advantages when they are properly built.

**Comment by A3EKV** [comment]
Hi, thank you for your reply.

As you can see, we got some discussion over there on gitlab, and it was accepted and is moved to the main issue tracker.: https://gitlab.com/inkscape/inkscape/-/issues/3029

Just a side note: Probably, you don't need to build yourself inkscape, you can of course download the latest pre-built versions from pipelines: https://gitlab.com/inkscape/inkscape/-/pipelines (AppImages, Linux build, Windows, MacOS, etc.)

**Comment by jcwinkler** [comment]
> Probably, you don't need to build yourself inkscape, you can of course download the latest pre-built versions from pipelines: https://gitlab.com/inkscape/inkscape/-/pipelines

Ah, I did not know this. This is nice. Thank you!
