### ISSUE TITLE
Inkscape 1.2-dev: New nodes are not placed in the center of the view

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#338]
**Description of the problem/ steps to reproduce**
When running TexText in the **development** version of Inkscape **1.2** together with the Inkscape extension system from the extension **master** branch new nodes are not placed in the center of the view. Instead, they are placed far away from the current view (usually bottom right, you need to zoom out to find it).

**Screenshot**
The node has been created while the A4 pager was filling the view completely (Shortcut `5`). It should have been placed in the center of the page. In the screenshot it became visible after zooming out to 28%
![grafik](https://user-images.githubusercontent.com/11866252/147471592-0e2d66b6-48bb-4c12-b6aa-6ff542d6dec8.png)

**System information**

- TexText version: At least >= 1.6.0
- Inkscape version: Inkscape 1.2-dev (0677221, 2021-12-22)
- Operating system: all

**Comment by jcwinkler** [comment]
The same happens with the Inkscape built-in pdflatex extension (Render/Mathematics). I will investigate this and if necessary open an issue in the Inkscape extensions repo.

**Comment by s1291** [comment]
You need probably to check the documentation: https://inkscape.gitlab.io/extensions/documentation/units.html

**Comment by jcwinkler** [comment]
Thanks @s1291 I read this documentation and I am currently discussing in the chat some misunderstandings I have.

Anyway, I boiled down the problem to the following diference between Inkscape 1.1 and Inkscape 1.2.

Given a document with `inkscape:document-units="mm"` one has
- `self.svg.namedview.center` returns 
   - Inkscape 1.1: values in **mm**
   - Inkscape 1.2: values in **px**
- `self.svg.unittouu("1mm")`returns 
   - Inkscape 1.1: **1.0** (independently of what is set in  `inkscape:document-units`!)
   - Inkscape 1.2: **3.779** (independently of what is set in  `inkscape:document-units`!)
- The translation values in the transform attribute in both Inkscape versions are interpreted in what is specified in `inkscape:document-units`. Hence, composing the `transform` from values obtained from things like `self.svg.namedview.center` etc. will place the snippet elsewhere, but not in the center of the view. We have to consider this in a release of TexText that is fully compatible with Inkscape 1.2.

**Comment by s1291** [comment]
Hi
To quote from the Inkscape [wiki](https://wiki.inkscape.org/wiki/Units_In_Inkscape):

> Units are not as straightforward as one should think they are.
