### ISSUE TITLE
Unexpected message everytime textext windows is closed.

### ISSUE THREAD

**Issue by noone-g** [textext/textext#344]
**Before submitting a bug report make sure you have checked the
  [FAQ](https://textext.github.io/textext/usage/faq.html) and
  [Troubleshooting](https://textext.github.io/textext/usage/troubleshooting.html)
  sections in the documentation!**

**Description of the problem/ steps to reproduce**
A clear and concise description of what the bug is and what you expected to happen.

**Steps to reproduce the behavior (if not obvious from description)**:
As the title suggests, everytime the textext windows is closed, Inkscape show the window.

```
(__main__.py:10688): GLib-GIO-WARNING **: 22:36:25.886: Unexpectedly, UWP app `microsoft.windowscommunicationsapps_16005.14326.20544.0_x64__8wekyb3d8bbwe' (AUMId `microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail') supports 1 extensions but has no verbs
```

**System information**

- TexText version: 1.8
- Inkscape version: 1.1
- Operating system: Windows 10 19044 64-bit
- Windows only: MiKTeX
- Windows only: TexText installed via batch script

**Comment by noone-g** [comment]
1.  I run Inkscape portable version at two machines (Intel laptop and AMD desktop)
Laptop is ok but desktop shows this behavior.
  2.  Yes, the same window pop up!!

For the test, I turned off all the firewall.
Can you guess why?

Thanks~!


________________________________

**Comment by jcwinkler** [comment]
That this error occurs also with the extension manager (and possibly with other extensions using a user defined gui) makes me assuming that this is a problem with the extension API.

I guess you already removed Inkscape from PA and also removeed all configurations stored by it and then re-installed Inkscape + TexText?

>For the test, I turned off all the firewall.
>Can you guess why?

You mean the test with the extension manager? As far as I do know the extension manager contacts some Inkscape servers in order to be able to load extensions from their website. There is some discussion about this in the Inkscape developer chat regarding privacy concerns.

**Comment by noone-g** [comment]
That’s right.

I installed and reinstalled for both PA and MS store version.
I also turned off firewall during the test.

Interestingly, the error message includes not only the windows mail but also the windows calendar too.
This only happens for PD not for LAPTOP.

It’s not hurting any function. Just annoying.

Thanks for the reply.
You can close the ticket.

Best!

**Comment by jcwinkler** [comment]
@noone-g If this error occurs in the extensions manager you might want to open an issue at https://gitlab.com/inkscape/extensions . Refer to the extension manager only so the Inkscape developers take it serious.

**Comment by Jafanovic** [comment]
I have similar message when using TexText. The preview works well. The Latex math is inserted to the Inkscape. But following message is reported for every time. 

(__main__.py:27652): GLib-GIO-WARNING **: 20:45:34.494: Unexpectedly, UWP app `XBMCFoundation.Kodi_19.4.500.0_x64__4n2hpmxwrvr6p' (AUMId `XBMCFoundation.Kodi_4n2hpmxwrvr6p!Kodi') supports 120 extensions but has no verbs

**Comment by jcwinkler** [comment]
Please try to open the Inkscape extension manager and close it. Is the same message shown?
