### ISSUE TITLE
 Undefined control sequence.  \documentclass{article}

### ISSUE THREAD

**Issue by songlin** [textext/textext#345]
Hi , 

inkscape version: 1.0.2 on ubuntu20
plugin version: 1.8.0

installation method:
```
python3 setup.py --pdflatex-executable /usr/local/texlive/2021/bin/x86_64-linux/pdflatex
```

after open textext, i got following error:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./tmp.tex
! Undefined control sequence.
l.2     \documentclass
                      {article}
? 
! Emergency stop.
l.2     \documentclass
                      {article}
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on tmp.log.
```

It looks like the plugin still runs pdftex instead of pdflatex

**Comment by jcwinkler** [comment]
Hi @songlin Thanks for the report. Please note that the term `This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021)` is also printed by pdflatex. So there is no reason to assume that textext calls outdated `tex` compiler.

If TexText is installed without any arguments in `setup.py`, it just uses the command `pdflatex`. If `pdflatex` is in the path, compilation works. If not, it fails. In that case you need to explicitely specify the path as you did it.

Please do me a favour and do the following:

1. Remove TexText:
    ```bash
     rm -rf ~/.config/inkscape/extensions/textext
     ```
2. Download the previous version **1.7.1** of TexText and install it.

Does the error still occur? (We changed something in the handling of the preamble file from 1.7.1 -> 1.8.0, so I want to check this) Thanks!

**Comment by songlin** [comment]
@jcwinkler 

Thanks for looking at this issue.  The same error still exists.

**Comment by jcwinkler** [comment]
Hmm, this is strange. Could you please try the steps 1 to 4 in the manual toolchain as explained in the [documentation](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain)? For the call of pdflatex please use exactly the path to pdflatex you passed to setup.py.

**Comment by songlin** [comment]
Sorry for the late reply, here is the content of my `.cache.json`

```
{
  "requirements_checker": {
    "inkscape_executable": "/usr/bin/inkscape",
    "available_tex_to_pdf_converters": {
      "pdflatex": "/usr/local/texlive/2021/bin/x86_64-linux/pdftex"
    },
    "available_pdf_to_svg_converters": {}
  },
  "previous_exit_code": 0
}
```

After i deleted this file, i run TexText again, i encounters another error:

```

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at https://inkscape.org/report
with a detailed description of the steps leading to the crash, so we can fix it.
** Message: 16:04:47.022: Error: Inkscape encountered an internal error and will close now.
```
at the same time, inkscape crashed.

**Comment by songlin** [comment]
and the cache file becomes:

```
{
  "requirements_checker": {
    "inkscape_executable": "/usr/bin/inkscape",
    "available_tex_to_pdf_converters": {
      "pdflatex": "/usr/local/texlive/2021/bin/x86_64-linux/pdflatex",
      "lualatex": "/usr/local/texlive/2021/bin/x86_64-linux/lualatex",
      "xelatex": "/usr/local/texlive/2021/bin/x86_64-linux/xelatex"
    },
    "available_pdf_to_svg_converters": {}
  },
  "previous_exit_code": 0
}
```

Thanks.

**Comment by songlin** [comment]
I now follow the instruction [here](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain).

It fails at step 5. I can't convert pdf to svg with inkscape.

```
inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf


Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at https://inkscape.org/report
with a detailed description of the steps leading to the crash, so we can fix it.
** Message: 16:10:46.307: Error: Inkscape encountered an internal error and will close now.

[1]    16706 segmentation fault (core dumped)  inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path  
```

Does this helps?

**Comment by songlin** [comment]
Hi @jcwinkler, i reinstalled inkscape with apt-get, it turns out to be version 0.92.x, then I installed `textext-0.11.1`, it works now.
I am totally happy with this and do not bother to upgrade to 1.1+ version. Thanks.
