### ISSUE TITLE
Bug in inkscape

### ISSUE THREAD

**Issue by adomps** [textext/textext#348]
Hello
I have installed textext 1.8.1 to work with Inkscape 1.1.2 under Ubuntu Mate 1.24.
The installation process seemed successfull, but I am in trouble when using 
the extension. When I click on Extension --> Textext, Inkscape delivers the
following error message :
  File "textext.py", line 122
    filtered_messages = filter(lambda (m, l): l != LOG_LEVEL_DEBUG, filtered_messages)
                                      
SyntaxError: invalid syntax

Does anyone know how to fix this ?

Thank you very much,
Andre DOMPS

**Comment by jcwinkler** [comment]
The file `textext.py` is not part of current TexText. Most likely some outdated files exist in your local extension system.

Please do the following:

1. Make a backup of your inkscape configuration: `mv ~/.config/inkscape ~/.config/inkscape.backup`
2. Launch Inkscape and close it.
3. Re-install TexText.
4. Launch Inkscape again. TexText can be launched from Extensions - Text submenu.

Does this work?
