### ISSUE TITLE
Run TexText GUI failed

### ISSUE THREAD

**Issue by giofrnc** [textext/textext#349]
**Description of the problem/ steps to reproduce**
The GUITK3 and TkInter are both found during the installation and in the initial DEBUG running mode but there is a persisting error at the GUI.

**Message(s) in error dialog (if this comes up)**
[TexText][DEBUG   ]:   Run TexText GUI failed
[TexText][DEBUG   ]: TexText.effect failed
[TexText][ERROR   ]: could not get a reference to type class
[TexText][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\giova\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 24, in <module>
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Users\giova\AppData\Roaming\inkscape\extensions\textext\base.py", line 274, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "C:\Users\giova\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1270, in ask
    window = self.create_window()
  File "C:\Users\giova\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1106, in create_window
    text_buffer = GtkSource.Buffer()
TypeError: could not get a reference to type class

[textext.log](https://github.com/textext/textext/files/8375547/textext.log)

**System information**

- TexText version: 1.8.1
- Inkscape version: 1.1.2
- Operating system: Windows 10, 64-bit
- Windows only: LaTeX-distribution MiKTeX
- Windows only: TexText installed via batch script or installer file: Both methods reproduced the same error

**Comment by giofrnc** [comment]
Hi Jan, 
I followed your instructions without success, but then proceeded to also uninstall Miktex and use TeX Live as my LaTex distributor and now it works! There seems to be a bug on my Miktex version that I hadn't encountered up to now.

Thanks,
gio

**Comment by jcwinkler** [comment]
Hmm, this is strange since the error shouldn't be related to the TeX installation. But anyway, who knows the strange dependencies of operating systems.... Good to know that it works now.
