### ISSUE TITLE
ArchLinux + Python 3.10: DynamicImporter... not found. Error

### ISSUE THREAD

**Issue by pezr** [textext/textext#350]
Inkscape 1.1 fresh install and 
TexText 1.8.1 fresh install via setup.py script (all TexText requirements OK, except TkInter)
on Archlinux with python 3.10.2 and python-gobject 3.42.0-3 [installed]
When I try to use the TexText extension I get the next message:

\<frozen importlib._bootstrap\>:914: ImportWarning: DynamicImporter.find_spec() not found; falling back to find_module()
\<frozen importlib._bootstrap\>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
\<frozen importlib._bootstrap\>:914: ImportWarning: DynamicImporter.find_spec() not found; falling back to find_module()
\<frozen importlib._bootstrap\>:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

any help, please
thanks in advance

**Comment by jcwinkler** [comment]
@pezr Could you please try to open the Inkscape extension manager (Menu `Extensions` and there at the very bottom `Manage Extensions`). Does it open or do similar messages come up?

**Comment by medwatt** [comment]
I am experiencing the same issue. I'm also on arch linux and running python 3.10.

![image](https://i.imgur.com/rVo8nl8.png)

**Comment by medwatt** [comment]
> @pezr Could you please try to open the Inkscape extension manager (Menu `Extensions` and there at the very bottom `Manage Extensions`). Does it open or do similar messages come up?

Here's a short recording answering your question.

https://user-images.githubusercontent.com/17733465/161048732-4115b863-12c0-4ecc-b072-ba4fd6a7bf1d.mp4

**Comment by jcwinkler** [comment]
@medwatt So when you close the extension manager the error message is thrown as well, correct?

**Comment by jcwinkler** [comment]
OK, this clearly indicates a bug or imcompatibility in the Inkscape extension subsystem, not in TexText. I recommend to file a bug report (relating the error message of the extension manager only!) at https://gitlab.com/inkscape/extensions

**Comment by jcwinkler** [comment]
Maybe a workaround: Are you able to downgrade to Python 3.9.12.

**Comment by jcwinkler** [comment]
Yes, you have to specify the path to the alternative interpreter as described here:

https://textext.github.io/textext/textext_0x/usage/faq.html#set-inkscape-python-interpreter-to-python2

**Comment by jcwinkler** [comment]
And you may need to install some additional packages like `lxml`, `numpy` in your conda installation, etc. (Trial and error)

**Comment by medwatt** [comment]
So, I should use a python environment with python 2? Not python 3?

**Comment by jcwinkler** [comment]
No, you need to replace the python 2 stuff written in the documentation by the correct executable paths of your conda environment.

**Comment by medwatt** [comment]
I did that, but there seems to be a massive list of dependencies to install. It tells me to install a module called "gi". I can't seem to find this module.

**Comment by jcwinkler** [comment]
I guess you need to install `pygobject` in your conda environment. This should pull the gi bindings.

**Comment by pezr** [comment]
> @medwatt So when you close the extension manager the error message is thrown as well, correct?

Sorry for late response. I confirm the same issue with the extension manager, as @medwatt.
I'll report the issue at inkscape's repo. 

Greetings

**Comment by gncs** [comment]
I am encountering the same issue. Is there any fix for this yet? Thank you :)

**Comment by jcwinkler** [comment]
Hi @gncs Sorry for the late reply. I have no Arch system available, so could you please create a file named `test.py` with the following content:

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World!")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

Then execute it from a terminal by `python test.py` (or `python3 test.py`)

Are you able to successfully execute it from the command line without any error messages? An empty window should be shown with the title "Hello World!",

**Comment by gncs** [comment]
Yes, that works without any problems.

I reported the issue on GitLab as well: https://gitlab.com/inkscape/inkscape/-/issues/3577

**Comment by jcwinkler** [comment]
Thanks! Now, please perform two additional tests:

**Test 1**
Modify the scripts mentioned above and try again:

```python
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
from gi.repository import Gdk, GdkPixbuf

try:

    gi.require_version('GtkSource', '3.0')
    from gi.repository import GtkSource

    print("GTKSOURCEVIEW installed!")
except (ImportError, TypeError, ValueError) as _:
    print("GTKSOURCEVIEW not installed!")


window = Gtk.Window(title="Hello World!")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

**Test 2**

1. Open Inkscape and save an empty svg document `empty.svg`into your home folder.
2. Close Inkscape
3. Navigate into the directory where TexText resides. Usually this should by `~/.config/inkscape/extensions/textext`
4. Execute the command
    ```
    export PYTHONPATH="`inkscape --system-data-directory`/extensions:$HOME/.config/inkscape/extensions/"
    ```
5. Execute the command: `python __main__.py ~/empty.svg`

*Remarks* Step 4 temporarily adds the Python extension system to the Pythonpath, Step 5 should open the TexText gui. Maybe you need to use `python3` instead of `python` and modify `$HOME/.config/inkscape/extensions/` if TexText is installed elsewhere (which shouldn't be the case).

Does the TexText gui comes up?
