### ISSUE TITLE
Error when generating tmp.svg (KDE Neon only (?))

### ISSUE THREAD

**Issue by Marcel-Mueck** [textext/textext#351]
**Description of the problem/ steps to reproduce**
g-file-error-quark: Failed to open file “tmp.png”: No such file or directory (4) appears when I click on "Save" or "Preview"

**Steps to reproduce the behavior (if not obvious from description)**:
1.open Inkscape
2. Open TexText in Inkscape
3. write anything in the text field

**Message(s) in error dialog (if this comes up)**
g-file-error-quark: Failed to open file “tmp.png”: No such file or directory (4)

**Logfile**
Please also *attach* the TexText log file. You find it at the following locations:

[textext.log](https://github.com/textext/textext/files/8419870/textext.log)

**Screenshots**
![bild](https://user-images.githubusercontent.com/23211603/161795760-5d2a826b-b076-47ad-bc79-c48c37f7aec4.png)

**System information**

- TexText version:1.8.1
- Inkscape version: 1.1.2
- Operating system: KDE neon 5.24
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)

**Comment by jcwinkler** [comment]
Thanks for the report @Marcel-Mueck The error is very strange. According to the logfile it seems that an exception is thrown during processing of the latex snippet which is not caught properly by TexText. 

It would be very helpful if you could process the manual toolchain as described [here](https://textext.github.io/textext/usage/troubleshooting.html#manual-use-of-the-toolchain). Please use the content of `~/.config/inkscape/extensions/textext/default_packages.tex` as preamble in your test file.

Are you able to successfully process all steps of the manual toolchain? Thanks!

**Comment by Marcel-Mueck** [comment]
Hey, thank you for the quick response. I created a test.tex file in the texteext directory in the  ~/.config/Inkscape/extensions/textext, and added all packages from default packages as preamble. I used $f_{\lambda}$ as a test case in the document section, live preview with kile worked. pdflatex test.tex -interaction=nonstopmode -halt-on-error worked as expected with following log: 
[test.log](https://github.com/textext/textext/files/8425396/test.log)

---
inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf
**failed** with output: 
`PDFInput::open: error opening document: file:///home/elmolo/.config/inkscape/extensions/textext/test.pdf
/home/elmolo/.config/inkscape/extensions/textext/test.pdf:1: parser error : Start tag expected, '<' not found
%PDF-1.5
^
ink_file_open: '/home/elmolo/.config/inkscape/extensions/textext/test.pdf' cannot be opened!
InkscapeApplication::document_open: Failed to open: /home/elmolo/.config/inkscape/extensions/textext/test.pdf
ConcreteInkscapeApplication::on_open: failed to create document!`

I hope that this helps, and thank you.
Marcel Mück

**Comment by Marcel-Mueck** [comment]
I installed inkscape with apt by the way, if that bears any relevancy.

**Comment by jcwinkler** [comment]
Thanks for executing this test. The error message shows that the conversion of the pdf-document to a svg-snippet fails. This conversion is done by the Inkscape executable so we have an Inkscape issue here. 

If you open the generated pdf do you see a correctly rendered `$f_\lambda$?` If so, could you attach the pdf document please?

**Comment by Marcel-Mueck** [comment]
yeah, of course. The output is:
[test.pdf](https://github.com/textext/textext/files/8425570/test.pdf)

**Comment by Marcel-Mueck** [comment]
Inkscape is on version 1.1.2 and ghostscript is on version 9.50 by the way

**Comment by jcwinkler** [comment]
Hmm, I also use Inkscape 1.1.2 from apt together with TexLive 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) as you and the toolchain works perfectly...

Please find attached my pdf file. Are you able to convert it to svg using

```
inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test_jw.svg test_jw.pdf
```

[test_jw.pdf](https://github.com/textext/textext/files/8425730/test_jw.pdf)

**Comment by Marcel-Mueck** [comment]
Hey, when I try to convert your pdf, I get the same error message: 
`inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test_jw.svg test_jw.pdf
PDFInput::open: error opening document: file:///home/elmolo/H%C3%A4mtningar/test_jw.pdf
/home/elmolo/Hämtningar/test_jw.pdf:1: parser error : Start tag expected, '<' not found
%PDF-1.5
^
ink_file_open: '/home/elmolo/Hämtningar/test_jw.pdf' cannot be opened!
InkscapeApplication::document_open: Failed to open: /home/elmolo/Hämtningar/test_jw.pdf
ConcreteInkscapeApplication::on_open: failed to create document!
`

**Comment by jcwinkler** [comment]
Your pdf converts perfectly to svg on my machine. So we have different behaviour of the same inkscape installation. Maybe we have different cairo versions installed. What is the output of `apt list --installed | grep -E 'cairo|poppler'` on your machine?

Mine is:
```
libcairo-gobject2/focal,now 1.16.0-4ubuntu1 amd64  [Installiert,automatisch]
libcairo2/focal,now 1.16.0-4ubuntu1 amd64  [Installiert,automatisch]
libcairomm-1.0-1v5/focal,now 1.12.2-4build1 amd64  [Installiert,automatisch]
libpangocairo-1.0-0/focal,now 1.44.7-2ubuntu4 amd64  [Installiert,automatisch]
libpoppler-cpp0v5/focal,now 0.86.1-0ubuntu1 amd64  [Installiert,automatisch]
libpoppler-glib8/focal,now 0.86.1-0ubuntu1 amd64  [Installiert,automatisch]
libpoppler-qt5-1/focal,now 0.86.1-0ubuntu1 amd64  [Installiert,automatisch]
libpoppler97/focal,now 0.86.1-0ubuntu1 amd64  [Installiert,automatisch]
poppler-data/focal,focal,now 0.4.9-2 all  [installiert]
poppler-utils/focal,now 0.86.1-0ubuntu1 amd64  [Installiert,automatisch]
python3-cairo/focal,now 1.16.2-2ubuntu2 amd64  [Installiert,automatisch]
python3-gi-cairo/focal,now 3.36.0-1 amd64  [Installiert,automatisch]
```

**Comment by Marcel-Mueck** [comment]
mine is
`gir1.2-poppler-0.18/focal,now 22.04.0-1+20.04+focal+release+build4 amd64 [installerat,automatiskt]
libcairo-gobject2/focal,now 1.16.0-4ubuntu1 amd64 [installerat,automatiskt]
libcairo-script-interpreter2/focal,now 1.16.0-4ubuntu1 amd64 [installerat,automatiskt]
libcairo2-dev/focal,now 1.16.0-4ubuntu1 amd64 [installerat]
libcairo2/focal,now 1.16.0-4ubuntu1 amd64 [installerat,automatiskt]
libcairomm-1.0-1v5/focal,now 1.12.2-4build1 amd64 [installerat,automatiskt]
libpangocairo-1.0-0/focal,now 1.44.7-2ubuntu4 amd64 [installerat,automatiskt]
libpoppler-cpp0v5/focal,now 22.04.0-1+20.04+focal+release+build4 amd64 [installerat,automatiskt]
libpoppler-glib8/focal,now 22.04.0-1+20.04+focal+release+build4 amd64 [installerat,automatiskt]
libpoppler-qt5-1/focal,now 22.04.0-1+20.04+focal+release+build4 amd64 [installerat,automatiskt]
libpoppler119/focal,now 22.03.0-1+20.04+focal+release+build2 amd64 [installerat]
libpoppler120/focal,now 22.04.0-1+20.04+focal+release+build4 amd64 [installerat]
libpoppler97/focal,now 0.86.1-0ubuntu1 amd64 [installerat,automatiskt]
poppler-data/focal,focal,now 0.4.9-2 all [installerat,automatiskt]
poppler-utils/focal,now 22.04.0-1+20.04+focal+release+build4 amd64 [installerat,automatiskt]
python3-cairo/focal,now 1.16.2-2ubuntu2 amd64 [installerat,automatiskt]
python3-gi-cairo/focal,now 3.36.0-1 amd64 [installerat,automatiskt]

`

**Comment by jcwinkler** [comment]
Thanks. I need to contact the Inkscape developers to get a clue what's going on.

**Comment by jcwinkler** [comment]
Ah, could you please post the output of `inkscape --version`. Thanks again!

**Comment by Marcel-Mueck** [comment]
Here you go:
`Inkscape 1.1.2 (1:1.1+202202050950+0a00cf5339)
`
Thanks

**Comment by designbybeck** [comment]
On KDE Neon I get the above error about "tmp.svg"
This is installed from the ppa stable

Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d)

My friend tried on his KDE Neon as well and got the same thing. However on Manjaro it seem to work fine as expected

Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d)

    GLib version:     2.64.6
    GTK version:      3.24.20
    glibmm version:   2.64.2
    gtkmm version:    3.24.2
    libxml2 version:  2.9.10
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.44.7
    HarfBuzz version: 2.6.4

    OS version:       KDE neon User - 5.25

![2022-08-02_13-06](https://user-images.githubusercontent.com/4542852/182443997-fdc0e1ed-a327-4596-96a9-929330876f45.png)

**Comment by jcwinkler** [comment]
Did you try the manual toolchain as mentioned above in the thread? Did you also encounter the same error?

**Comment by designbybeck** [comment]
Hmm, not sure I did that correctly, but it didn't seem to work:

pdflatex test.tex -interaction=nonstopmode -halt-on-error
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amscls/amsthm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
<*> test.tex -
              interaction=nonstopmode -halt-on-error
? 


--------------------------------------------

This is what I had in my test.tex file:
`\documentclass{article}

\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}
`
Not sure if I understood those steps correctly.

**Comment by vlukes** [comment]
I confirm the same issue on my KDE Neon installation. Everything works well except for the PDF to SVG conversion.

```
inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename tmp.svg tmp.pdf
PDFInput::open: error opening document: file:///tmp/tmpj0u2kwcetextext_/tmp.pdf
/tmp/tmpj0u2kwcetextext_/tmp.pdf:1: parser error : Start tag expected, '<' not found
%PDF-1.5
^
ink_file_open: '/tmp/tmpj0u2kwcetextext_/tmp.pdf' cannot be opened!
InkscapeApplication::document_open: Failed to open: /tmp/tmpj0u2kwcetextext_/tmp.pdf
ConcreteInkscapeApplication::on_open: failed to create document!
```

Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d)

    GLib version:     2.64.6
    GTK version:      3.24.20
    glibmm version:   2.64.2
    gtkmm version:    3.24.2
    libxml2 version:  2.9.10
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.44.7
    HarfBuzz version: 2.6.4

    OS version:       KDE neon User - 5.25

**Comment by jcwinkler** [comment]
@vlukes, @designbybeck, @Marcel-Mueck I opened an issue in the Inkscape issue tracker. The problem is related to Inkscape, not to TexText. Since I do not have a KDE Neon distro for testing (and I am currently underway) maybe you could help in testing of corresponding requests given in that issue?
