### ISSUE TITLE
textext 1.8.1 could not start to work for inkscape 1.2 in Fedora 36

### ISSUE THREAD

**Issue by maoqiukun** [textext/textext#352]
**Description of the problem/ steps to reproduce**
textext 1.8.1 could not start to work for inkscape 1.2

**Steps to reproduce the behavior (if not obvious from description)**:
1. install inkscape 1.2 in Fedora 36
2. install textext 1.8.1
3. textext 1.8.1 could not start to work in inkscape 1.2

**Message(s) in error dialog (if this comes up)**
Traceback (most recent call last):
  File "/home/username/.config/inkscape/extensions/textext/__main__.py", line 17, in <module>
    from textext.base import *
  File "/home/username/.config/inkscape/extensions/textext/base.py", line 70, in <module>
    import inkex
  File "/usr/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/usr/share/inkscape/extensions/inkex/extensions.py", line 34, in <module>
    from .elements import (
  File "/usr/share/inkscape/extensions/inkex/elements/__init__.py", line 10, in <module>
    from ._base import ShapeElement, BaseElement
  File "/usr/share/inkscape/extensions/inkex/elements/_base.py", line 38, in <module>
    from ..styles import Style, Classes
  File "/usr/share/inkscape/extensions/inkex/styles.py", line 33, in <module>
    from .css import ConditionalRule
  File "/usr/share/inkscape/extensions/inkex/css.py", line 27, in <module>
    import cssselect
ModuleNotFoundError: No module named 'cssselect'

**Logfile**
no log file generated, since it could not start

**Screenshots**
![Screenshot 2022-05-20 at 12 57 08](https://user-images.githubusercontent.com/105920815/169514133-142355b4-0650-40b6-8313-aecb408a09da.jpg)
![Screenshot 2022-05-20 at 12 57 13](https://user-images.githubusercontent.com/105920815/169514154-92ec04fc-812b-4ea1-a994-11c745c0ba24.jpg)

**System information**

- TexText version: 1.8.1
- Inkscape version: 1.2
- Operating system: Fedora 36 (in Parallels Desktop on a macOS)

**Comment by jcwinkler** [comment]
According to the error message the `inkex`-Module tries to load `cssselect` but fails. The `inkex`-Module is part of Inkscape's extension system. Hence, this error is related to Inkscape and not to TexText. I guess it is a packaging issue of Inkscape on Fedora.

You can install it in your Python distribution manually via `sudo pip install cssselect` (or maybe `sudo pip3 install cssselect`). But maybe other packages are missing, too, 

You could also open an issue on the [Inkscape developer site](https://gitlab.com/inkscape/inkscape). There are already two issues related to this one: [Here](https://gitlab.com/inkscape/inkscape/-/issues/2473) and [here](https://gitlab.com/inkscape/inkscape/-/issues/2886).

**Comment by maoqiukun** [comment]
> According to the error message the `inkex`-Module tries to load `cssselect` but fails. The `inkex`-Module is part of Inkscape's extension system. Hence, this error is related to Inkscape and not to TexText. I guess it is a packaging issue of Inkscape on Fedora.
> 
> You can install it in your Python distribution manually via `sudo pip install cssselect` (or maybe `sudo pip3 install cssselect`). But maybe other packages are missing, too,
> 
> You could also open an issue on the [Inkscape developer site](https://gitlab.com/inkscape/inkscape). There are already two issues related to this one: [Here](https://gitlab.com/inkscape/inkscape/-/issues/2473) and [here](https://gitlab.com/inkscape/inkscape/-/issues/2886).

@jcwinkler Thank you for your quick reply! Installing `cssselect` solves the issue perfectly. I will open an issue about this on [Inkscape developer site](https://gitlab.com/inkscape/inkscape).
