### ISSUE TITLE
An error message when closing textext window

### ISSUE THREAD

**Issue by maoqiukun** [textext/textext#353]
**Description of the problem/ steps to reproduce**

An error message always pops up when closing TexText window by clicking 'Save' or 'Cancel' button, or simply close 'x' icon on the top right corner; while it does not affect TexText's functioning.

**Message(s) in error dialog (if this comes up)**

< frozen importlib._bootstrap >:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()
< frozen importlib._bootstrap >:671: ImportWarning: DynamicImporter.exec_module() not found; falling back to load_module()

**Logfile**

Logfile does not record any errors.

**Screenshots**

![Screenshot 2022-05-21 at 14 24 07](https://user-images.githubusercontent.com/105920815/169651673-71d1f9ec-6c0f-4c6b-9a80-276f877964af.jpg)
![Screenshot 2022-05-21 at 14 24 28](https://user-images.githubusercontent.com/105920815/169651678-742c9021-6439-44d6-b37a-764e32cdc524.jpg)
![Screenshot 2022-05-21 at 14 24 40](https://user-images.githubusercontent.com/105920815/169651680-5a02b7b6-8d37-4f09-8f88-c39a218770f6.jpg)

**System information**

- TexText version: 1.8.1
- Inkscape version: 1.2
- Operating system: Fedora 36

**Comment by jcwinkler** [comment]
Hi @maoqiukun This again looks like an error in Inkscape's extension system on Fedora or the packaging of Inkscape (see #352) 

Does this error also occur when you open "Extensions" - "Manage Extensions" (at the very bottom of the Extensions menu)?
