### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by chrismiller3245** [textext/textext#360]
Hello,

I've tried installing the Texttext extension (1.8.1) with Inkskape (1.2), however I've encountered the issue that is shown in the attached image. I am no expert at programming and could not find the issue discussed elsewhere, so any help you could provide would be greatly appreciated.

![TextText_issue](https://user-images.githubusercontent.com/109816219/180482443-380c7eb4-6f1e-4e1a-a195-43b706bee34f.jpg)

Thank you in advance!

**Comment by jcwinkler** [comment]
This error results not from TexText but from the Extension Manager. I suggest to install TexText manually via the setup script as discribed in the [documentation](https://textext.github.io/textext/install/windows.html).

Please report if you succeeded or need additional help!

**Comment by chrismiller3245** [comment]
Silly oversight on my part. Successfully installed. Thanks for taking the time to respond.
