### ISSUE TITLE
--pdflatex-executable=$(which pdflatex)

### ISSUE THREAD

**Issue by ffgg11** [textext/textext#364]
what is the argument 'pdflatex-executable'? I can't run the file setup.py.

**Comment by jcwinkler** [comment]
Usually, it is sufficient to run the setup without any arguments: `python setup.py`. 

The `pdflatex-executable` argument is only required if the `pdflatex` command is not in the system path. If this is the case you need to call setup as follows (assuming pdflatex is in /opt/latex/bin):

``` bash
python setup.py --pdflatex-executable /opt/latex/bin/pdflatex
```
