### ISSUE TITLE
Mac: Inkscape bugging while opening a file [After TexText installation]

### ISSUE THREAD

**Issue by WissemEd** [textext/textext#365]
Hello everyone,

I am currently trying to use TexText in my M1 Mac. I followed all the installation instructions from the related website. 
Everything seems to be well installed (For instance in my terminal, I have checked the installation of TexText itself and it says that the installation was complete and successful).

I have added the line required in the file "preferences.xml" in the "extensions" group. Here it seems to create a problem when launching Inkscape.

Because after modifying the "preferences.xml" file and launching Inkscape then opening a random EPS file : I keep encountering this error message : 

<img width="477" alt="Capture d’écran 2022-09-22 à 10 22 30" src="https://user-images.githubusercontent.com/111924896/191698818-f6051a1d-2e1e-4180-bca0-6e9dbb72a0f7.png">

Furthermore, the "TexText" extensions appears in the extensions window of Inkscape : so it made me sure that the installation was correct.

Here is the modified line of the "preferences.xml" file : 

<img width="432" alt="Capture d’écran 2022-09-22 à 10 35 44" src="https://user-images.githubusercontent.com/111924896/191699354-aee7c194-6932-4390-b109-a5efac636554.png">

What am I missing ? Could anyone help me to solve this issue ? Thank you a lot for your help (Also I apologize if my message is unclear : I am not familiar with this kind of procedure)

Best regards,

**Comment by jcwinkler** [comment]
Hi @WissemEd Did you try to launch Inkscape and then the TexText extension **without** modifcation of `preferences.xml`? If not, please try this at first. What happens?

**Comment by jcwinkler** [comment]
(I know that the documentation says to add this line to the preferences, but maybe the behavior of the Inkscape extension subsystem on Mac has changed once again, so lets test it...)

**Comment by WissemEd** [comment]
Hi @jcwinkler,

Thank you for your answer. Indeed, your proposition was correct : it worked fine by launching the extension without modifying the preferences file.
It may seem obvious but I have tried many alternatives except this one !

Maybe it would be useful to add a little note on the documentation to aware next users that this step could be unnecessary for some !

Thank you again for our help and have a nice day,

Best regards.

Wissem Eddine

**Comment by jcwinkler** [comment]
> Maybe it would be useful to add a little note on the documentation to aware next users that this step could be unnecessary for some !

Good hint! I will update the documentation.
