### ISSUE TITLE
TexText freezes and does not produce any output

### ISSUE THREAD

**Issue by steine01** [textext/textext#367]
**Description of the problem/ steps to reproduce**
The TextText extension window opens, but freezes when clicking preview or save, regardless of the content. There is no error message or dialog, I just need to close the window and do not get any output. I uninstalled and re-installed both inkscape and TexText with the recommended settings. Also the manual use of the toolchain works, and the log file does not contain any obvious errors.

**Logfile**
[textext.log](https://github.com/textext/textext/files/9656687/textext.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/74188395/192549345-26807fa0-13a9-4063-8fed-104dbc6193ff.png)

**System information**

- TexText version: 1.8.2
- Inkscape version: 1.2.1
- Operating system: [e.g. Windows 10, 1803, 32-bit] Windows 10, 64 bit
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTeX
- Windows only: TexText installed via batch script or installer file: batch script

**Comment by jcwinkler** [comment]
At the first run the Python files are compiled to .pyc files which may take some time, esp. on slow systems. What happens if you really wait for a long time? I experience similar issues on my Windows system from time to time.
