### ISSUE TITLE
Support for Inkscape App installation via the Microsoft Store

### ISSUE THREAD

**Issue by christianll9** [textext/textext#375]
**Is your feature request related to a problem? Please describe.**
I installed Inkscape as an app for Win10 from the [Microsoft Store](https://apps.microsoft.com/store/detail/inkscape/9PD9BHGLFC7H). I was able to find the executable in a hidden windows folder, but when I start the `setup_win.bat` script with Powershell (and admin rights), I get the following error:

![grafik](https://user-images.githubusercontent.com/38144453/199711225-f027ae13-0213-4555-a7bd-aa1aecda2f63.png)

**Describe the solution you'd like**
I would like to have a working instruction, how to install TexText when Inkscape was installed via the Microsoft Store.

**Comment by jcwinkler** [comment]
It is not possible to call Windows Apps installed from the store directly from the command line. I suggest to run setup with this option:

```
setup_win.bat --skip-requirements-check
```

Then try to open TexText from within Inkscape.
