### ISSUE TITLE
Add linting with `pylint` (and in CI)

### ISSUE THREAD

**Issue by nikosavola** [textext/textext#377]
**Before submitting a feature request make sure you have checked in the
  [documentation](https://textext.github.io/textext) if it does
  already exist!**

**Is your feature request related to a problem? Please describe.**
Static analysis is not done to the repo currently. It can help with simplifying statements and preventing bugs.

**Describe the solution you'd like**
Add a `.pylintrc` with some chosen standard to the repository and enforce some sort of linting in the CI.

**Comment by jcwinkler** [comment]
I will definitely do this, but not in the current chaotic code base which is the result of 15 years of development with several participants. I am currently doing a major refactoring of the whole extension which will be released as TexText 2.0. There, I will ensure that the code will meet pylint requirements.
