### ISSUE TITLE
Two different libpng

### ISSUE THREAD

**Issue by jvianalopes** [textext/textext#382]
**Before submitting a bug report make sure you have checked the
  [FAQ](https://textext.github.io/textext/usage/faq.html) and
  [Troubleshooting](https://textext.github.io/textext/usage/troubleshooting.html)
  sections in the documentation!**

**Description of the problem/ steps to reproduce**

Executing the Python 

**Steps to reproduce the behavior (if not obvious from description)**:
1. Command to install textext:
/Applications/Inkscape.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 setup.py --pdflatex-executable=$(which pdflatex) --inkscape-executable=/Applications/Inkscape.app/Contents/MacOS/inkscape 

2. TexText Installation works without problems in Mac OS X

3. After I call Tex Text from inkscape menu I received the messages bellow..

4. I am able to run pdflatex from the Inkscape Python:
from subprocess import Popen, PIPE
process = Popen(['pdflatex', '/Users/jlopes/a.tex', '-interaction=nonstopmode -halt-on-error'], stdout=PIPE, stderr=PIPE)
stdout, stderr = process.communicate()
the stderr is empty and the latex file was compiled

5.  I was able to force to use the library from macports adding in exec_command :
   my_env = os.environ.copy()
   if "DYLD_LIBRARY_PATH" in my_env:                                                                                             
        my_env["DYLD_LIBRARY_PATH"] = "/opt/local/lib:" + my_env["DYLD_LIBRARY_PATH"]                                             
   else:                                                                                                                         |
       my_env["DYLD_LIBRARY_PATH"] = "/opt/local/lib"    

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stdout (if available):</summary>

```
Command /opt/local/bin/pdflatex tmp.tex -interaction=nonstopmode failed (code -6)
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
dyld: Library not loaded: /opt/local/lib/libpng16.16.dylib
  Referenced from: /opt/local/bin/pdflatex
  Reason: Incompatible library version: pdflatex requires version 55.0.0 or later, but libpng16.16.dylib provides version 54.0.0

```
</details>

**Logfile**
Please also *attach* the TexText log file. You find it at the following locations:

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**
Mac OS X Big Sur 11.7.3
Macports  2.8.1
texlive @2022 
libpng @1.6.39

- TexText version: 1.8.2
- Inkscape version: 1.2
- Operating system: [e.g. Windows 10, 1803, 32-bit]
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Comment by jcwinkler** [comment]
Thanks for the report.

Am I right that the provided code

```python
my_env = os.environ.copy()
if "DYLD_LIBRARY_PATH" in my_env:
    my_env["DYLD_LIBRARY_PATH"] = "/opt/local/lib:" + my_env["DYLD_LIBRARY_PATH"]
else:
    my_env["DYLD_LIBRARY_PATH"] = "/opt/local/lib"
```
fixed the problem?
