### ISSUE TITLE
Installation fails on MacOS due to cssselect package missing

### ISSUE THREAD

**Issue by ddrous** [textext/textext#389]
**Description of the problem/ steps to reproduce**
The installations instruction appear to be out of date as `cssslect` appears not to be packages with `lxml` anymore.

**Steps to reproduce the behavior (if not obvious from description)**:
1. Go to the page https://textext.github.io/textext/install/macos.html
2. Follow the installation steps all the way to Method 1
3. TextText doesn't start in Inkscape due to missing packages

**Message(s) in error dialog (if this comes up)**
Package not found. 

**Potential solution**
`$(brew --prefix)/opt/python@3.9/libexec/bin/pip install cssselect`

That worked for me !

**Comment by jcwinkler** [comment]
Thanks @ddrous  I will update the documentation tomorrow!
