### ISSUE TITLE
Use external otf or ttf font

### ISSUE THREAD

**Issue by DavidCheshire** [textext/textext#39]
I have a preferred font, Baskerville 120 Pro, set as the default font in Inkscape. It would be nice if TexText would automatically use the Inkscape default font. If not by default, it would be nice if the font to be used by TexText could be specified as an external system gont. I understand that XeLaTex supports this, but entering \setmainfont{Times New Roman} in the TexText equation editor produces an error message.

I should have said thanks for all your hard work creating TexText, so I'll say it now: thank you.

**Comment by sizmailov** [comment]
`\setmainfont{Times New Roman}` probably should go to preamble file rather than in equation editor. Did you try it?

**Comment by DavidCheshire** [comment]
Thanks for getting back to me. I tried adding it to default_packages.tex, so that it is:

\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}
\setmainfont{Times New Roman}

but I get the same error message whether I use pdflatex, xelatex or lualatex:

"Your LaTeX code has problems:
5: Error: Undefined control sequence \setmainfont.
Problem exists here: \setmainfont"

**Comment by sizmailov** [comment]
`setmainfont` comes from `fontspec` package. You should import it first. 
  
    \usepackage{fontspec}
    \setmainfont{Times New Roman}

**Comment by jcwinkler** [comment]
I will add a section to the WIKI which gives some hints for the usage of specific fonts and specific sizes because these questions are asked quite frequently.

**Comment by DavidCheshire** [comment]
Excellent, thank you both for your help.
