### ISSUE TITLE
GUI appears behind main window on macOS

### ISSUE THREAD

**Issue by micfong-z** [textext/textext#392]
**Description**

On macOS Ventura 13.4.1, the TexText GUI window appears behind main Inkscape window, and needs to be manually selected (which is counterintuitive). It should work like a popup that appears in front of everything.

It could be confusing to new users, since the main Inkscape window freezes and my cursor turns into a spinning pinwheel (not visible in the screen recording) when I try to start TexText, and nothing *seem* to happen.

Could be related to #370. I can confirm that the exit shortcut mentioned in that issue now works correctly.

**Screen recording**

https://github.com/textext/textext/assets/68492819/5d459adc-9df2-4c21-9346-41c77839f4ca

**System information**

- TexText version: 1.9.0
- Inkscape version: 1.3 (0e150ed, 2023-07-21), Apple Silicon/M1 distribution.
- Operating system: macOS Ventura 13.4.1

**Comment by jcwinkler** [comment]
Thank you for the report. Please open the Inkscape  extension manager - does it show the same behavior?

**Comment by micfong-z** [comment]
> extension manager - does it show the same behavior?

Yes it does. It also opens behind the main window.

FYI, there are still a number of windows that pops up "correctly", e.g. About, Preferences, most extensions includes with Inkscape etc.

**Enlarged/zoomed window**

https://github.com/textext/textext/assets/68492819/69ce5dbb-c40b-4125-8ee0-f44bf3bce2d5

**Fullscreen window**

https://github.com/textext/textext/assets/68492819/05a8c265-3042-469c-b9f4-d69b21700ce7

(Sorry for the low bitrate. GitHub forced me to limit video size :( )

**Comment by jcwinkler** [comment]
It seems that this is a general issue of GTK3 under MacOS.

> FYI, there are still a number of windows that pops up "correctly", e.g. About, Preferences, most extensions includes with Inkscape etc.

These extension use Inkscape GUI extension framework. Hence, they are not affected by this issue. TexText and the ExtensionManager use a custom GUI directly based on GTK (via Gobject) which offers far more possibilities.

**Comment by jcwinkler** [comment]
See here: https://gitlab.gnome.org/GNOME/gtk/-/issues/1296

In fact, TexText and ExtensionManager are opend via Inkscape from the comand line...

Hmm...
