### ISSUE TITLE
TexText Extension not working on Inkscape 1.3

### ISSUE THREAD

**Issue by orengt** [textext/textext#395]
**Description of the problem/ steps to reproduce**
I just updated my inkscape installation to 1.3 and then reinstalled TexText 1.8.2 on win 64B using the bat script.
The installation ended successfully without any error message.
I looked for the installation in my extensions folder, it's there as expected.
However when I try to use the extension via Extensions -> Text -> TexText: 
The Waiting Cursor appear for about 10 seconds then I get nothing.
Note that TexText operated properly on my Inkscape 1.2 instal & TexText 1.3 dev with the only problem that it throw an error on closing the extension window but the text was edited correctly. Unfortunately I didn't save the error hopping it'll solve in the new version.

**Steps to reproduce the behavior (if not obvious from description)**:
Tring to open the extension.

**Message(s) in error dialog (if this comes up)**
No Message

**Logfile**
Log file not created.

**System information**

- TexText version: 1.8.2
- Inkscape version: 1.3
- Operating system: Widows 11
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTeX (all packages are up to date).
- Windows only: TexText installed via batch script or installer file: batch

**Comment by jcwinkler** [comment]
Hi @orengt! TexText 1.8.2 is not compatible with Inkscape 1.3. Please download and install TexText 1.9.0.

**Comment by orengt** [comment]
@jcwinkler 
Oh, sorry for the trouble, I miss read the instructions.
Thanks for the quick reply and the very useful extension you developed.
Oreng
