### ISSUE TITLE
TeXtext doesn't make anything at all

### ISSUE THREAD

**Issue by Mischrysalis** [textext/textext#396]
When I compile the TeX code, then there is nothing printed, it's freezing, and even there is no error dialog displaying. I clicked both of preview and save buttons, but both of them fails. I didn't change any options of inkscape, textext when I installed.

### Errors
No errors are printed. If compilation of your LaTeX code fails TexText opens a dialog displaying the cause of the failure. In most cases a syntax error in your code will be the reason. TexText filters the relevant information from the compiler output and displays it:

### Logfile
I check the logfiles in %APPDATA%, and find that the last done is
"       Converting .tex to .pdf done          //  base.py:538 " in pdf-2-svg process.

### System information
TexText version: 1.9
Inkscape version: 1.3
Operating system: Win11-x64
TeX Distro: MiKTeX
TexTeXt Install: Installer

**Comment by jcwinkler** [comment]
Hmm, actually, this behaviour is more typical when running TexText 1.8.2 under Inkscape 1.3. Are you really sure that TexText 1.9 is called when you open the extension? Please check if "TexText 1.9" is shown in the extension's window title. Thanks.

**Comment by jcwinkler** [comment]
Another possibility is that Miktex tries to install packages on the fly. This blocks TexText from compilation. Please try to manually compile the snippet using the packages you specified in the TexText preamble.
