### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by WC802** [textext/textext#397]
Textext has been successfully installed according to the terminal message (TexText has been SUCCESSFULLY installed on your system <--) and appears on the Inkscape extensions but no window pops up when I try to use it. It does try to open it and fails, but no error message appears. If I try to it intall it from "Manage Extensions...", I get the following error "This package requires python VirtualEnv which is not available on your system.". If it refers to the Python virtualenv package, it is already installed. The OS I'm using is macOS Ventura 13.3, Inkscape is  v.1.3 and textext v.1.9.0.

**Comment by jcwinkler** [comment]
On MacOs the TexText window sometimes opens behind Inkscape. You should be able to switch to the Window. This behaviour is stupid, but a fundamental problem of MacOS and GTK 3.

Are you able to confirm this? (I have no Mac to test this)
