### ISSUE TITLE
inkscape hangs when opening textext extension; Ubuntu 22.04

### ISSUE THREAD

**Issue by h-dashti** [textext/textext#398]
**Before submitting a bug report make sure you have checked the
  [FAQ](https://textext.github.io/textext/usage/faq.html) and
  [Troubleshooting](https://textext.github.io/textext/usage/troubleshooting.html)
  sections in the documentation!**

**Description of the problem/ steps to reproduce**
When I use Inkscape and try to open the TexText extension, Inkscape does not respond and hangs; then I need to quit the Inkscape.

**Steps to reproduce the behavior (if not obvious from description)**:
1. Open Inkscape
2. Goto Extensions -> Text -> Tex Text
3. Inkscape hangs, and a message pops up asking to wait or close the application.

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```
Inkscape is not responding.
You may choose to wait a short while for it to continue or force the application to quit entirely.
```
</details>

**Logfile**
Please also *attach* the TexText log file. You find it at the following locations:
  - Windows: `C:\Users\[Your user name]\AppData\Roaming\textext`
  - Linux: `~/.cache/textext`
  - Mac: `~/Library/Preferences/textext`

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 1.8.2
- Inkscape version: 1.3
- Operating system: Ubuntu 22.04.3 LTS
[textext.log](https://github.com/textext/textext/files/12483106/textext.log)

**Comment by jcwinkler** [comment]
Please install TexText 1.9, then the problem should disappear.

**Comment by h-dashti** [comment]
I've installed TexTex 1.9, and upon launching Inkscape and attempting to utilize the TexText extension, I noticed that the Latex formula panel appears as expected. I am able to input mathematical expressions within this panel. However, simultaneously, a warning window emerges, displaying the message "Inkscape is not responding." Despite this warning, I can still successfully input formulas in the Latex Formula panel. Upon closing the formula panel and selecting the Wait button within the warning window, the warning window shuts down without any issues.

My perception is that this issue is associated with Inkscape 1.3 rather than being a problem with the TexText extension. This assumption arises from the fact that I reinstalled Inkscape, excluding any additional extensions, and encountered the same message upon navigating to Extensions -> Manage Extension. It's worth noting that this alert does not manifest when I utilize other subtabs within the Extensions tab.

**Comment by jcwinkler** [comment]
@h-dashti Am I right that TexText now produces correct svg snippets which are inserted into the document? And the remaining problem is that "not responding" is shown?

Both, TexText and the ExtensionManager make use of a custom user interface using GTK. Hence, they show similar blocking behaviour. Most other extension use the extension user interface framework provided by the extension subsystem. However, this offers only limited functionality and is not suitable for the needs of TexText.
