### ISSUE TITLE
Error occurred while generating preview

### ISSUE THREAD

**Issue by DavidCdeB** [textext/textext#399]
Thanks for this great program; unfortunately, since last update, I can see the error message below.

**Minimal Working Example:**
- $ inkscape
- Extensions > Text > TexText
- type `ab`
- press button Preview
- I'm using the default preamble `default_packages.tex` 

![textext](https://github.com/textext/textext/assets/18029016/c04a6206-7cd2-4f48-83e6-6b8ba50aaca5)

**Full error message here:**

Return Code: -11: b'\nEmergency save activated!\nEmergency save completed. Inkscape will close now.\nIf you can reproduce this crash, please file a bug at https://inkscape.org/report\nwith a detailed description of the steps leading to the crash, so we can fix it.\n** Message: 18:12:30.665: Error: \n 0# Inkscape::Application::crash_handler(int) in /usr/bin/../lib/inkscape/libinkscape_base.so.1.3.0.0\n 1# 0x00007F1AFCC2A710 in /usr/lib/libc.so.6\n 2# 0x00007F1AFB128A7B in /usr/bin/../lib/inkscape/../libgtk-3.so.0\n 3# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n 4# 0x00007F1AFC34E6AD in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n 5# 0x00007F1AFC3B828E in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n 6# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n 7# 0x00007F1AFC34E6AD in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n 8# 0x00007F1AFC3A5493 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n 9# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n10# 0x00007F1AFC34A67D in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n11# g_main_context_dispatch in /usr/lib/libglib-2.0.so.0\n12# 0x00007F1AFD3F1CC9 in /usr/lib/libglib-2.0.so.0\n13# g_main_context_iteration in /usr/lib/libglib-2.0.so.0\n14# g_application_run in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\n15# main in /usr/bin/inkscape\n16# 0x00007F1AFCC13CD0 in /usr/lib/libc.so.6\n17# __libc_start_main in /usr/lib/libc.so.6\n18# _start in /usr/bin/inkscape\n'
b''
args: ("Return Code: -11: b'\\nEmergency save activated!\\nEmergency save completed. Inkscape will close now.\\nIf you can reproduce this crash, please file a bug at https://inkscape.org/report\\nwith a detailed description of the steps leading to the crash, so we can fix it.\\n** Message: 18:12:30.665: Error: \\n 0# Inkscape::Application::crash_handler(int) in /usr/bin/../lib/inkscape/libinkscape_base.so.1.3.0.0\\n 1# 0x00007F1AFCC2A710 in /usr/lib/libc.so.6\\n 2# 0x00007F1AFB128A7B in /usr/bin/../lib/inkscape/../libgtk-3.so.0\\n 3# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 4# 0x00007F1AFC34E6AD in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 5# 0x00007F1AFC3B828E in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 6# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 7# 0x00007F1AFC34E6AD in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 8# 0x00007F1AFC3A5493 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 9# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n10# 0x00007F1AFC34A67D in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n11# g_main_context_dispatch in /usr/lib/libglib-2.0.so.0\\n12# 0x00007F1AFD3F1CC9 in /usr/lib/libglib-2.0.so.0\\n13# g_main_context_iteration in /usr/lib/libglib-2.0.so.0\\n14# g_application_run in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n15# main in /usr/bin/inkscape\\n16# 0x00007F1AFCC13CD0 in /usr/lib/libc.so.6\\n17# __libc_start_main in /usr/lib/libc.so.6\\n18# _start in /usr/bin/inkscape\\n'\nb''\nargs: ('inkscape', -11, b'\\nEmergency save activated!\\nEmergency save completed. Inkscape will close now.\\nIf you can reproduce this crash, please file a bug at https://inkscape.org/report\\nwith a detailed description of the steps leading to the crash, so we can fix it.\\n** Message: 18:12:30.665: Error: \\n 0# Inkscape::Application::crash_handler(int) in /usr/bin/../lib/inkscape/libinkscape_base.so.1.3.0.0\\n 1# 0x00007F1AFCC2A710 in /usr/lib/libc.so.6\\n 2# 0x00007F1AFB128A7B in /usr/bin/../lib/inkscape/../libgtk-3.so.0\\n 3# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 4# 0x00007F1AFC34E6AD in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 5# 0x00007F1AFC3B828E in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 6# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 7# 0x00007F1AFC34E6AD in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 8# 0x00007F1AFC3A5493 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n 9# 0x00007F1AFC34A644 in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n10# 0x00007F1AFC34A67D in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n11# g_main_context_dispatch in /usr/lib/libglib-2.0.so.0\\n12# 0x00007F1AFD3F1CC9 in /usr/lib/libglib-2.0.so.0\\n13# g_main_context_iteration in /usr/lib/libglib-2.0.so.0\\n14# g_application_run in /usr/bin/../lib/inkscape/../libgio-2.0.so.0\\n15# main in /usr/bin/inkscape\\n16# 0x00007F1AFCC13CD0 in /usr/lib/libc.so.6\\n17# __libc_start_main in /usr/lib/libc.so.6\\n18# _start in /usr/bin/inkscape\\n', b'', ['/usr/bin/inkscape', '--export-filename=tmp.png', '--pdf-poppler', '--pages=1', '--export-type=png', '--export-dpi=300', '--export-area-drawing', 'tmp.pdf'])",)

**Logfile**
Here the TexText log file:

[textext.log](https://github.com/textext/textext/files/12506555/textext.log)

**System information**

- TexText version: TexText 1.9.0
- Inkscape version: 1.3 (0e150ed6c4, 2023-07-21)
- Operating system: ArchLinux

**Comment by jcwinkler** [comment]
Thanks for the report. What I do conclude from the log is that the gobject introspection system throws the error. The system provides the Python bindings for the gtk interface of TexText (and other extensions like the extension manager). So I assume a packaging problem here. What does happen of you open the extension manager and work a little bit with it?

**Comment by Guilherme-gog** [comment]
@jcwinkler Ran into the same problem just now. When I opened the extension manager, I could not find TexText in it, and the error messages persisted. 

System info: 

-  TexText version: 1.9.0
- Inkscape version 1.3
- OS: Fedora 38

**Comment by andreyzhitnikov** [comment]
Hi guys, same issue for me. 
System info:

    TexText version: 1.9.0
    Inkscape version 1.3
    OS: Fedora 39

I tried Xorg and Wayland. Same problem.

**Comment by andreyzhitnikov** [comment]
Which info needed @jcwinkler ???

**Comment by jcwinkler** [comment]
Please could you perform the following test: generate a small pdf snippet using latex, e.g with the content $x=y$. Then open Inkscape and try to import this snippet. Does it work?

**Comment by andreyzhitnikov** [comment]
Yes, importing pdf works well. If I'm trying to generate from textex however I got  this
![Screenshot from 2023-11-10 04-27-24](https://github.com/textext/textext/assets/20877529/45cdaa5b-26e4-4e6e-a9f8-6937f8fda0aa)

**Comment by andreyzhitnikov** [comment]
@jcwinkler I have TeX Live 2023

**Comment by jcwinkler** [comment]
Ok, thanks @andreyzhitnikov . Now a final test. Take your pdf snippet (I assume it is called `test.pdf`) and run the following command:

```bash
inkscape --pdf-poppler --pages=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf
```

Does it produce a valid `test.svg` or does it result in a crash?

**Comment by andreyzhitnikov** [comment]
![Screenshot from 2023-11-10 10-41-25](https://github.com/textext/textext/assets/20877529/8ddc0f9a-07ce-4ee9-8497-7731396a819e)

**Comment by andreyzhitnikov** [comment]
@jcwinkler crashed

**Comment by jcwinkler** [comment]
OK, thanks. So this is really an inkscape issue, not an issue of TexText. 

Background: Inkscape is used by TexText to convert the generated pdf snippet into svg. And this converion crashes Inkscape. Most likely, it is a problem of packaging on your Fedora distro.

The Inkscape developers told me that this issue should be fixed in Inkscape 1.3.1. So you can try the following:

1. Download the Inkscape 1.3.1 AppImage from [their Website](https://inkscape.org/release/inkscape-dev/gnulinux/appimage/dl/)
2. Try to run the AppImgage. It shoud run out of the box. If not we are lost here.
3. Run and test TexText.

Please also post the exact version of the AppImage-Inkscape.

**Comment by andreyzhitnikov** [comment]
@jcwinkler I run Appimage. Textex does not start

**Comment by jcwinkler** [comment]
> It can run on the latest Appimage. Although it's still showing `"inkscape" is not responding` warning message.

This means what? Does it compile sth? Or does it hang?

**Comment by jcwinkler** [comment]
Ok. The "Inkscape is not responding" message is fine and intended since TexText opens a modal dialog, hence blocking the calling program.

**Comment by ajacquey** [comment]
I encountered the same issue than described here on Fedora 39.

I downloaded the Appimage from the website but Textext does not start (no window opens).

> @jcwinkler I run Appimage. Textex does not start
