### ISSUE TITLE
Repository spelling error

### ISSUE THREAD

**Issue by leberwurstsaft** [textext/textext#4]
It's a common spelling error, and it'd be unfortunate if we leave it in the repository name.

It should be *textext* instead of *texttext*.

**Comment by leberwurstsaft** [comment]
See https://help.github.com/articles/renaming-a-repository/ for a guide on how to rename the repo. It should be a quick fix.

**Comment by jcwinkler** [comment]
Indeed, my most favorite typo... Fixed it.

**Comment by leberwurstsaft** [comment]
👍
