### ISSUE TITLE
texttext hangs before any ouput is produced

### ISSUE THREAD

**Issue by VasilySotnikov** [textext/textext#401]
**Description of the problem/ steps to reproduce**

When I press _Save_ or _Preview_ with any input, `textext` hangs and never produces any output, even messages. `inkscape` itself is also blocked. From here I can only kill `textext` to return to `inkscape`.

`textext` worked perfectly fine for me until recently when this issue appeared, so it must have been caused by a recent update in `inkscape`. If it's of any help I can try to downgrade both `inkscape` and `textext` to see if the issue disappears. 

From the log file it's clear that it hangs on the call  `ixc.inkscape` from `TexToPdfConverter.pdf_to_svg`.

**Message(s) in error dialog (if this comes up)**
`textext` (and `inkscape` together with it) hangs before messages are shown.

**Logfile**
[textext.log](https://github.com/textext/textext/files/12905779/textext.log)

**System information**

- TexText version: 1.9.0
- Inkscape version: 1.3 (1:1.3+202307231459+0e150ed6c4)
- Operating system: Tuxedo OS 2 (based on Kubuntu 22.04), x86_64 GNU/Linux, kernel 6.2.0-10027

**Comment by VasilySotnikov** [comment]
I'm not sure if this is relevant, but I thought I'd mention this. Just 2 weeks ago I had an [issue](https://github.com/dmitry-t/inkscape-export-layers/issues/17) with another extension related to [self-calling of inkscape](https://gitlab.com/inkscape/inkscape/-/merge_requests/5664).  I managed to [fix](https://github.com/dmitry-t/inkscape-export-layers/pull/18) it by a simple hack. 

I tried something similar with `textext` as well, but it didn't fix it unfortunately.

**Comment by tommy-engels** [comment]
I have a similar problem, but I do get an error message:
![image](https://github.com/textext/textext/assets/3800194/9ba35ff4-6ccf-4b3e-975a-d22634eff1be)

it seems to me, just like you describe it, that it is some self-calling to inkscape, but I cannot clearly identify the call to `TexToPdfConverter.pdf_to_svg`

**Comment by jcwinkler** [comment]
Thanks for the reports. Indeed, it seems to be related with self calling Inkscape. This is done when the TeX generated pdf is converted to svg so it can be inserted in the document. This is a common problem in TexText 1.8.2 when using it in Inkscpa 1.3.

Currently, I do not understand why it again happens with TexText 1.9. On Windows and Linux evertyhing is fine but I do not have a Mac for testing.

Could you do the following test: There is a built in tool for inserting a TeX formula (which cannot be re-edited later). It also uses this inkscape self call. Please try it out. You find it under `Extensions - Text - Formula (pdflatex)...`. Does it also blocks Inkscape?

**Comment by tommy-engels** [comment]
Dear jcwinkler,
I will try that now.
FYI:
I am running on LINUX (Fedora), and the initial report also considers a LINUX variant

**Comment by tommy-engels** [comment]
`Formula (pdflatex)` does also crash on my system, but with a different error message:
![image](https://github.com/textext/textext/assets/3800194/26f51c32-c380-43c0-8baa-d29f05e90bc6)

**Comment by jcwinkler** [comment]
> I am running on LINUX (Fedora), and the initial report also considers a LINUX variant

Ah, sorry. I am on Kubuntu 22.04 with no problems. Hmm, strange.

**Comment by jcwinkler** [comment]
> Formula (pdflatex) does also crash on my system, but with a different error message:

You need to install the standalone package of your Latex distro (`texlive-latex-extra` under ubuntu)

**Comment by jcwinkler** [comment]
Ok, so this is clearly an Inkscape problem. In the extension subsystem the `call` method seems to be broken.

Would you like to post it to the developers or should I do?

Here is their issue-tracker: https://gitlab.com/inkscape/extensions/-/issues

**Comment by tommy-engels** [comment]
If you don't mind I would appreciate if you could report it. if they have further questions etc, you are certainly the better person, also, in case it requires adaptations to `textext`, you should be in CC I imagine

**Comment by jcwinkler** [comment]
@VasilySotnikov, @tommy-engels Could you try the following fix, please? Just install it as you did with your original installation of TexText. Does it work now?

[TexText-Linux-1.9.1-dev.zip](https://github.com/textext/textext/files/12927325/TexText-Linux-1.9.1-dev.zip)

**Comment by tommy-engels** [comment]
Hi again,
unfortunately on my end same result as before:
![image](https://github.com/textext/textext/assets/3800194/d6ff63bb-e5c3-44ce-9a1c-ca155413dd81)

**Comment by VasilySotnikov** [comment]
> @VasilySotnikov, @tommy-engels Could you try the following fix, please? Just install it as you did with your original installation of TexText. Does it work now?
> 
> [TexText-Linux-1.9.1-dev.zip](https://github.com/textext/textext/files/12927325/TexText-Linux-1.9.1-dev.zip)

This doesn't fix the problem unfortunately.

Thanks a lot for your help with this!

**Comment by jcwinkler** [comment]
Please do another test with `pdflatex.py` attached below. I want to be sure that the problem is not related to TexText's complexity.

1. Make a backup of the original `pdflatex.py` (admin rights required):
    ```bash
     cp /usr/share/inkscape/extensions/pdflatex.py    /usr/share/inkscape/extensions/pdflatex.py.old
     ```
2. Unzip the attached archive and put `pdflatex.py`into `/usr/share/inkscape/extensions/`
3. Restart inkscpae and try `Extensions`- `Text` - `Formula (pdflatex)...`

Does the error still persists?

To restore the original pdflatex:
```bash
 cp /usr/share/inkscape/extensions/pdflatex.py.old    /usr/share/inkscape/extensions/pdflatex.py
 ```
[pdflatex.zip](https://github.com/textext/textext/files/12928910/pdflatex.zip)

**Comment by VasilySotnikov** [comment]
> Please do another test with `pdflatex.py` attached below. I want to be sure that the problem is not related to TexText's complexity.
> 
>     1. Make a backup of the original `pdflatex.py` (admin rights required):
>        ```shell
>         cp /usr/share/inkscape/extensions/pdflatex.py    /usr/share/inkscape/extensions/pdflatex.py.old
>        ```
> 
>     2. Unzip the attached archive and put `pdflatex.py`into `/usr/share/inkscape/extensions/`
> 
>     3. Restart inkscpae and try `Extensions`- `Text` - `Formula (pdflatex)...`
> 
> 
> Does the error still persists?
> 
> To restore the original pdflatex:
> 
> ```shell
>  cp /usr/share/inkscape/extensions/pdflatex.py.old    /usr/share/inkscape/extensions/pdflatex.py
> ```
> 
> [pdflatex.zip](https://github.com/textext/textext/files/12928910/pdflatex.zip)

Yes, the error still persists. 


I actually already tried to insert the line 
```
os.environ["SELF_CALL"] = "1"
```
already before, it didn't help.

**Comment by VasilySotnikov** [comment]
> Perform the steps described there. The critical one will be step 5 where Inkscape is called for pdf to svg conversion. Does it work?

Actually it does not work, it gets stuck also, hmm. In fact, I just realized that even importing any _pdf_ hangs Inkscape for me. So from my perspective the issue can be closed here, since the bug has to do with _pdf_ importing in Inkscape. Ok, it really feels dumb not trying this in the first place, sorry for bringing an irrelevant issue here...

**Comment by tommy-engels** [comment]
@jcwinkler 

I tried the manual testing as described - indeed step 5 fails:

`inkscape --pdf-poppler --pdf-page=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf`

returns:

`Unknown option --pdf-page=1`

now if I remove the offending paramete, I get a crash similar to what I observe in textext:

![image](https://github.com/textext/textext/assets/3800194/52a731bd-977b-4da6-8f41-7f8058a73f28)

**Comment by jcwinkler** [comment]
Thanks for the tests! It clearly reveals that the pdf to svg conversion itself crashes Inkscape. So we were on the wrong path here. I will communicate this to the Inkscape developers.

@tommy-engels Yes, the documentaiton is outdated there. I forgot to update the manual toolchain for 1.3. The correct conversion command line is

```bash
inkscape --pdf-poppler --pages=1 --export-type=svg --export-text-to-path --export-area-drawing --export-filename test.svg test.pdf
```

I will fix this,

**Comment by jcwinkler** [comment]
@VasilySotnikov Could you do the Inkscape developers a favour and try to import a pdf file using the latest AppImage of Inkscape? And also do the command line conversion test?

You can download it here: https://inkscape.org/release/inkscape-dev/gnulinux/appimage/dl/

Does it work with the nightly build (Note: TexText will not work using an AppImage if not configured properly).

Please give feedback here so we can decide of we open a separate issue on their issue tracker,

**Comment by VasilySotnikov** [comment]
> @VasilySotnikov Could you do the Inkscape developers a favour and try to import a pdf file using the latest AppImage of Inkscape? And also do the command line conversion test?
> 
> You can download it here: https://inkscape.org/release/inkscape-dev/gnulinux/appimage/dl/
> 
> Does it work with the nightly build (Note: TexText will not work using an AppImage if not configured properly).
> 
> Please give feedback here so we can decide of we open a separate issue on their issue tracker,

I downloaded the image `Inkscape 1.4-dev (afe3546, 2023-10-20)`, and pdf import does work. Both as a command for step 5 and through the GUI. Thanks a lot communicating the issue to inkscape developers!

**Comment by jcwinkler** [comment]
Great to hear! Thanks!

**Comment by jcwinkler** [comment]
Ah, and one final test please with the 1.3.x nightly: https://gitlab.com/inkscape/inkscape/-/jobs/artifacts/1.3.x/download?job=appimage%3Alinux

(Please also post the version string)

**Comment by VasilySotnikov** [comment]
> Ah, and one final test please with the 1.3.x nightly: https://gitlab.com/inkscape/inkscape/-/jobs/artifacts/1.3.x/download?job=appimage%3Alinux
> 
> (Please also post the version string)

Also works with this version (`Inkscape 1.3 (4f532fb, 2023-09-22)`)
