### ISSUE TITLE
TexText window does not open with Inkscape 1.3.2

### ISSUE THREAD

**Issue by shamu35** [textext/textext#409]
I have upgraded Inkscape from 1.3 to 1.3.2 and TexText extension from 1.9.0 to 1.10.1 on Windows 10.

When I run Erweiterungen -> Text -> TexText noting happens. It doesn't open the TexText window for entering my LaTeX formula.

Then I uninstalled everything, installed older Inkscape 1.3 and TexText 1.10.1 and it worked fine again.

It seems, TexText 1.10.1 or 1.9.0 is running fine with Inkscape 1.3, but not with 1.3.2. I have not tried how it worked on Inkscape 1.3.1 which was only available for a few days.

**Logfile**
See here my textext.log file:
[textext.log](https://github.com/textext/textext/files/13488586/textext.log)

**System information**

- TexText version: 1.10.1
- Inkscape version: 1.3.2
- Operating system: Windows 10, 1809 (LTSC), 64-bit
- Windows only: LaTeX-distribution: MiKTeX 23.10.12
- Windows only: TexText installed via installer file

**Comment by jcwinkler** [comment]
Thanks for the report. I will look into this within the next 24h.

**Comment by jcwinkler** [comment]
Hi @shamu35 I cannot reproduce this problem on Windows 10 22H2 and Inkscape 1.3.2 / TexText 1.3.2. The log file you provided stopped at a certain point.

Please try the following: 
1. Download the script based installer: https://github.com/textext/textext/releases/download/1.10.1/TexText-Windows-1.10.1.zip
2. Unzip the file
3. Open a Windows command window and change into the directory containing the `setup_win.bat` file.
4. Execute the file. What is the output of the installer script?

**Comment by shamu35** [comment]
Hi Jan

 

Thanks for your answer

 

I did some more tests in the meantime.

 

I found that it works on Windows 10 22H2 and also Windows 10 LTSC 2021 21H2,
but not on the older Windows 10 LTSC 2019 (1809).

 

Please find attached the two log files from the Windows 10 LTSC 2019
installation.

Do you think you can fix this, that it will also work for Windows 10 LTSC
2019 (1809)?

We have many from them and this version is still supported by Microsoft.

 

 

Best regards

shamu35

**Comment by jcwinkler** [comment]
I am not aware that I do use any Windows version specific commands in TexText. So I am a bit puzzled.

Could you please do the test I suggested and post the output? It will run the requirement check so I can see where and why it hangs (according to the log you provided that's the crurcial part).

**Comment by shamu35** [comment]
The file "setup_win.log" which I sent in the last email is the output from the test you requested and the file "textext.log" was created on the same computer after starting Inkscape and tried to run TexText.

It doesn't open a TexText window for entering formulas.

**Comment by jcwinkler** [comment]
> The file "setup_win.log" which I sent in the last email 

I do not see this file on github.

**Comment by shamu35** [comment]
ok sorry, I attached it to the email. Now I add them directly in Github.
[textext.log](https://github.com/textext/textext/files/13500528/textext.log)
[setup_win.log](https://github.com/textext/textext/files/13500530/setup_win.log)

**Comment by shamu35** [comment]
I did a test on a different computer also with Windows 10 LTSC 2019. 
When I press the Preview button inside of Tex Text plugin, it needs 20-25 minutes! until the preview is showing correctly. During this time, inkscape.exe process is making a lot of CPU load, uses up to 3GB ram and Inkscape is not responding. When I press the Save Button, the same situation happens again, finally the Latex code will be showing within the document but this is unusable.

The same procedure with older Inkscape 1.3 and Tex Text Plugin 1.9.0 needs only a few seconds and not minutes on the same computer.

Do you think you can figure out the problem?

**Comment by jcwinkler** [comment]
The log files you provided do not offer any helpful information.

The only change that has been made from TexText 1.9 to 1.10 is to offer typst support. This does not affect the Latex workflow. I do not see a problem in TexText.

What happens if you compile a formula using the built-in latex extension (Formula (pdflatex))? Is it also slow?

**Comment by shamu35** [comment]
> What happens if you compile a formula using the built-in latex extension (Formula (pdflatex))? Is it also slow?

On LTSC 2019 this works but is also slow, on LTSC 2021 it's fast. The same situation as with Tex Text Plugin.

**Comment by shamu35** [comment]
I did some more tests and determined that the problem appears only when there is selected "System default" for the interface language in Inkscape Preferences. This configures the UI language of Inkscape to German which is the OS language of my test system.
If I choose "German (de)" from the drop down list and restart Inkscape, then it runs fast without a problem. I tried also Italian and French language and they also are running fine. There is only a problem when I choose "System Default" and this is the default setting after installation of Inkscape.

And again, this happens only on Windows 10 LTSC 2019 not on the newer Windows 10 versions.
It also happens when I use "Formula (pdflatex)", so it's not a TexText problem, but can you imagine what could be the reason for this strange behavior?

**Comment by jcwinkler** [comment]
Thanks for this in-deep investigation. This is really a very strange result i cannot explain.

I suggest you post your observation (by the example of "Formula (pdflatex)" to the inkscape extensions issue tracker:

https://gitlab.com/inkscape/extensions/-/issues

**Comment by shamu35** [comment]
I have posted the problem now on the Inkscape extensions issue tracker:

https://gitlab.com/inkscape/extensions/-/issues/562

**Comment by berryboy2012** [comment]
I have encountered a similar problem, except that setting Inkscape's language to Chinese wouldn't fix my problem. My workaround is sticking with English at the moment.

**Comment by sitadrost** [comment]
Same problem here, with `Inkscape 1.3.2 (1:1.3.2+202311252150+091e20ef0f)` on Ubuntu 22.04. 

I just installed TexText-1.10.0, prompted by [this post](https://github.com/textext/textext/issues/386) (I got the same error), and now the TexText pop-up window no longer opens when I select Extensions -  Text - TexText. 

I've tried several different interface languages, but none of them fixed the problem so far.

**Comment by jcwinkler** [comment]
@sitadrost Did you also check the built-in TeX extension? (Extensions - Text - Formula (pdflatex))? Does it also fail to open?

**Comment by sitadrost** [comment]
@jcwinkler Apologies for the late response! The built-in TeX extension is greyed-out, so yes, you could say that it fails to open.

**Comment by jcwinkler** [comment]
Usually this means that the latex compiler is not found or the Python environment is not set up properly. Hmm. 

What is the output of `~/.cache/textext/textext.log` if this file exists?

**Comment by sitadrost** [comment]
Thanks, that log file is really helpful! 

Interesting: when I ran `setup.py `the first time, it informed me that all LaTeX compilers had been found (only `typst` hadn't been located, which is correct, so I ignored that), and that "TexText has successfully been installed on your system" Still, the log file complains about the LaTeX compilers not being found. So I just ran `setup.py` again, this time explicitly pointing it to `pdflatex`, and now everything works as it should.

Thanks a lot for your help @jcwinkler!

**Comment by jcwinkler** [comment]
OK, glad that it works now.

However, I am a little bit puzzled about this scenario. The error should be safely caught by the  setup script. 

Could you please re-run the setup procedure without explicitely specifying the pdflatex path and post the output as well as the file `setup.log` which is created in the directory of `setup.py` ?

**Comment by sitadrost** [comment]
Sure, here you go (attached). Just checked: the TexText window in Inkscape doesn't open now, but luckily I now know how to fix that.
[textextsetup.log](https://github.com/textext/textext/files/14415573/textextsetup.log)
