### ISSUE TITLE
Make latex hyperrefs work

### ISSUE THREAD

**Issue by drdrjacobs** [textext/textext#412]
Hyperrefs in latex text do not work when they are clicked on. It would be nice if they did work. 

To reproduce, add the hyperref package to the preamble:

```
\usepackage{amsmath,amsthm,amssymb,amsfonts,hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,      
    urlcolor=cyan}
``` 

Then add some links using Textex, for example `\url{https://www.wikipedia.org/}` or `\href{https://www.wikipedia.org/}{Link to Wikipedia}`.

Now export to a pdf and open up in a pdf viewer. The hyperlinks will not work.

Alternatively, drop the svg into your browser. The hyperlinks will also not work.

**Comment by jcwinkler** [comment]
Unfortunately, I do not think this is possible. TexText processes each code snippet in three steps:
1. Compilation of the tex code to a temporary pdf file using the tex compiler.
2. Converison of the temporariy pdf file into a temporary svg file using inkscape itself.
3. Placement of the content of the temporariy svg file into your svg document.

In step 2 any hyperlink information is lost.

**Comment by drdrjacobs** [comment]
Inkscape does have hyperlink functionality:

[https://proseandconst.xyz/blog/underlined-link-inkscape/](url)

Is the loss of hyperlink information in step 2 something that could be fixed with an Inkscape feature request?

**Comment by jcwinkler** [comment]
> Is the loss of hyperlink information in step 2 something that could be fixed with an Inkscape feature request?

I asked the Inkscape developers in their chat and will let you know when I got a reply.

**Comment by jcwinkler** [comment]
OK, they told me that it is not possible to implement this since it is a limitation of the library they use for the pdf -> svg conversion. 👎
