### ISSUE TITLE
setup.py: error: unrecognized arguments: not found

### ISSUE THREAD

**Issue by wglogowski** [textext/textext#422]
**Description of the problem/ steps to reproduce**
1) When I open Inkscape, I see TexText, but it is grayed out.
2) I followed all the steps on the page https://textext.github.io/textext/install/macos.html
3) When I run the code $(brew --prefix)/opt/python@3.9/libexec/bin/python3 setup.py --pdflatex-executable=$(which pdflatex) --skip-requirements-check 
from step 12 I get the following output: 

**Message(s) in error dialog (if this comes up)**

<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
(base) walterglogowski@Walters-MacBook-Air-2 ~ % $(brew --prefix)/opt/python@3.9/libexec/bin/python3 setup.py --pdflatex-executable=$(which pdflatex) --skip-requirements-check
usage: setup.py [-h] [--inkscape-extensions-path INKSCAPE_EXTENSIONS_PATH] [--inkscape-executable INKSCAPE_EXECUTABLE] [--pdflatex-executable PDFLATEX_EXECUTABLE]
                [--lualatex-executable LUALATEX_EXECUTABLE] [--xelatex-executable XELATEX_EXECUTABLE] [--typst-executable TYPST_EXECUTABLE]
                [--portable-apps-dir PORTABLE_APPS_DIR] [--skip-requirements-check] [--skip-extension-install] [--keep-previous-installation-files] [--all-users]
                [--color {always,never}]
setup.py: error: unrecognized arguments: not found

I did check to make sure of the setup.py file in the location
I'm running Sonoma 14.4 Beta (23E5205c 
Inkscape Inkscape 1.3.2 (091e20e, 2023-11-25)

Any suggestions?

**Comment by wglogowski** [comment]
***@***.*** ~ % python3 setup.py --pdflatex-executable=$(which pdflatex) --skip-requirements-check
usage: setup.py [-h] [--inkscape-extensions-path INKSCAPE_EXTENSIONS_PATH]
                [--inkscape-executable INKSCAPE_EXECUTABLE]
                [--pdflatex-executable PDFLATEX_EXECUTABLE]
                [--lualatex-executable LUALATEX_EXECUTABLE]
                [--xelatex-executable XELATEX_EXECUTABLE]
                [--typst-executable TYPST_EXECUTABLE]
                [--portable-apps-dir PORTABLE_APPS_DIR]
                [--skip-requirements-check] [--skip-extension-install]
                [--keep-previous-installation-files] [--all-users]
                [--color {always,never}]
setup.py: error: unrecognized arguments: not found



Walter

**Comment by jcwinkler** [comment]
I mean please just enter the sole command `which pdflatex` in the terminal (without setup.py etc).

I guess what you get is

```bash
> which pdflatex
> pdflatex not found
```
or sth. like this?

**Comment by wglogowski** [comment]
Sorry,


Here it is

MacBook-Air-2 ~ % pdflatex
zsh: command not found: pdflatex
