### ISSUE TITLE
Horizontal lines in tex input not rendered

### ISSUE THREAD

**Issue by SebastianGrGr** [textext/textext#424]
As the title says, the horizontal lines (As in the ones on the top of the square root symbol and the fractional number division line) don't appear on the rendered path but does in the preview.

![image](https://github.com/textext/textext/assets/109915645/bb077a8e-3e9c-4808-8608-5a6c3e34310b)

**Comment by jcwinkler** [comment]
Usually this behaviour only occurs if you re-edit a formula which has been previously colorized via Inkscape (or re-edit a formula which has been copied from a colorized formula).

Is this the case in your scenario?

**Comment by ExpPhysU** [comment]
But that is not the way a usere expects it to work. In that sense it is a bug
