### ISSUE TITLE
TexText extension for Inkscape is not compatible with the MiKTeX

### ISSUE THREAD

**Issue by airton0** [textext/textext#427]
The TexText extension for Inkscape requires an typst.exe file to work. However, MikTeX does not provide such a file and this makes the TexText extension to fail in Inkscape.

**Comment by jcwinkler** [comment]
This ist not correct. Even without typst, TexText ist fully funktional.

If TextText does not work on your system with MikTex installed but typst not, there must be a different error. Please post the log file in this case, so I can help you solving the issue.
