### ISSUE TITLE
Explicit text sizing fails if document scale is not 1.0

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [textext/textext#428]
**Description of the problem/ steps to reproduce**

The description in [FAQ: Explicit setting of font size](https://textext.github.io/textext/usage/faq.html#explicit-setting-of-font-size) appears to work only if document's scale is in its default value (1mm/user unit). When the scale value is changed, textext font size no longer matches Inkscape's text objects.

**System information**

- TexText version: 1.10.2
- Inkscape version: 1.3.2
- Operating system: Windows 10 22H2
- Windows only: LaTeX-distribution MiKTeX
- Windows only: TexText installed via batch script or installer file: batch script

**Comment by jcwinkler** [comment]
Hmm, the FAQ already states that the scale must be set to 1.0:

![grafik](https://github.com/textext/textext/assets/11866252/92e96405-7b61-4b18-be10-353830b58432)

Or do you refer to the settings the Inkscape scale settings:

![grafik](https://github.com/textext/textext/assets/11866252/e8d911a6-6303-40af-b2d0-46e2b103ef6a)

**Comment by tikuma-lsuhsc** [comment]
Yes, the latter, the Inkscape scale setting.

In general, I'm quickly learning that messing with the Inkscape document scale is a bad idea (had Inkscape crashing multiple times because of it) and I have already resolved this issue on my document by reverting the document scale to 1 mm/uu.

It would be nice if this requirement to be at least added to the FAQ. And the best if the document scale can be incorporated into the textext scaling algorithm.

Sorry for not fully expanding the issue initially.

**Comment by jcwinkler** [comment]
I updated the FAQ-section of the documentation.
