### ISSUE TITLE
textext not wrking in manjaro xfce

### ISSUE THREAD

**Issue by acsarda** [textext/textext#433]
Hello!

I am running manjaro 24 with xfce. I download the inkscape appimage 1.3.2 and follow the instructions for installing textext. 
Inkscape works fine, but textext doesn't. I can see Extensions->Text->TexText, but when clicking on it nothing happens. 
I used textext in the past, so I expect the textext window, but nothing.
I wonder if it's something related to gtk and manjaro... I try installing all the dependencies detailed in the textext installation steps for debian/ubuntu based systems but on manjaro , but still no luck.

I will wait for feedback!
Thanks a lot!

**Comment by jcwinkler** [comment]
Hi @acsarda Did you ever succeed running Inkscape and TexText from an AppImgae in the past?

Please try to launch the Extension Manager (Menu Extensions - Manage Extensions). Does it launch? If not there is a problem with the packed pygobject subsystem which TexText as well as the Extension manager is based on.

**Comment by acsarda** [comment]
Hi @jcwinkler ! 
Yes, previously I used to run debian&kde and ubuntu&kde, using inkscape from an appimage, and textext was working alright!

When trying to launch the Extension manager I get a window with these errors
```
Gtk-Message: 21:23:59.521: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:23:59.521: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:23:59.522: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:23:59.522: Failed to load module "canberra-gtk-module"
An error occured with the extensions manager!
Trying to self-update the package... Failed to update!

Please delete the package manually! (see location below)


Please report this error
------------------------

Report URL: https://gitlab.com/inkscape/extras/extension-manager/-/issues
Location: /tmp/.mount_Inkscaggn0hm/usr/share/inkscape/extensions/inkman/inkman/inkman
inkscape-extension-manager: 1.0

Not done
Traceback (most recent call last):
  File "manage_extensions.py", line 61, in recovery_run
    run(args)
  File "manage_extensions.py", line 47, in run
    version = options.for_version or get_inkscape_version()
  File "/tmp/.mount_Inkscaggn0hm/usr/share/inkscape/extensions/inkman/inkman/inkman/utils.py", line 95, in get_inkscape_version
    (major, minor) = line.strip().split(" ")[1].split(".")[:2]
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by acsarda** [comment]
I installed xapp, canberra and [pygobject](https://pygobject.gnome.org/getting_started.html), but still no luck at trying to lunch the extension manager

**Comment by jcwinkler** [comment]
Installing pygobject won't help in this situation since it will never be called from within an AppImage Inkscape instance.

Are you able to install inkscape via `apt-get` ? This would be the more reliable way.
