### ISSUE TITLE
Typst 0.12 output too big

### ISSUE THREAD

**Issue by wenbin-liu** [textext/textext#438]
Textext: 1.10.2
Inkscape: 1.3.2
Typst: 0.12
PC: Windows 10 Enterpise
When using typst 0.12 version, input anything you get the whole page of typst output(a whole a4 page) which didn't occur in 0.11 version.

**Comment by jcwinkler** [comment]
I confirm this problem. `typst` changed the output structure of the generated svg from 0.11 to 0.12. In the most recent version 0.12 of `typst` the generated object is surrounded by a path having full a4-paper format. Thats the reason why the sinppets appear too big when inserted in your svg.

I need to figure out if this behavior can be suppressed by any command line options or if I need to remove the path object by myself in TexText.

**Comment by wenbin-liu** [comment]
Any progress? I didn't find such a command line option. Maybe a preamble may help.

**Comment by wenbin-liu** [comment]
I found that this is due to `fill` argument in page setting. Adding `#set page(fill:none)` can solve this
![图片](https://github.com/user-attachments/assets/cb3df7cc-c6d4-42b7-ab52-0a49c9109951)

**Comment by jcwinkler** [comment]
Thanks for this important news, very good! I will check and implement it this week.

**Comment by jcwinkler** [comment]
@wenbin-liu Could you do me a favor and check the hotfix? Here is the package: [TexText-Windows-1.10.2-dev1.zip](https://github.com/user-attachments/files/17775102/TexText-Windows-1.10.2-dev1.zip)

Thanks!

**Comment by wenbin-liu** [comment]
@jcwinkler Sure. I tested on windows with inkscape 1.3.2 and it  just works as before. Thanks.
