### ISSUE TITLE
Unable to install textext 1.10.2

### ISSUE THREAD

**Issue by wyatt-wong** [textext/textext#441]
I got the following error when I execute `python3 setup.py`

[textextsetup.log](https://github.com/user-attachments/files/17990347/textextsetup.log)

`
[TexText][[41m[97mCRITICAL[0m]: [49m[31m+ [Fail][0m TexText requirements
[TexText][[49m[32mSUCCESS [0m]: [49m[31m/-and-[49m[32m* [Succ][0m Detect inkscape >= 1.3
[TexText][[49m[32mSUCCESS [0m]: [49m[31m|[0m      inkscape=1.4 is found
[TexText][[41m[97mCRITICAL[0m]: [49m[31m/-and-[49m[31m+ [Fail][0m Detect *latex
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m      Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m/--or-[49m[31m* [Fail][0m `pdflatex` is NOT found in PATH
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      If pdflatex is installed in custom location, specify it via 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m             --pdflatex-executable=<path-to-pdflatex>
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      and run setup.py again
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m/--or-[49m[31m* [Fail][0m `lualatex` is NOT found in PATH
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      If lualatex is installed in custom location, specify it via 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m             --lualatex-executable=<path-to-lualatex>
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      and run setup.py again
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m/--or-[49m[31m* [Fail][0m `xelatex` is NOT found in PATH
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      If xelatex is installed in custom location, specify it via 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m             --xelatex-executable=<path-to-xelatex>
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m|[0m      and run setup.py again
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m     [49m[31m/--or-[49m[31m* [Fail][0m `typst` is NOT found in PATH
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m            Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m                   [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-preparation[0m
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m            If typst is installed in custom location, specify it via 
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m                   --typst-executable=<path-to-typst>
[TexText][[41m[97mCRITICAL[0m]: [49m[31m|[0m            and run setup.py again
[TexText][[41m[97mCRITICAL[0m]: [49m[31m/-and-[49m[31m+ [Fail][0m Detect GUI library
[TexText][[41m[97mCRITICAL[0m]:        Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]:               [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gui-library[0m
[TexText][[41m[97mCRITICAL[0m]:       [49m[31m/--or-[49m[31m* [Fail][0m GTK3 is not found
[TexText][[41m[97mCRITICAL[0m]:       [49m[31m|[0m      Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]:       [49m[31m|[0m             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gtk3[0m
[TexText][[41m[97mCRITICAL[0m]:       [49m[31m/--or-[49m[31m* [Fail][0m TkInter is not found
[TexText][[41m[97mCRITICAL[0m]:              Please follow installation instructions at 
[TexText][[41m[97mCRITICAL[0m]:                     [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-tkinter[0m
[TexText][[49m[31mERROR   [0m]: Automatic requirements check found issue
[TexText][[49m[31mERROR   [0m]: Follow instruction above and run install script again
[TexText][[49m[31mERROR   [0m]: To bypass requirement check pass `--skip-requirements-check` to setup.py
`

**Comment by wyatt-wong** [comment]
> The setup does not find a latex compiler (at least, it is not in the path). Which operating system do you use?

I was not aware that a latex compiler is required. It is NOT mentioned in the README.rst

**Comment by wyatt-wong** [comment]
I have downloaded luatex from https://github.com/TeX-Live/luatex and successfully built luatext into binary under the following folder:

luatex/build/texk/web2c/luatex

After that, I executed the following command and have successfully built the TexText and installed to ~/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions folder.

python3 setup.py --pdflatex-executable=$(which luatex) --skip-requirements-check

![Screenshot 2024-12-17 at 2 00 14 AM](https://github.com/user-attachments/assets/a83e55b3-a87f-4bea-9cc9-f0464f011548)

**Comment by jcwinkler** [comment]
> I was not aware that a latex compiler is required. It is NOT mentioned in the README.rst

I added some hints in the documentation to avoid this misunderstanding.

If you really intend to use lualatex you could also use:

```bash
python3 setup.py --lualatex-executable=$(which luatex) --skip-requirements-check
```

and then select `lualatex` in the TexText GUI. See [advanced intall options](https://textext.github.io/textext/install/advanced.html) in the documentation.
