### ISSUE TITLE
can not run on python3 default linux

### ISSUE THREAD

**Issue by doraven** [textext/textext#45]
my ubuntu18.04, soft link /usr/bin/python linked to /usr/bin/python3 , many syntax errors.
Setting back to python2, everything fine now.

Is there any solutions to this?

Is setting python2 as default env the only way?

**Comment by sizmailov** [comment]
I have a fresh install of ubuntu 18.04.1. The default `python` is python2.7:
```bash
    $ ls -l  /usr/bin/python
    lrwxrwxrwx 1 root root 9 окт  5 10:54 /usr/bin/python -> python2.7
```

If you prefer to have python3 as default you should specify path to python2.7 for inkscape, see 
http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters

**Comment by doraven** [comment]
@sizmailov thx, it shall help me a lot
