### ISSUE TITLE
Wrap text in the latex text box

### ISSUE THREAD

**Issue by veltsov** [textext/textext#47]
It would be nice to wrap (automatically move to a new line) the latex text in the editor box. I often copy the latex text from some other source, which might have very long lines due to automatic wrapping usually available in any editor. Such long lines are difficult to work with in the current textext dialog. Unconditionally the wrapping is added by a single-line patch (attached), but full implementation should probably include a checkbox in the menu.
[asktext.py.patch.txt](https://github.com/textext/textext/files/2453297/asktext.py.patch.txt)

**Comment by jcwinkler** [comment]
Thanks @veltsov . I will review this during the week.

**Comment by jcwinkler** [comment]
Should we provide this as a checkbox? I think so.
Should word wrap be a default behaviour? It is a matter of taste. Would not set it as default. User can select it and TexText remembers the state. On a per node basis or on a per machine basis?

**Comment by leberwurstsaft** [comment]
I believe it should be a per user/machine setting.

**Comment by jcwinkler** [comment]
**Word Wrap OFF:**
![grafik](https://user-images.githubusercontent.com/11866252/49169343-db232880-f339-11e8-823e-315e56b8d223.png)

**Word Wrap ON:**
![grafik](https://user-images.githubusercontent.com/11866252/49169474-1d4c6a00-f33a-11e8-899c-4fba269cf8d2.png)

Without GTKSourceView there will be only one entry in the Menu. TK is open.

Any suggestions w.r.t. to the position of the checkbox?

**Comment by sizmailov** [comment]
All looks good to me. The only missing part is storage of values in config. It holds for all menu items, not only "wrap" option. Or I missed something?
