### ISSUE TITLE
Your LaTeX code has problems

### ISSUE THREAD

**Issue by JohnCovering** [textext/textext#48]
Hello,

I tried to run TexText 0.8.1 with Inkscape 0.92.3 on Windows 10, but I got the following error when clicking on the Save button.
The LaTeX code was : $x$

With TexText 0.7.3 I don't have any error.

Your LaTeX code has problems:

Traceback (most recent call last):
  File "asktext.py", line 599, in cb_ok
    self._texcmd_cbox.get_active_text().lower())
  File "textext.py", line 292, in callback
    tex_cmd, original_scale=current_scale)
  File "textext.py", line 393, in do_convert
    new_svg_ele = converter.convert(text, preamble_file, scale_factor, tex_command)
  File "textext.py", line 820, in convert
    self.tex_to_pdf(tex_command, latex_text, preamble_file)
  File "textext.py", line 763, in tex_to_pdf
    raise RuntimeError("Your LaTeX code has problems:\n\n{errors}".format(errors=parsed_log))
RuntimeError: Your LaTeX code has problems:

**Comment by sizmailov** [comment]
I wonder is your error message truncated? Is there anything after `RuntimeError: Your LaTeX code has problems:`?

**Comment by JohnCovering** [comment]
No, there's nothing after "RuntimeError: Your LaTeX code has problems:"

**Comment by michaelhaar** [comment]
I am getting the same error message.

- operating system: Win10 64bit
- inscape version: 0.92.3 with Python 2.7
- Miktex version 2.9.6821
- installed PyGTK-2.24-Inkscape-0.92.3-64bit.exe, pstoedit Version 3.73, ghostscript Version 9.25 and ImageMagick-7.0.8-14-Q16-x64-static.exe as described in the wiki

I also tried to use install textext on my office computer. It also displays the same error message.

Note: The error only occurs if `pdflatex` is selected. `xelatex` works fine 😄

**Comment by michaelhaar** [comment]
@sizmailov TexText version is 0.8.1.

The error doesn't depend on the text itself. It always gives the same error

**Comment by sizmailov** [comment]
Can you create a tex file with following content and compile it from command line with pdflatex? 

one.tex:
```latex
\documentclass{article}

\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}

\pagestyle{empty}
\begin{document}
% ***Your code***
\end{document}
```

two.tex:
```latex
\documentclass{article}

\pagestyle{empty}
\begin{document}
% ***Your code***
\end{document}
```

1) Hit <kbd>Windows</kbd>+<kbd>R</kbd>, enter `cmd`. The command line will appear.
2) enter `cd "<your folder with test tex files>"`; Note the quotes
3) run  `pdflatex.exe one.tex "-interaction=nonstopmode" "-halt-on-error"`
4) run  `pdflatex.exe one.tex "-interaction=nonstopmode" "-halt-on-error"`

Copy output here as markdown code blocks to avoid formatting.

**Comment by michaelhaar** [comment]
Output of one.tex (it wants to install the latex package `mptopdf`)
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6840 64-bit)
entering extended mode
(one.tex
LaTeX2e <2018-04-01> patch level 5
("C:\Program Files\Miktex\tex\latex\base\article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files\Miktex\tex\latex\base\size10.clo"))
("C:\Program Files\Miktex\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\Miktex\tex\latex\amsmath\amstext.sty"
("C:\Program Files\Miktex\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files\Miktex\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files\Miktex\tex\latex\amsmath\amsopn.sty"))
("C:\Program Files\Miktex\tex\latex\amscls\amsthm.sty")
("C:\Program Files\Miktex\tex\latex\amsfonts\amssymb.sty"
("C:\Program Files\Miktex\tex\latex\amsfonts\amsfonts.sty"))
("C:\Program Files\Miktex\tex\latex\graphics\color.sty"
("C:\Program Files\Miktex\tex\latex\graphics-cfg\color.cfg")
("C:\Program Files\Miktex\tex\latex\graphics-def\pdftex.def"))
No file one.aux.
QWindowsWindow::setGeometry: Unable to set geometry 451x317+690+357 on QWidgetWindow/'InstallPackageDialogWindow'. Resulting geometry:  541x317+690+357 (frame: 9, 38, 9, 9, custom margin: 0, 0, 0, 0, minimum size: 541x287, maximum size: 16777215x16777215).

======================================================================
starting package maintenance...
installation directory: "C:\Program Files\Miktex"
package repository: http://mirror.easyname.at/ctan/systems/win32/miktex/tm/packages/
visiting repository http://mirror.easyname.at/ctan/systems/win32/miktex/tm/packages/...
repository type: remote package repository
loading lightweight database...
downloading http://mirror.easyname.at/ctan/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
0.18 MB, 2.38 Mbit/s

Unfortunately, the package mptopdf could not be installed.
Please check the log file:
C:\Users\Michael Haar\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log
======================================================================
(one.aux) )
No pages of output.
Transcript written on one.log.
```

Output of two.tex:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6840 64-bit)
entering extended mode
(two.tex
LaTeX2e <2018-04-01> patch level 5
("C:\Program Files\Miktex\tex\latex\base\article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files\Miktex\tex\latex\base\size10.clo"))
No file two.aux.
(two.aux) )
No pages of output.
Transcript written on two.log.
```

**Comment by sizmailov** [comment]
@michaelhaar Can you confirm next two points? 
1) the empty preamble produce the output (at least for plain text) 
2) after installation of extra packages with MikTex the TexText works with default preamble

**Comment by sizmailov** [comment]
@jcwinkler Can we investigate it deeper? 

On the one hand we should not have in default preamble / .tex template anything beyond default installation. On another hand we can't remove the packages which are already here to maintain backward compatibility. Seems like something happened with tex distribution or packages. 

We probably should add functionality to show full latex log on demand.

**Comment by michaelhaar** [comment]
> @michaelhaar Can you confirm next two points?
> 
> 1. the empty preamble produce the output (at least for plain text)
> 2. after installation of extra packages with MikTex the TexText works with default preamble

I can confirm the second statement 👍 
TexText works with default preamble after installation of the `mptopdf` package (I had to run the `MikTex Console` as administrator ).

**Comment by sizmailov** [comment]
@michaelhaar Good enough, thank you!

**Comment by michaelhaar** [comment]
@jcwinkler I just downloaded the standard Miktex installer from [here](https://miktex.org/download)

**Comment by jcwinkler** [comment]
@michaelhaar Thank you. It explains why some packages are missing on your system. 

@sizmailov 
https://github.com/textext/textext/blob/0935ae6bed8fc0c0775ba6799b40a68610ce8988/extension/textext/__init__.py#L603-L611

I suggest that we pass the full log file to `TexTextConversionError` if the logfileparser does not find anything or even better parse_pdf_log returns the full log file if it does not find any tex file error.

**Comment by sizmailov** [comment]
Created #77, lets move discussion there.

**Comment by sizmailov** [comment]
@JohnCovering Can you confirm the solution works for you too?
