### ISSUE TITLE
Add continuous integration tests

### ISSUE THREAD

**Issue by sizmailov** [textext/textext#57]
TexText is a GUI plugin, so CI does not exclude manual testing. 

Nevertheless some parts of TexText could be automatically tested. For example backward compatibility tests are massive and time consuming. 

What can be done with CI: 
 - backward compatibility checks (newer version is able to operate on svg generated with older versions)
 - back-end interoperability pstoedit/pdf2svg
 - extension installation script

**Comment by jcwinkler** [comment]
Yes, CI tests would be really helpful. Currently I do backward compatibility tests manually using the snippets collection. Question is how to comapare the svg-results without having a "visual look" on them since svg code differs quite a lot, e.g. between pstoedit and pdf2svg.

**Comment by sizmailov** [comment]
I ended up with comparison of png images. It's not perfect, needs adjustments of thresholds, but it's better than nothing. 

Here I cite [commit](
https://github.com/sizmailov/textext/commit/3c10b3792f6969f9104652514ffabda8dd0f2e5d
) message:

> 
> Behaviour of different TexText versions differs. Tests cases check
> minimum existing compatibility which should not break in next releases.
> 
> For versions 0.4-0.6 basically only re-editing is checked
> For version 0.7 added color manipulations check
> For version 0.8 added inkscape transformations preserving
> 
> Each test case contain:
> original.svg - svg with TexText node created with particular TexText version
> modified.svg - GUI edited version of original.svg as described in config.json
> config.json - describes original.svg and modification.svg. Also contains instruction to compare svg
> 
> Test loads original.svg, applies changes described in config.json and saves result in temporary svg.
> Resulting svg is compared to modified.svg according to config.json.

Now I successfully run tests on ubuntu at travis-ci. 

I tried to extend testing environment to MacOS on travis, but miserably failed(. To run tests one need to install *latex and inkscape. It looks like only way is to compile both from source which takes a lot of time. 

Travis recently added windows support https://blog.travis-ci.com/2018-10-11-windows-early-release. 
But it's another (painful?) story.

I think minimum is here and I'm about to create PR. But let's do one thing at a time and finish "clean up" first.

**Comment by jcwinkler** [comment]
Great to hear, thank you!

**Comment by sizmailov** [comment]
@jcwinkler Can you activate travis-ci for this repo?

**Comment by jcwinkler** [comment]
I activated it and put the logo into the develop branch https://github.com/textext/textext/tree/develop
