### ISSUE TITLE
Move doc to github.io, provide solutions for common issues

### ISSUE THREAD

**Issue by sizmailov** [textext/textext#59]
System-specific solution might be to wordy to be readable from popup in plain text, it's worth to have such page with solutions for all problems. 

Current page: https://github.com/textext/textext/wiki/Common-issues

What should be included in each "common-issue"
 1. Description of _observed_ behavior
 2. Error message from TexText if available (We should provide error messages for different TexText versions if messages differ in order to help people find information via google or simple page search)
3. Explanation of root cause of problem 
4. Instruction to fix problem

Here is (incomplete) check list:
- Linux
   - [ ] *latex is not found 
   - [ ] no converter pdf->svg
   - [ ] no converter pdf->png
   - [ ] bad combination of pstoedit+ghostscript
   - [ ] no GUI library
   - [x] preview is not working, but imagemagick is installed 

- Windows
   - [ ] *latex is not found 
   - [ ] no converter pdf->svg
   - [ ] no converter pdf->png
   - [ ] bad combination of pstoedit+ghostscript
   - [ ] no GUI library
   - [ ] preview is not working, but imagemagick is installed 

- Mac OS
   - [ ] *latex is not found 
   - [ ] no converter pdf->svg
   - [ ] no converter pdf->png
   - [ ] bad combination of pstoedit+ghostscript
   - [ ] no GUI library
   - [ ] preview is not working, but imagemagick is installed 

**Important:** references to wiki paragraphs must be permanent since they will be bundled in TexText distribution and should be valid as long as possible. In principle such check can be done in CI.

**Comment by sizmailov** [comment]
Didn't found a way to make links in github wiki pages permanent. If you change the section label, link changes too. Didn't work with markdown or even with restructuredtext. 

A solution would be to move wiki to github pages. Here is first draft rendering: 
https://sizmailov.github.io/textext/

The branch with reworked documentation: https://github.com/sizmailov/textext/tree/build_gh_pages

The documentation is rewritten in restructuredtext.  

The installation part is rewritten for windows and linux in a way to be used as installation instruction and as a reference in case of installation issues. 

The permanent links has form:
```
https://sizmailov.github.io/textext/install/<os>.html#<os>-name
```
for example 
https://sizmailov.github.io/textext/install/windows.html#windows-install-pygtk2

So it's easy to from links to right section in requirement check

Since this issue check list is covered by installation instruction there is no need in special "Common issues" page.

**Comment by sizmailov** [comment]
Here are two examples of setup.py output.

The worst scenario:
![image](https://user-images.githubusercontent.com/2975991/48661845-a4235c00-ea89-11e8-87ee-1824be6d800a.png)

Inkscape is not found: 

![image](https://user-images.githubusercontent.com/2975991/48661871-03816c00-ea8a-11e8-8456-e91f3fc2d8ca.png)

Should we hide help messages with links for non-criticall errors? In latter example only first link is relevant to setup failure, so others are not helpful for most of users.

**Comment by jcwinkler** [comment]
> A solution would be to move wiki to github pages.

This is another good idea and input from you. Working with the WIKI is not very straightforward, I agree. So we should switch to this approach and it would be nice if you could open an appropriate PR. 

Thank you very much.

**Comment by jcwinkler** [comment]
I activated gh-pages for this repository. Development downloads follow.
