### ISSUE TITLE
Store TexText global settings in extensions/textext/config.json

### ISSUE THREAD

**Issue by sizmailov** [textext/textext#69]
Now global settings stored in `./inkscape/textextrc` on Linux/MacOS and in register on Windows. 

The storage of configs in `./<AppName>/` was deprecated. Now `./inkscape/` contains only `textextrc`.
The better location of settings file would be `extensions/textext`. And it can be done for all systems uniformly. 

The format of the config also can be changed to json. The `json` is builtin module, so no need in custom format parser/writer. Another benefit possibility to conveniently store complex values (dicts, lists, etc.)

What would we do with old-format settings? 
1) **Discard**
Simplest solution. Information of previous scale factor and preamble would be lost. Not too much of information though. No need in custom format parsing code anymore. 
2) (optionally) **Import and convert** to new format upon installation in `setup.py`. 
All previous information would be preserved. Custom format parsing code resides only in `setup.py`, but not in plugin code.
3) **Allow both to co-exist**
Worst. What should be used if both exists? Code for both formats adds. 

If we apply this change the old installation procedure should be tweaked to clean up old settings. 

What do you think? 

P.S.: The question arises, because we are about to rely on requirement checks in plugin itself and it requires checks to be 100% correct. Since automatic checks might be (and presumably would be) imperfect we should provide additional handles to help requirements checks pass. For example we can store preferred executable of `inkcape` at installation by providing extra options to `setup.py` like `--inkscape-executable=/opt/inkscape/bin/inkscape`.

**Comment by jcwinkler** [comment]
I would discard it. This setting is only relevant once when creating a new node after the update to 0.9. So there it should be OK to use the default values.

**Comment by sizmailov** [comment]
I would vote for "discard" option too. Implemented in active branch.
