### ISSUE TITLE
Remember last used latex command

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#70]
When having created a new node, e.g. with `xelatex`, and when later creating an additional node from scratch (i.e. not by duplicating and modifying the previously created one) the GUI does not remember that `xelatex` has been used in the previous node. It would be nice if this is the case.

@sizmailov Maybe this can be done in the work on issue #69 (if it has not already been done, I have no time at the moment to go through your code on your fork, was just getting annoyed about this issue the last couple of hours...).

Expected behaviour:
- Editing existing node: Use the command used for last compilation of this node
- Creating a new node: Use command used for compilation of previous node

**Comment by sizmailov** [comment]
So it would be global option, just as `preable file`, right? 
Ok, I'll do it.

**Comment by sizmailov** [comment]
Implemented https://github.com/sizmailov/textext/commit/483053996bbfd4962e79a2bff2811b779f75fc05
