### ISSUE TITLE
Move PyGTK_for_Inkscape?

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#8]
The PyGTK for Inkscape package which is included in this project is just for building packages for Windows users only. In fact, it is not a part of TexText. It is just needed to make TexText run for Windows user without an own Python installation.

You can see this "inconsistancy" in the different versioning: TexText versions increase, PyGTK for Inkscape not necessarily.

I suggest to move it as separate project in the textext-organisation. Any comments?

**Comment by leberwurstsaft** [comment]
Yes, it should go into a separate repository. It's definitely nice that we can put multiple related things into separate places but keep them under the umbrella of the textext org.

**Comment by jcwinkler** [comment]
Movement completed: https://github.com/textext/pygtk-for-inkscape-windows
