### ISSUE TITLE
Automatic development package builds ?

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#82]
It would be nice if packages are being automatically build from the development branch and offered somewhere. Is it possible via Travis-CI and pack them maybe into gh-pages???? (Google results are not clear to me :tired_face: )

**Comment by sizmailov** [comment]
I had it in mind. Travis can do deployment to github-pages and also publish releases. 
The deployment can be limited only to tagged commits. Travis setup is a bit work. I can make it.
