### ISSUE TITLE
Documentation needs update

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#9]
The readme pdf shipped with TexText (from the doc dir) includes all the installation stuff. But when the user opens it, the extension is already installed. It is better to focus on the usage of the extension.

**Comment by jcwinkler** [comment]
Especially, the scale and anchor feature should be explained in detail.

**Comment by raegnar** [comment]
Instructions for OSX would be greatly appreciated as well.  Is there any good way to debug what is going wrong?  Something more useful than Tex Text menu not displaying.

**Comment by jcwinkler** [comment]
Two of my MAC-students are currently preparing a reliable installation procedure for OSX (pstoedit and pdf2svg). Will be available soon.

**Comment by raegnar** [comment]
Any update on mac documentation?  In particular where to get a pre 9.20 version of Ghostcript?

**Comment by jcwinkler** [comment]
> In particular where to get a pre 9.20 version of Ghostcript?

Did you try http://pages.uoregon.edu/koch/ ?

**Comment by raegnar** [comment]
Thanks, I ended up building Ghostscript from source, but it didn't solve my issue.  Is there a good guide to debugging Inkscape extensions?  I'm having trouble even figuring out what is failing.

**Comment by leberwurstsaft** [comment]
>  Is there a good guide to debugging Inkscape extensions?

That was a major nuisance in developing this extension. I couldn't find anything more usable than what we have now. Which is to collect log messages with some sort of log level and dump it all in the text box that is shown when an extension is done.

If someone finds out how to actually debug a running extension, that would be golden!

**Comment by jcwinkler** [comment]
I added a WIKI to this repo and heavily shortened the Readme. 

Please **do not hesitate** to modify and improve the Readme and the Wiki, remove typos, Germanisms, etc...

Thanks!

**Comment by jcwinkler** [comment]
> Thanks, I ended up building Ghostscript from source, but it didn't solve my issue. Is there a good guide to debugging Inkscape extensions? I'm having trouble even figuring out what is failing.

I will open a separate issue for the MAC.
