### ISSUE TITLE
Inconsistent text size in expression

### ISSUE THREAD

**Issue by DavidCheshire** [textext/textext#91]
When I create an expression with a fractional part and a non-fractional part, the characters in the non-fractional part are too big. See the image - the upper expression was rendered by Google Chrome, the lower expression is an SVG created by TexText in Inkscape 0.92.3. The '3' characters between the red horizontal lines are copied to show how the browser renders them the same size as the characters in the fractional part, but in the SVG they are much bigger. 

![clipboard03](https://user-images.githubusercontent.com/9606912/49800995-d6e70a00-fd40-11e8-9f0f-5e3a506062a5.jpg)

I would like the characters to be the same height in both fractional and non-fractional parts.

This can be seen online at http://www.vintagewatchstraps.com/equations2.php

**Comment by sizmailov** [comment]
TexText does not alters output of tex engine. What you get is exactly what pdflatex/lualatex/xelatex generates. 

To understand how TeX renders math see texbook by D. Knuth, chapter 17.

Commands `\displaystyle`/`\textstyle`/`\scriptstyle`/ `\scriptscriptstyle` will alter default math size.

**Comment by DavidCheshire** [comment]
Thanks for your comment. When I set the same expression with TeXworks  and with TeXstudio and generate a pdf output I get the same result as the image at the top of the graphic rendered by Google. Is the output of all of these others wrong, and only TexText correct?

The expression is $$ \frac{1}{E}\frac{dE}{dT}+3\alpha_s-2\alpha_b $$ - perhaps you could try it in your favourite TeX editor, and in TextText, and see what you get?

**Comment by sizmailov** [comment]
`$$` math environment generates *display math* while `$` defines inline (text) math:

![image](https://user-images.githubusercontent.com/2975991/49806277-62c05c80-fd68-11e8-9358-2a36d6dbd28d.png)

Check your input.

**Comment by jcwinkler** [comment]
I cannot reproduce this problem on my Windows installation.

![grafik](https://user-images.githubusercontent.com/11866252/49806573-5e8c4300-fd58-11e8-9891-699d5b842efc.png)

(Top is from direct compilation of the following code via Emacs, bottom from TexText)
```latex
\documentclass[a4paper,11pt]{article}

\usepackage{amsmath}
\usepackage{amssymb}

\begin{document}
$$ \frac{1}{E}\frac{dE}{dT}+3\alpha_s-2\alpha_b $$
\end{document}
```

**Comment by DavidCheshire** [comment]
Yes the difference does occur with the number of $. The formulation I posted with $$ was from my web page, within TexText I was using a single $. When I replace the $ with $$ in TexText the problem goes away. Thank you for resolving that, I will have to remember to use $$ in the future. 

Is there somewhere donations can be made to support the development of TexText?

**Comment by jcwinkler** [comment]
Good to hear that the problem is solved. In the updated doc I will also use the $$ in the screenshot (currently, there is a single $, too)

Best way to contribute is to give feedback on how to improve the extension if you think something is missing, report issues, test new versions, etc.

Thanks!

**Comment by DavidCheshire** [comment]
Thank you.

I was doing a bit of further research into this and this post https://tex.stackexchange.com/questions/503/why-is-preferable-to says that $$ is TeX primitive syntax and LaTeX doesn't officially support $$. I haven't fully understood what the post says, but using $$ is deprecated because it affects paragraph spacing.
